In [1]:
# Instala o ecossistema Foundry com suporte ao RFD3
!pip install -q "rc-foundry[rfd3]"

# Baixa os checkpoints do RFdiffusion3 na pasta de modelos
!foundry install rfd3 --checkpoint-dir models/rfd3

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 517.0/517.0 kB 13.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 35.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 12.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.8/155.8 kB 12.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.6/120.6 kB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.6/56.6 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 848.6/848.6 kB 48.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 915.7/915.7 kB 46.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 59.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.8/109.8 kB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.4/37.4 MB 50.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 79.7 MB/s eta 0:00:00
  Building wheel for assertpy (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires ipykernel==6.17.1, but you have ipykernel 7.3.0 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
notebook 6.5.7 requires jupyter-client<8,>=5.3.4, but you have jupyter-client 8.9.1 which is incompatible.
jupyter-kernel-gateway 2.5.2 requires jupyter-client<8.0,>=5.2.0, but you have jupyter-client 8.9.1 which is incompatible.
Install target: /kaggle/working/models/rfd3

Installing rfd3: RFdiffusion3 checkpoint
  Downloading rfd3_latest.ckpt ━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 GB 58.1 MB/s 0:00:00
✓ Successfully installed rfd3 to /kaggle/working/models/rfd3/rfd3_latest.ckpt

Installation complete!

In [2]:
!git clone https://github.com/dauparas/ProteinMPNN.git

Cloning into 'ProteinMPNN'...
remote: Enumerating objects: 634, done.
remote: Counting objects: 100% (271/271), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 634 (delta 151), reused 146 (delta 146), pack-reused 363 (from 1)
Receiving objects: 100% (634/634), 119.90 MiB | 39.32 MiB/s, done.
Resolving deltas: 100% (290/290), done.

In [3]:
!pip install -q "colabfold[alphafold] @ git+https://github.com/sokrypton/ColabFold"

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.1/264.1 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 50.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.3/374.3 kB 24.2 MB/s eta 0:00:00
  Building wheel for colabfold (pyproject.toml) ... done

In [4]:
# Célula 4: Ampliando o contexto para o RFD3 ver o fragmento como um todo
select_fixed_atoms = "A35-45"

In [5]:
# Célula 5: Nova configuração de Hotspots
import json

rfd3_config = {
    "anexina_binder_design": {
        "dialect": 2,
        "input": "/kaggle/input/datasets/calistu/cropped-rank-frames-d40g-rep1-bioemu-1-1/cropped_rank_08_frame_520_d40g_rep1_bioemu-1.1.pdb",
        # Estratégia 3: Aumentamos o tamanho do binder (70-90) para induzir envelopamento
        "contig": f"{select_fixed_atoms},/0,70-90",
        "is_non_loopy": True,
        "infer_ori_strategy": "hotspots",
        "cif_parser_args": {
            "add_missing_atoms": True
        },
        "select_hotspots": {
            "A37": "CB",
            "A39": "CB",
            "A41": "CB",
            "A45": "CB"
        }
    }
}

with open("rfd3_input.json", "w") as f:
    json.dump(rfd3_config, f, indent=4)
    
print("Configuração do RFD3 atualizada com novos hotspots!")

Configuração do RFD3 atualizada com novos hotspots!

In [6]:
!rfd3 design out_dir=outputs/rfd3_designs inputs=rfd3_input.json ckpt_path=/kaggle/working/models/rfd3/rfd3_latest.ckpt diffusion_batch_size=20

/usr/local/lib/python3.12/dist-packages/hydra/_internal/config_loader_impl.py:216: UserWarning: provider=hydra.searchpath in main, path=configs is not available.
  warnings.warn(
Environment variable CCD_MIRROR_PATH not set. Will not be able to use function requiring this variable. To set it you may:
  (1) add the line 'export VAR_NAME=path/to/variable' to your .bashrc or .zshrc file
  (2) set it in your current shell with 'export VAR_NAME=path/to/variable'
  (3) write it to a .env file in the root of the atomworks.io repository
Environment variable PDB_MIRROR_PATH not set. Will not be able to use function requiring this variable. To set it you may:
  (1) add the line 'export VAR_NAME=path/to/variable' to your .bashrc or .zshrc file
  (2) set it in your current shell with 'export VAR_NAME=path/to/variable'
  (3) write it to a .env file in the root of the atomworks.io repository
20:57:31 DEBUG transforms: Debug mode is on
20:57:34 INFO rfd3.engine: [rank: 0] Outputs will be written to /kaggle/working/outputs/rfd3_designs.
20:57:34 INFO rfd3.engine: [rank: 0] Found 0 existing example IDs in the output directory (0 total).
Using bfloat16 Automatic Mixed Precision (AMP)
20:57:45 WARNING atomworks.io: We can't fix formal charges without building from templates, as we need to know the true number of hydrogens bonded to a given atom, not the inferred number. This may lead to occasional inaccuracies after adding inter-residue bonds. To avoid this and fix formal charges, set `add_missing_atoms = True`.
20:57:46 WARNING atomworks.io: The `extra_fields` argument will be ignored if there is no CIF file input.
21:03:54 INFO rfd3.engine: [rank: 0] Finished inference batch in 368.10 seconds.
21:03:54 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_0 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_0.
21:03:54 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_1 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_1.
21:03:54 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_2 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_2.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_3 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_3.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_4 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_4.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_5 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_5.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_6 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_6.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_7 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_7.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_8 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_8.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_9 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_9.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_10 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_10.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_11 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_11.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_12 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_12.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_13 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_13.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_14 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_14.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_15 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_15.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_16 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_16.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_17 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_17.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_18 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_18.
21:03:55 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_anexina_binder_design_0_model_19 written to /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_19.

In [7]:
#!rm -rf outputs/rfd3_designs/*

In [8]:
#!rm -rf /kaggle/working/outputs/rfd3_pdb/*
#!rm -rf /kaggle/working/outputs/rfd3_pdb_filtered/*
#!rm /kaggle/working/outputs/rfd3_designs/rfd3_input_anexina_binder_design_0_model_0.cif
#!ls /kaggle/working/outputs/rfd3_pdb
#!ls /kaggle/working/outputs/rfd3_pdb_filtered
#!ls /kaggle/working/outputs/rfd3_designs

In [9]:
# Instala o biopython para manipulação de estruturas se necessário
!pip install -q biopython

import os
import gzip
from Bio.PDB import MMCIFParser, PDBIO

cif_dir = "/kaggle/working/outputs/rfd3_designs"
pdb_dir = "/kaggle/working/outputs/rfd3_pdb"
os.makedirs(pdb_dir, exist_ok=True)

parser = MMCIFParser()
io = PDBIO()

print("Iniciando a conversão de arquivos...")
for file in os.listdir(cif_dir):
    if file.endswith(".cif.gz"):
        base_name = file.replace(".cif.gz", "")
        gz_path = os.path.join(cif_dir, file)
        cif_path = os.path.join(cif_dir, base_name + ".cif")
        pdb_path = os.path.join(pdb_dir, base_name + ".pdb")
        
        # 1. Descompactar o arquivo .cif.gz
        with gzip.open(gz_path, 'rb') as f_in:
            with open(cif_path, 'wb') as f_out:
                f_out.write(f_in.read())
        
        # 2. Converter de .cif para .pdb
        try:
            # Silencia os warnings comuns de leitura de CIF
            import warnings
            from Bio.PDB.PDBExceptions import PDBConstructionWarning
            with warnings.catch_warnings():
                warnings.simplefilter('ignore', PDBConstructionWarning)
                structure = parser.get_structure(base_name, cif_path)
                
            io.set_structure(structure)
            io.save(pdb_path)
            print(f"✓ Convertido com sucesso: {base_name}.pdb")
        except Exception as e:
            print(f"✗ Erro ao converter {base_name}: {e}")
            
        # Remover o .cif descompactado temporário para economizar espaço
        #if os.path.exists(cif_path):
        #    os.remove(cif_path)

print(f"\nPronto! Seus arquivos convertidos estão em: {pdb_dir}")

Iniciando a conversão de arquivos...
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_14.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_5.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_17.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_4.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_7.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_10.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_0.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_15.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_8.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_11.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_6.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_3.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_2.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_16.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_12.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_13.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_19.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_18.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_9.pdb
✓ Convertido com sucesso: rfd3_input_anexina_binder_design_0_model_1.pdb

Pronto! Seus arquivos convertidos estão em: /kaggle/working/outputs/rfd3_pdb

In [10]:
import os
import json
import shutil

# Diretórios
cif_dir = "/kaggle/working/outputs/rfd3_designs"
pdb_dir = "/kaggle/working/outputs/rfd3_pdb"
filtered_pdb_dir = "/kaggle/working/outputs/rfd3_pdb_filtered"

# Limpa a pasta antes de começar para evitar misturar execuções antigas
shutil.rmtree(filtered_pdb_dir, ignore_errors=True)
os.makedirs(filtered_pdb_dir, exist_ok=True)

# Critérios de Aceitação Mais Rigorosos
MIN_FRACAO_ESTRUTURADA = 0.70 # Subimos a régua para 70%
MAX_CLASHES = 0
TOP_K_BACKBONES = 10

backbones_candidatos = []

print("Iniciando a filtragem rigorosa de backbones...")

for file in os.listdir(cif_dir):
    if file.endswith(".json"):
        base_name = file.replace(".json", "")
        json_path = os.path.join(cif_dir, file)
        pdb_path = os.path.join(pdb_dir, f"{base_name}.pdb")
        
        if os.path.exists(pdb_path):
            with open(json_path, 'r') as f:
                data = json.load(f)
                metrics = data.get("metrics", {})
            
            fracao = metrics.get("non_loop_fraction", 0)
            clashes = metrics.get("n_clashing.interresidue_clashes_w_backbone", 999)
            desvio = metrics.get("max_ca_deviation", 999)
            
            if fracao >= MIN_FRACAO_ESTRUTURADA and clashes <= MAX_CLASHES:
                backbones_candidatos.append({
                    "base_name": base_name,
                    "pdb_path": pdb_path,
                    "fracao": fracao,
                    "desvio": desvio
                })

# Ordenar: Maior fração estruturada primeiro, e se empatar, menor desvio do alvo
backbones_candidatos.sort(key=lambda x: (-x['fracao'], x['desvio']))

# Pegar apenas a "nata" dos backbones gerados
melhores_backbones = backbones_candidatos[:TOP_K_BACKBONES]

for b in melhores_backbones:
    destino = os.path.join(filtered_pdb_dir, f"{b['base_name']}.pdb")
    shutil.copy2(b['pdb_path'], destino)

print(f"Filtragem concluída!")
print(f"✓ Total que atingiram o limite mínimo (70%): {len(backbones_candidatos)}")
print(f"🏆 Aprovados e enviados para o MPNN (Top {TOP_K_BACKBONES}): {len(melhores_backbones)}")

Iniciando a filtragem rigorosa de backbones...
Filtragem concluída!
✓ Total que atingiram o limite mínimo (70%): 20
🏆 Aprovados e enviados para o MPNN (Top 10): 10

In [11]:
import os
import json
import pandas as pd

cif_dir = "/kaggle/working/outputs/rfd3_designs"
json_data = []

for file in os.listdir(cif_dir):
    if file.endswith(".json"):
        with open(os.path.join(cif_dir, file), 'r') as f:
            data = json.load(f)
            metrics = data.get("metrics", {})
            
            # Extraindo as métricas biofísicas reais do RFD3
            json_data.append({
                "Modelo": file.replace(".json", ""),
                "Clashes (Backbone)": metrics.get("n_clashing.interresidue_clashes_w_backbone", "N/A"),
                "Fração Estruturada": round(metrics.get("non_loop_fraction", 0) * 100, 1), # Em %
                "Qtd Hélices/Folhas": metrics.get("num_ss_elements", "N/A"),
                "Desvio do Alvo (Å)": round(metrics.get("max_ca_deviation", 0), 3),
                "Tamanho do Binder": data.get("specification", {}).get("extra", {}).get("sampled_contig", "").split("P")[0]
            })

df = pd.DataFrame(json_data)
# Ordenar pelos mais estruturados e com menor desvio
df = df.sort_values(by=["Fração Estruturada", "Desvio do Alvo (Å)"], ascending=[False, True])

print("Tabela de Métricas dos Backbones (RFD3):")
display(df)

Tabela de Métricas dos Backbones (RFD3):

,Modelo,Clashes (Backbone),Fração Estruturada,Qtd Hélices/Folhas,Desvio do Alvo (Å),Tamanho do Binder
5,rfd3_input_anexina_binder_design_0_model_4,0,94.3,3,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
14,rfd3_input_anexina_binder_design_0_model_0,0,94.3,3,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
1,rfd3_input_anexina_binder_design_0_model_16,0,94.3,2,0.634,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
9,rfd3_input_anexina_binder_design_0_model_11,0,93.1,3,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
12,rfd3_input_anexina_binder_design_0_model_3,0,92.0,3,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
8,rfd3_input_anexina_binder_design_0_model_19,0,90.8,3,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
10,rfd3_input_anexina_binder_design_0_model_18,0,90.8,3,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
3,rfd3_input_anexina_binder_design_0_model_13,0,89.7,4,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
15,rfd3_input_anexina_binder_design_0_model_17,0,88.5,4,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
2,rfd3_input_anexina_binder_design_0_model_5,0,87.4,2,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
18,rfd3_input_anexina_binder_design_0_model_1,0,87.4,4,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
4,rfd3_input_anexina_binder_design_0_model_8,0,86.2,3,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
19,rfd3_input_anexina_binder_design_0_model_10,0,86.2,4,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
6,rfd3_input_anexina_binder_design_0_model_7,0,85.1,5,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
11,rfd3_input_anexina_binder_design_0_model_6,0,85.1,4,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
13,rfd3_input_anexina_binder_design_0_model_12,0,85.1,4,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
16,rfd3_input_anexina_binder_design_0_model_14,0,83.9,4,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
0,rfd3_input_anexina_binder_design_0_model_9,0,79.3,4,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
17,rfd3_input_anexina_binder_design_0_model_2,0,77.0,6,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"
7,rfd3_input_anexina_binder_design_0_model_15,0,73.6,5,0.456,"A35,A36,A37,A38,A39,A40,A41,A42,A43,A44,A45,/0,87"

In [12]:
!rm -rf /kaggle/working/outputs/mpnn_sequences/seqs/*

In [13]:
import os
import subprocess
from pathlib import Path

# 1. Definir caminhos de entrada e saída
pdb_dir = Path("/kaggle/working/outputs/rfd3_pdb_filtered")
output_base = Path("/kaggle/working/outputs/mpnn_sequences")
output_base.mkdir(parents=True, exist_ok=True)

# 2. Iterar sobre todos os arquivos .pdb do diretório
pdb_files = list(pdb_dir.glob("*.pdb"))

if not pdb_files:
    print(f"Nenhum arquivo .pdb encontrado em {pdb_dir}")
else:
    for p in pdb_files:
        # Extrai apenas o nome base (sem caminho e sem .pdb)
        name = p.stem
        
        print(f"Desenhando sequencias para o backbone: {name}")
        
        out_folder = output_base / name
        out_folder.mkdir(parents=True, exist_ok=True)
        
        cmd = [
            "python", "ProteinMPNN/protein_mpnn_run.py",
            "--pdb_path", str(p),
            "--pdb_path_chains", "B",
            "--out_folder", str(out_folder),
            "--num_seq_per_target", "200",
            "--sampling_temp", "0.25",
            "--seed", "42",
            "--batch_size", "1",
            "--suppress_print", "1"
        ]
        
        # Executa o ProteinMPNN para a estrutura atual
        subprocess.run(cmd, check=True)

    print("Triagem concluída! Próximo passo: submeter os designs ao ColabFold para validação do ipTM.")

Desenhando sequencias para o backbone: rfd3_input_anexina_binder_design_0_model_17
Desenhando sequencias para o backbone: rfd3_input_anexina_binder_design_0_model_11
Desenhando sequencias para o backbone: rfd3_input_anexina_binder_design_0_model_18
Desenhando sequencias para o backbone: rfd3_input_anexina_binder_design_0_model_5
Desenhando sequencias para o backbone: rfd3_input_anexina_binder_design_0_model_4
Desenhando sequencias para o backbone: rfd3_input_anexina_binder_design_0_model_3
Desenhando sequencias para o backbone: rfd3_input_anexina_binder_design_0_model_19
Desenhando sequencias para o backbone: rfd3_input_anexina_binder_design_0_model_16
Desenhando sequencias para o backbone: rfd3_input_anexina_binder_design_0_model_0
Desenhando sequencias para o backbone: rfd3_input_anexina_binder_design_0_model_13
Triagem concluída! Próximo passo: submeter os designs ao ColabFold para validação do ipTM.

In [14]:
#!ls /kaggle/working/outputs/mpnn_sequences/seqs
#!cat /kaggle/working/outputs/mpnn_sequences/seqs/rfd3_input_anexina_binder_design_0_model_0.fa

In [15]:
# Célula 14: Formatação para o AlphaFold Multimer (Foco no Fragmento)
import os
import glob
import re

mpnn_seq_dir = "/kaggle/working/outputs/mpnn_sequences" 
af2_input_dir = "/kaggle/working/outputs/af2_inputs_multimer"
os.makedirs(af2_input_dir, exist_ok=True)

# Proteína inteira (apenas como referência)
alvo_d40g_completo = "MSYPGYPPPPGGYPPAAPGGGPWGGAAYPPPPSMPPIGLGNVATYAGQFNQDYLSGMAANMSGTFGGANMPNLYPGAPGAGYPPVPPGGFGQPPSAQQPVPPYGMYPPPGGNPPSRMPSYPPYPGAPVPGQPMPPPGQQPPGAYPGQPPVTYPGQPPVPLPGQQQPVPSYPGYPGSGTVTPAVPPTQFGSRGTITDAPGFDPLRDAEVLRKAMKGFGTDEQAIIDCLGSRSNKQRQQILLSFKTAYGKDLIKDLKSELSGNFEKTILALMKTPVLFDIYEIKEAIKGVGTDEACLIEILASRSNEHIRELNRAYKAEFKKTLEEAIRSDTSGHFQRLLISLSQGNRDESTNVDMSLAQRDAQELYAAGENRLGTDESKFNAVLCSRSRAHLVAVFNEYQRMTGRDIEKSICREMSGDLEEGMLAVVKCLKNTPAFFAERLNKAMRGAGTKDRTLIRIMVSRSETDLLDIRSEYKRMYGKSLYHDISGDTSGDYRKILLKICGGND"

# Estratégia 1: Extrair apenas o fragmento A34-A45 (índices 24 a 55 em Python)
# Isso resulta em: "GGAAYPPPPSMPPIGLGNVATYAGQFNQDYL"
fragmento_d40g = alvo_d40g_completo[34:45]

TOP_N_POR_BACKBONE = 20
SCORE_MAXIMO = 1.1      

print("Filtrando e formatando complexos (APENAS O FRAGMENTO) para o AlphaFold Multimer...")

total_geradas = 0

for seq_design_folder in glob.glob(f"{mpnn_seq_dir}/*"):
    if not os.path.isdir(seq_design_folder):
        continue
        
    design_name = os.path.basename(seq_design_folder)
    out_subfolder = os.path.join(af2_input_dir, design_name)
    os.makedirs(out_subfolder, exist_ok=True)
    
    for fasta_file in glob.glob(f"{seq_design_folder}/seqs/*.fa"):
        base_name = os.path.basename(fasta_file).replace(".fa", "")
        
        with open(fasta_file, "r") as f:
            linhas = f.readlines()
            
        sequencias_avaliadas = []
            
        for i in range(2, len(linhas), 2):
            header = linhas[i].strip()
            seq_linha = linhas[i+1].strip()
            
            try:
                score = float(re.search(r'score=([\d\.]+)', header).group(1))
                global_score = float(re.search(r'global_score=([\d\.]+)', header).group(1))
            except AttributeError:
                continue
            
            binder_seq = seq_linha.split("/")[0] 
            
            sequencias_avaliadas.append({
                'binder_seq': binder_seq,
                'score': score,
                'global_score': global_score
            })
            
        sequencias_avaliadas.sort(key=lambda x: x['global_score'])
        melhores_seqs = [seq for seq in sequencias_avaliadas if seq['score'] <= SCORE_MAXIMO][:TOP_N_POR_BACKBONE]
        
        contador_seq = 1
        for seq_data in melhores_seqs:
            # Substituímos a proteína inteira apenas pelo fragmento no fasta do AF2
            seq_complexo = f"{fragmento_d40g}:{seq_data['binder_seq']}"
            score_formatado = f"{seq_data['score']:.3f}"
            
            nome_arquivo = f"{out_subfolder}/{base_name}_top{contador_seq}_score{score_formatado}.fasta"
            
            with open(nome_arquivo, "w") as out_f:
                out_f.write(f">{base_name}_top{contador_seq} | score={seq_data['score']} | global_score={seq_data['global_score']}\n{seq_complexo}\n")
                
            contador_seq += 1
            total_geradas += 1

print(f"✓ Pronto! {total_geradas} complexos organizados para validação do fragmento.")

Filtrando e formatando complexos (APENAS O FRAGMENTO) para o AlphaFold Multimer...
✓ Pronto! 200 complexos organizados para validação do fragmento.

In [16]:
#!rm -rf /kaggle/working/outputs/af2_inputs_multimer
#!ls /kaggle/working/outputs/af2_inputs_multimer

In [17]:
import os
import subprocess
from pathlib import Path

input_dir = Path("/kaggle/working/outputs/af2_inputs_multimer")
output_base = Path("/kaggle/working/outputs/af2_predictions_multimer")
output_base.mkdir(parents=True, exist_ok=True)

# Itera sobre todos os subdiretórios
for design_path in input_dir.iterdir():
    if not design_path.is_dir():
        continue
        
    design_name = design_path.name
    print(f"Validando sequências do design: {design_name}")
    
    design_output_dir = output_base / design_name
    design_output_dir.mkdir(parents=True, exist_ok=True)
    
    cmd = [
        "colabfold_batch",
        str(design_path),
        str(design_output_dir),
        "--model-type", "alphafold2_multimer_v3",
        "--num-recycle", "3",
        "--num-models", "1",
        "--custom-template-path", "/kaggle/working/outputs/rfd3_pdb_filtered",
        "--pair-mode", "unpaired_paired",
        "--stop-at-score", "90"
    ]
    
    subprocess.run(cmd, check=True)

Validando sequências do design: rfd3_input_anexina_binder_design_0_model_19
2026-08-15 21:19:48,619 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)

Downloading alphafold2_multimer_v3 weights to /root/.cache/colabfold: 100%|██████████| 3.82G/3.82G [00:16<00:00, 249MB/s]

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-15 21:20:08,808 Running on GPU
2026-08-15 21:20:09,424 Found 5 citations for tools or databases
2026-08-15 21:20:09,871 Query 1/20: rfd3_input_anexina_binder_design_0_model_19_top10_score0.975 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:20:10,805 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-15 21:20:16,819 Sleeping for 8s. Reason: PENDING
2026-08-15 21:21:18,745 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.2 pTM=0.762 ipTM=0.187
2026-08-15 21:21:59,768 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.2 pTM=0.757 ipTM=0.129 tol=0.872
2026-08-15 21:22:05,709 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.6 pTM=0.758 ipTM=0.154 tol=1.64
2026-08-15 21:22:11,707 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84.6 pTM=0.756 ipTM=0.131 tol=0.621
2026-08-15 21:22:11,707 alphafold2_multimer_v3_model_1_seed_000 took 97.1s (3 recycles)
2026-08-15 21:22:11,716 reranking models by 'multimer' metric
2026-08-15 21:22:11,716 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.6 pTM=0.756 ipTM=0.131 ipSAE=0.00525 pDockQ2=0.0155
2026-08-15 21:22:12,086 Query 2/20: rfd3_input_anexina_binder_design_0_model_19_top11_score0.975 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:16 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:22:12,421 Sleeping for 5s. Reason: PENDING
2026-08-15 21:22:17,755 Sleeping for 10s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 21:22:28,753 Sleeping for 7s. Reason: PENDING
2026-08-15 21:22:42,963 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.8 pTM=0.758 ipTM=0.296
2026-08-15 21:22:49,069 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.2 pTM=0.753 ipTM=0.205 tol=1.16
2026-08-15 21:22:55,231 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=82.8 pTM=0.74 ipTM=0.152 tol=0.527
2026-08-15 21:23:01,456 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=82.8 pTM=0.744 ipTM=0.174 tol=0.469
2026-08-15 21:23:01,456 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-15 21:23:01,466 reranking models by 'multimer' metric
2026-08-15 21:23:01,466 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.8 pTM=0.744 ipTM=0.174 ipSAE=0.00775 pDockQ2=0.025
2026-08-15 21:23:01,832 Query 3/20: rfd3_input_anexina_binder_design_0_model_19_top12_score0.982 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:23:02,177 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 21:23:10,171 Sleeping for 7s. Reason: PENDING
2026-08-15 21:23:24,452 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.4 pTM=0.761 ipTM=0.127
2026-08-15 21:23:30,691 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.2 pTM=0.768 ipTM=0.15 tol=1.04
2026-08-15 21:23:36,990 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.9 pTM=0.77 ipTM=0.159 tol=0.964
2026-08-15 21:23:43,338 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85 pTM=0.771 ipTM=0.161 tol=0.271
2026-08-15 21:23:43,339 alphafold2_multimer_v3_model_1_seed_000 took 25.2s (3 recycles)
2026-08-15 21:23:43,348 reranking models by 'multimer' metric
2026-08-15 21:23:43,349 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85 pTM=0.771 ipTM=0.161 ipSAE=0.0061 pDockQ2=0.0189
2026-08-15 21:23:43,731 Query 4/20: rfd3_input_anexina_binder_design_0_model_19_top13_score0.990 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:23:44,065 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 21:23:53,062 Sleeping for 5s. Reason: PENDING
2026-08-15 21:24:05,253 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79.8 pTM=0.707 ipTM=0.13
2026-08-15 21:24:11,374 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.7 pTM=0.729 ipTM=0.0919 tol=2.01
2026-08-15 21:24:17,589 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.5 pTM=0.732 ipTM=0.0989 tol=0.785
2026-08-15 21:24:23,872 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=82.1 pTM=0.733 ipTM=0.11 tol=1.89
2026-08-15 21:24:23,873 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 21:24:23,882 reranking models by 'multimer' metric
2026-08-15 21:24:23,882 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.1 pTM=0.733 ipTM=0.11 ipSAE=0.00528 pDockQ2=0.0161
2026-08-15 21:24:24,246 Query 5/20: rfd3_input_anexina_binder_design_0_model_19_top14_score0.991 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:24:24,553 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 21:24:30,453 Sleeping for 9s. Reason: PENDING
2026-08-15 21:24:46,611 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.8 pTM=0.736 ipTM=0.104
2026-08-15 21:24:52,816 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.1 pTM=0.763 ipTM=0.161 tol=4.3
2026-08-15 21:24:59,099 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.1 pTM=0.764 ipTM=0.129 tol=1.24
2026-08-15 21:25:05,463 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=83.6 pTM=0.759 ipTM=0.133 tol=0.547
2026-08-15 21:25:05,464 alphafold2_multimer_v3_model_1_seed_000 took 25.1s (3 recycles)
2026-08-15 21:25:05,472 reranking models by 'multimer' metric
2026-08-15 21:25:05,472 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.6 pTM=0.759 ipTM=0.133 ipSAE=0.00559 pDockQ2=0.0178
2026-08-15 21:25:05,828 Query 6/20: rfd3_input_anexina_binder_design_0_model_19_top15_score0.992 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:25:06,134 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:25:15,032 Sleeping for 9s. Reason: PENDING
2026-08-15 21:25:31,161 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82.7 pTM=0.75 ipTM=0.121
2026-08-15 21:25:37,329 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.4 pTM=0.769 ipTM=0.157 tol=2.15
2026-08-15 21:25:43,585 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.6 pTM=0.769 ipTM=0.166 tol=0.438
2026-08-15 21:25:43,586 alphafold2_multimer_v3_model_1_seed_000 took 18.6s (2 recycles)
2026-08-15 21:25:43,595 reranking models by 'multimer' metric
2026-08-15 21:25:43,595 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.6 pTM=0.769 ipTM=0.166 ipSAE=0.00614 pDockQ2=0.019
2026-08-15 21:25:43,961 Query 7/20: rfd3_input_anexina_binder_design_0_model_19_top16_score0.986 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:25:44,257 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 21:25:51,157 Sleeping for 9s. Reason: PENDING
2026-08-15 21:26:07,437 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=80.7 pTM=0.734 ipTM=0.105
2026-08-15 21:26:13,725 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.6 pTM=0.723 ipTM=0.113 tol=0.357
2026-08-15 21:26:13,725 alphafold2_multimer_v3_model_1_seed_000 took 12.6s (1 recycles)
2026-08-15 21:26:13,734 reranking models by 'multimer' metric
2026-08-15 21:26:13,734 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.6 pTM=0.723 ipTM=0.113 ipSAE=0.00522 pDockQ2=0.0144
2026-08-15 21:26:14,088 Query 8/20: rfd3_input_anexina_binder_design_0_model_19_top17_score0.994 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:26:14,404 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 21:26:23,435 Sleeping for 8s. Reason: PENDING
2026-08-15 21:26:38,680 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84 pTM=0.737 ipTM=0.117
2026-08-15 21:26:44,881 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.9 pTM=0.752 ipTM=0.117 tol=0.509
2026-08-15 21:26:51,172 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.5 pTM=0.753 ipTM=0.126 tol=0.409
2026-08-15 21:26:51,172 alphafold2_multimer_v3_model_1_seed_000 took 18.8s (2 recycles)
2026-08-15 21:26:51,183 reranking models by 'multimer' metric
2026-08-15 21:26:51,183 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.5 pTM=0.753 ipTM=0.126 ipSAE=0.00504 pDockQ2=0.0175
2026-08-15 21:26:51,545 Query 9/20: rfd3_input_anexina_binder_design_0_model_19_top18_score0.994 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:26:51,906 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 21:27:00,918 Sleeping for 7s. Reason: PENDING
2026-08-15 21:27:15,146 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82.3 pTM=0.722 ipTM=0.111
2026-08-15 21:27:21,323 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.6 pTM=0.739 ipTM=0.131 tol=1.5
2026-08-15 21:27:27,589 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.8 pTM=0.752 ipTM=0.15 tol=0.395
2026-08-15 21:27:27,589 alphafold2_multimer_v3_model_1_seed_000 took 18.7s (2 recycles)
2026-08-15 21:27:27,599 reranking models by 'multimer' metric
2026-08-15 21:27:27,599 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.8 pTM=0.752 ipTM=0.15 ipSAE=0.00605 pDockQ2=0.0172
2026-08-15 21:27:27,959 Query 10/20: rfd3_input_anexina_binder_design_0_model_19_top19_score0.993 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:27:28,299 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]

2026-08-15 21:27:36,294 Sleeping for 10s. Reason: PENDING
2026-08-15 21:27:53,567 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.7 pTM=0.704 ipTM=0.111
2026-08-15 21:27:59,806 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83 pTM=0.754 ipTM=0.0934 tol=1.75
2026-08-15 21:28:06,124 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.1 pTM=0.749 ipTM=0.0986 tol=1.47
2026-08-15 21:28:12,529 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=83.5 pTM=0.75 ipTM=0.0995 tol=1.5
2026-08-15 21:28:12,529 alphafold2_multimer_v3_model_1_seed_000 took 25.2s (3 recycles)
2026-08-15 21:28:12,538 reranking models by 'multimer' metric
2026-08-15 21:28:12,538 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.5 pTM=0.75 ipTM=0.0995 ipSAE=0.0046 pDockQ2=0.0138
2026-08-15 21:28:12,901 Query 11/20: rfd3_input_anexina_binder_design_0_model_19_top1_score0.847 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:28:13,233 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 21:28:20,205 Sleeping for 10s. Reason: PENDING
2026-08-15 21:28:37,415 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=73.8 pTM=0.63 ipTM=0.0847
2026-08-15 21:28:43,552 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=73.6 pTM=0.636 ipTM=0.0966 tol=5.25
2026-08-15 21:28:49,765 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=74.1 pTM=0.636 ipTM=0.0846 tol=0.673
2026-08-15 21:28:56,060 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=75.2 pTM=0.653 ipTM=0.0968 tol=4.39
2026-08-15 21:28:56,060 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 21:28:56,068 reranking models by 'multimer' metric
2026-08-15 21:28:56,068 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=75.2 pTM=0.653 ipTM=0.0968 ipSAE=0 pDockQ2=0.0131
2026-08-15 21:28:56,425 Query 12/20: rfd3_input_anexina_binder_design_0_model_19_top20_score0.993 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:28:56,737 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 21:29:04,664 Sleeping for 5s. Reason: PENDING
2026-08-15 21:29:17,115 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.1 pTM=0.748 ipTM=0.243
2026-08-15 21:29:23,310 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=86.5 pTM=0.76 ipTM=0.193 tol=2.35
2026-08-15 21:29:29,578 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.2 pTM=0.753 ipTM=0.167 tol=0.509
2026-08-15 21:29:35,911 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84.9 pTM=0.754 ipTM=0.171 tol=0.502
2026-08-15 21:29:35,911 alphafold2_multimer_v3_model_1_seed_000 took 25.0s (3 recycles)
2026-08-15 21:29:35,921 reranking models by 'multimer' metric
2026-08-15 21:29:35,921 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.9 pTM=0.754 ipTM=0.171 ipSAE=0.00582 pDockQ2=0.0167
2026-08-15 21:29:36,267 Query 13/20: rfd3_input_anexina_binder_design_0_model_19_top2_score0.879 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:29:36,557 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 21:29:46,441 Sleeping for 9s. Reason: PENDING
2026-08-15 21:30:02,547 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.8 pTM=0.701 ipTM=0.102
2026-08-15 21:30:08,698 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.4 pTM=0.729 ipTM=0.101 tol=2.71
2026-08-15 21:30:14,936 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.9 pTM=0.732 ipTM=0.102 tol=0.355
2026-08-15 21:30:14,936 alphafold2_multimer_v3_model_1_seed_000 took 18.6s (2 recycles)
2026-08-15 21:30:14,944 reranking models by 'multimer' metric
2026-08-15 21:30:14,944 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.9 pTM=0.732 ipTM=0.102 ipSAE=0.00527 pDockQ2=0.0146
2026-08-15 21:30:15,285 Query 14/20: rfd3_input_anexina_binder_design_0_model_19_top3_score0.916 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:30:15,595 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 21:30:24,775 Sleeping for 6s. Reason: PENDING
2026-08-15 21:30:38,052 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=68.9 pTM=0.594 ipTM=0.0792
2026-08-15 21:30:44,355 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.8 pTM=0.717 ipTM=0.0956 tol=2.9
2026-08-15 21:30:50,745 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.4 pTM=0.735 ipTM=0.14 tol=0.652
2026-08-15 21:30:57,137 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85.9 pTM=0.745 ipTM=0.139 tol=0.594
2026-08-15 21:30:57,138 alphafold2_multimer_v3_model_1_seed_000 took 25.4s (3 recycles)
2026-08-15 21:30:57,146 reranking models by 'multimer' metric
2026-08-15 21:30:57,147 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.9 pTM=0.745 ipTM=0.139 ipSAE=0.00572 pDockQ2=0.0167
2026-08-15 21:30:57,491 Query 15/20: rfd3_input_anexina_binder_design_0_model_19_top4_score0.934 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:30:57,783 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 21:31:05,705 Sleeping for 8s. Reason: PENDING
2026-08-15 21:31:20,800 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=87.7 pTM=0.789 ipTM=0.292
2026-08-15 21:31:26,929 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.4 pTM=0.797 ipTM=0.282 tol=0.579
2026-08-15 21:31:33,127 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.6 pTM=0.798 ipTM=0.288 tol=0.651
2026-08-15 21:31:39,414 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=87.7 pTM=0.797 ipTM=0.291 tol=0.324
2026-08-15 21:31:39,414 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 21:31:39,423 reranking models by 'multimer' metric
2026-08-15 21:31:39,424 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.7 pTM=0.797 ipTM=0.291 ipSAE=0.0141 pDockQ2=0.0503
2026-08-15 21:31:39,792 Query 16/20: rfd3_input_anexina_binder_design_0_model_19_top5_score0.949 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:36 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:31:40,091 Sleeping for 10s. Reason: PENDING
2026-08-15 21:31:50,395 Sleeping for 7s. Reason: PENDING
2026-08-15 21:31:57,682 Sleeping for 9s. Reason: PENDING
2026-08-15 21:32:06,995 Sleeping for 9s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]

2026-08-15 21:32:16,860 Sleeping for 5s. Reason: PENDING
2026-08-15 21:32:22,164 Sleeping for 5s. Reason: PENDING
2026-08-15 21:32:34,393 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78 pTM=0.67 ipTM=0.0858
2026-08-15 21:32:40,641 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.3 pTM=0.745 ipTM=0.13 tol=2.2
2026-08-15 21:32:46,984 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.6 pTM=0.75 ipTM=0.119 tol=0.656
2026-08-15 21:32:53,396 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84.2 pTM=0.75 ipTM=0.108 tol=0.861
2026-08-15 21:32:53,397 alphafold2_multimer_v3_model_1_seed_000 took 25.3s (3 recycles)
2026-08-15 21:32:53,405 reranking models by 'multimer' metric
2026-08-15 21:32:53,405 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.2 pTM=0.75 ipTM=0.108 ipSAE=0.00471 pDockQ2=0.0144
2026-08-15 21:32:53,779 Query 17/20: rfd3_input_anexina_binder_design_0_model_19_top6_score0.964 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:32:54,074 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 21:33:04,064 Sleeping for 9s. Reason: PENDING
2026-08-15 21:33:20,240 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79.1 pTM=0.711 ipTM=0.119
2026-08-15 21:33:26,405 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.9 pTM=0.763 ipTM=0.172 tol=1.23
2026-08-15 21:33:32,643 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.9 pTM=0.763 ipTM=0.143 tol=0.733
2026-08-15 21:33:38,972 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84 pTM=0.766 ipTM=0.147 tol=1.5
2026-08-15 21:33:38,973 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 21:33:38,981 reranking models by 'multimer' metric
2026-08-15 21:33:38,981 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84 pTM=0.766 ipTM=0.147 ipSAE=0.00653 pDockQ2=0.0208
2026-08-15 21:33:39,382 Query 18/20: rfd3_input_anexina_binder_design_0_model_19_top7_score0.963 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:14 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:33:39,709 Sleeping for 5s. Reason: PENDING
2026-08-15 21:33:45,043 Sleeping for 8s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 21:33:54,031 Sleeping for 5s. Reason: PENDING
2026-08-15 21:34:06,257 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86.1 pTM=0.763 ipTM=0.166
2026-08-15 21:34:12,457 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=86.1 pTM=0.761 ipTM=0.124 tol=0.819
2026-08-15 21:34:18,753 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.4 pTM=0.76 ipTM=0.131 tol=0.394
2026-08-15 21:34:18,754 alphafold2_multimer_v3_model_1_seed_000 took 18.7s (2 recycles)
2026-08-15 21:34:18,762 reranking models by 'multimer' metric
2026-08-15 21:34:18,762 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.4 pTM=0.76 ipTM=0.131 ipSAE=0.00491 pDockQ2=0.015
2026-08-15 21:34:19,129 Query 19/20: rfd3_input_anexina_binder_design_0_model_19_top8_score0.964 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:34:19,472 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 21:34:28,476 Sleeping for 8s. Reason: PENDING
2026-08-15 21:34:43,771 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.6 pTM=0.769 ipTM=0.172
2026-08-15 21:34:49,999 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.7 pTM=0.765 ipTM=0.133 tol=1.07
2026-08-15 21:34:56,311 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.6 pTM=0.769 ipTM=0.157 tol=1.9
2026-08-15 21:35:02,677 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85 pTM=0.765 ipTM=0.124 tol=1.5
2026-08-15 21:35:02,678 alphafold2_multimer_v3_model_1_seed_000 took 25.2s (3 recycles)
2026-08-15 21:35:02,686 reranking models by 'multimer' metric
2026-08-15 21:35:02,687 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85 pTM=0.765 ipTM=0.124 ipSAE=0.00493 pDockQ2=0.0172
2026-08-15 21:35:03,062 Query 20/20: rfd3_input_anexina_binder_design_0_model_19_top9_score0.970 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:35:03,360 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 21:35:14,264 Sleeping for 8s. Reason: PENDING
2026-08-15 21:35:29,382 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=75.8 pTM=0.636 ipTM=0.121
2026-08-15 21:35:35,521 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=76.2 pTM=0.647 ipTM=0.0985 tol=0.867
2026-08-15 21:35:41,752 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=75.5 pTM=0.639 ipTM=0.117 tol=0.429
2026-08-15 21:35:41,753 alphafold2_multimer_v3_model_1_seed_000 took 18.5s (2 recycles)
2026-08-15 21:35:41,762 reranking models by 'multimer' metric
2026-08-15 21:35:41,762 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=75.5 pTM=0.639 ipTM=0.117 ipSAE=0.00475 pDockQ2=0.0127
2026-08-15 21:35:42,122 Done
Validando sequências do design: rfd3_input_anexina_binder_design_0_model_0

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-15 21:35:45,946 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-15 21:35:46,718 Running on GPU
2026-08-15 21:35:47,018 Found 5 citations for tools or databases
2026-08-15 21:35:47,305 Query 1/20: rfd3_input_anexina_binder_design_0_model_0_top10_score0.983 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:35:48,142 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-15 21:35:54,074 Sleeping for 6s. Reason: PENDING
2026-08-15 21:36:53,611 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.3 pTM=0.786 ipTM=0.104
2026-08-15 21:37:35,518 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.8 pTM=0.796 ipTM=0.107 tol=1.14
2026-08-15 21:37:41,793 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=86.2 pTM=0.798 ipTM=0.145 tol=1.4
2026-08-15 21:37:48,168 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=86.6 pTM=0.796 ipTM=0.144 tol=0.37
2026-08-15 21:37:48,169 alphafold2_multimer_v3_model_1_seed_000 took 98.8s (3 recycles)
2026-08-15 21:37:48,178 reranking models by 'multimer' metric
2026-08-15 21:37:48,178 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=86.6 pTM=0.796 ipTM=0.144 ipSAE=0.00558 pDockQ2=0.0178
2026-08-15 21:37:48,541 Query 2/20: rfd3_input_anexina_binder_design_0_model_0_top11_score0.984 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:30 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:37:48,861 Sleeping for 6s. Reason: PENDING
2026-08-15 21:37:55,155 Sleeping for 10s. Reason: PENDING
2026-08-15 21:38:05,454 Sleeping for 6s. Reason: PENDING
2026-08-15 21:38:11,739 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:24 remaining: 00:00]

2026-08-15 21:38:19,643 Sleeping for 9s. Reason: PENDING
2026-08-15 21:38:28,946 Sleeping for 9s. Reason: PENDING
2026-08-15 21:38:38,277 Sleeping for 5s. Reason: PENDING
2026-08-15 21:38:50,450 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.6 pTM=0.781 ipTM=0.109
2026-08-15 21:38:56,646 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.2 pTM=0.777 ipTM=0.108 tol=0.63
2026-08-15 21:39:02,915 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.1 pTM=0.779 ipTM=0.11 tol=0.175
2026-08-15 21:39:02,916 alphafold2_multimer_v3_model_1_seed_000 took 18.7s (2 recycles)
2026-08-15 21:39:02,925 reranking models by 'multimer' metric
2026-08-15 21:39:02,925 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.1 pTM=0.779 ipTM=0.11 ipSAE=0.0045 pDockQ2=0.0138
2026-08-15 21:39:03,301 Query 3/20: rfd3_input_anexina_binder_design_0_model_0_top12_score0.984 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:39:03,591 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 01:18 remaining: 00:00]

2026-08-15 21:39:10,495 Sleeping for 8s. Reason: PENDING
2026-08-15 21:39:18,794 Sleeping for 6s. Reason: PENDING
2026-08-15 21:39:25,076 Sleeping for 8s. Reason: PENDING
2026-08-15 21:39:33,366 Sleeping for 9s. Reason: PENDING
2026-08-15 21:39:42,654 Sleeping for 8s. Reason: PENDING
2026-08-15 21:39:50,966 Sleeping for 6s. Reason: PENDING
2026-08-15 21:39:57,262 Sleeping for 10s. Reason: PENDING
2026-08-15 21:40:07,558 Sleeping for 5s. Reason: PENDING
2026-08-15 21:40:12,849 Sleeping for 10s. Reason: PENDING
2026-08-15 21:40:23,140 Sleeping for 5s. Reason: PENDING
2026-08-15 21:40:35,405 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.3 pTM=0.739 ipTM=0.0809
2026-08-15 21:40:41,662 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=82.4 pTM=0.753 ipTM=0.0905 tol=0.937
2026-08-15 21:40:47,988 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83 pTM=0.757 ipTM=0.092 tol=0.328
2026-08-15 21:40:47,989 alphafold2_multimer_v3_model_1_seed_000 took 18.8s (2 recycles)
2026-08-15 21:40:47,997 reranking models by 'multimer' metric
2026-08-15 21:40:47,997 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83 pTM=0.757 ipTM=0.092 ipSAE=0 pDockQ2=0.0116
2026-08-15 21:40:48,363 Query 4/20: rfd3_input_anexina_binder_design_0_model_0_top13_score0.989 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 08:37 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:40:48,685 Sleeping for 6s. Reason: PENDING
2026-08-15 21:40:55,016 Sleeping for 7s. Reason: PENDING
2026-08-15 21:41:02,351 Sleeping for 9s. Reason: PENDING
2026-08-15 21:41:11,676 Sleeping for 10s. Reason: PENDING
2026-08-15 21:41:22,013 Sleeping for 10s. Reason: PENDING
2026-08-15 21:41:32,330 Sleeping for 7s. Reason: PENDING
2026-08-15 21:41:39,660 Sleeping for 9s. Reason: PENDING
2026-08-15 21:41:49,010 Sleeping for 5s. Reason: PENDING
2026-08-15 21:41:54,352 Sleeping for 5s. Reason: PENDING
2026-08-15 21:41:59,672 Sleeping for 9s. Reason: PENDING
2026-08-15 21:42:09,040 Sleeping for 9s. Reason: PENDING
2026-08-15 21:42:18,369 Sleeping for 5s. Reason: PENDING
2026-08-15 21:42:23,703 Sleeping for 10s. Reason: PENDING
2026-08-15 21:42:34,371 Sleeping for 9s. Reason: PENDING
2026-08-15 21:42:43,737 Sleeping for 9s. Reason: PENDING
2026-08-15 21:42:53,022 Sleeping for 6s. Reason: PENDING
2026-08-15 21:42:59,317 Sleeping for 8s. Reason: PENDING
2026-08-15 21:43:07,614 Sleeping for 5s. Reason: PENDING
2026-08-15 21:43:12,902 Sleeping for 7s. Reason: PENDING
2026-08-15 21:43:20,226 Sleeping for 5s. Reason: PENDING
2026-08-15 21:43:25,524 Sleeping for 10s. Reason: PENDING
2026-08-15 21:43:35,830 Sleeping for 6s. Reason: PENDING
2026-08-15 21:43:42,113 Sleeping for 6s. Reason: PENDING
2026-08-15 21:43:48,398 Sleeping for 5s. Reason: PENDING
2026-08-15 21:43:53,701 Sleeping for 6s. Reason: PENDING
2026-08-15 21:43:59,997 Sleeping for 7s. Reason: PENDING
2026-08-15 21:44:07,282 Sleeping for 8s. Reason: PENDING
2026-08-15 21:44:15,580 Sleeping for 10s. Reason: PENDING
2026-08-15 21:44:25,888 Sleeping for 10s. Reason: PENDING
2026-08-15 21:44:36,195 Sleeping for 8s. Reason: PENDING
2026-08-15 21:44:44,501 Sleeping for 9s. Reason: PENDING
2026-08-15 21:44:53,790 Sleeping for 5s. Reason: PENDING
2026-08-15 21:44:59,089 Sleeping for 8s. Reason: PENDING
2026-08-15 21:45:07,431 Sleeping for 10s. Reason: PENDING
2026-08-15 21:45:17,716 Sleeping for 10s. Reason: PENDING
2026-08-15 21:45:28,028 Sleeping for 10s. Reason: PENDING
2026-08-15 21:45:38,317 Sleeping for 8s. Reason: PENDING
2026-08-15 21:45:46,611 Sleeping for 5s. Reason: PENDING
2026-08-15 21:45:51,896 Sleeping for 9s. Reason: PENDING
2026-08-15 21:46:01,194 Sleeping for 10s. Reason: PENDING
2026-08-15 21:46:11,490 Sleeping for 10s. Reason: PENDING
2026-08-15 21:46:21,784 Sleeping for 7s. Reason: PENDING
2026-08-15 21:46:29,099 Sleeping for 10s. Reason: PENDING
2026-08-15 21:46:39,435 Sleeping for 10s. Reason: PENDING
2026-08-15 21:46:49,735 Sleeping for 9s. Reason: PENDING
2026-08-15 21:46:59,036 Sleeping for 9s. Reason: PENDING
2026-08-15 21:47:08,334 Sleeping for 5s. Reason: PENDING
2026-08-15 21:47:13,663 Sleeping for 10s. Reason: PENDING
2026-08-15 21:47:23,962 Sleeping for 7s. Reason: PENDING
2026-08-15 21:47:31,250 Sleeping for 7s. Reason: PENDING
2026-08-15 21:47:38,542 Sleeping for 7s. Reason: PENDING
2026-08-15 21:47:45,829 Sleeping for 7s. Reason: PENDING
2026-08-15 21:47:53,131 Sleeping for 9s. Reason: PENDING
2026-08-15 21:48:02,420 Sleeping for 7s. Reason: PENDING
2026-08-15 21:48:09,711 Sleeping for 8s. Reason: PENDING
2026-08-15 21:48:17,996 Sleeping for 5s. Reason: PENDING
2026-08-15 21:48:23,291 Sleeping for 10s. Reason: PENDING
2026-08-15 21:48:33,581 Sleeping for 10s. Reason: PENDING
2026-08-15 21:48:43,894 Sleeping for 10s. Reason: PENDING
2026-08-15 21:48:54,184 Sleeping for 8s. Reason: PENDING
2026-08-15 21:49:02,475 Sleeping for 6s. Reason: PENDING
2026-08-15 21:49:08,777 Sleeping for 7s. Reason: PENDING
2026-08-15 21:49:16,064 Sleeping for 9s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:15 remaining: 00:00]

2026-08-15 21:49:25,981 Sleeping for 6s. Reason: PENDING
2026-08-15 21:49:32,304 Sleeping for 8s. Reason: RUNNING
2026-08-15 21:49:47,425 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=88.7 pTM=0.822 ipTM=0.413
2026-08-15 21:49:53,583 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=88.4 pTM=0.816 ipTM=0.296 tol=0.524
2026-08-15 21:49:59,825 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=88.3 pTM=0.818 ipTM=0.29 tol=0.201
2026-08-15 21:49:59,826 alphafold2_multimer_v3_model_1_seed_000 took 18.6s (2 recycles)
2026-08-15 21:49:59,835 reranking models by 'multimer' metric
2026-08-15 21:49:59,835 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=88.3 pTM=0.818 ipTM=0.29 ipSAE=0.0156 pDockQ2=0.0512
2026-08-15 21:50:00,180 Query 5/20: rfd3_input_anexina_binder_design_0_model_0_top14_score0.988 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:50:00,473 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 21:50:11,366 Sleeping for 10s. Reason: PENDING
2026-08-15 21:50:28,520 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.1 pTM=0.784 ipTM=0.205
2026-08-15 21:50:34,757 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.3 pTM=0.788 ipTM=0.216 tol=0.449
2026-08-15 21:50:34,758 alphafold2_multimer_v3_model_1_seed_000 took 12.5s (1 recycles)
2026-08-15 21:50:34,766 reranking models by 'multimer' metric
2026-08-15 21:50:34,767 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.3 pTM=0.788 ipTM=0.216 ipSAE=0.00924 pDockQ2=0.0339
2026-08-15 21:50:35,119 Query 6/20: rfd3_input_anexina_binder_design_0_model_0_top15_score1.001 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:50:35,410 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 21:50:45,267 Sleeping for 6s. Reason: PENDING
2026-08-15 21:50:58,436 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85 pTM=0.778 ipTM=0.0939
2026-08-15 21:51:04,660 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.9 pTM=0.781 ipTM=0.122 tol=0.621
2026-08-15 21:51:10,947 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.9 pTM=0.782 ipTM=0.12 tol=0.393
2026-08-15 21:51:10,947 alphafold2_multimer_v3_model_1_seed_000 took 18.8s (2 recycles)
2026-08-15 21:51:10,956 reranking models by 'multimer' metric
2026-08-15 21:51:10,956 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.9 pTM=0.782 ipTM=0.12 ipSAE=0.00493 pDockQ2=0.0146
2026-08-15 21:51:11,307 Query 7/20: rfd3_input_anexina_binder_design_0_model_0_top16_score1.001 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:51:11,616 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 21:51:19,505 Sleeping for 7s. Reason: PENDING
2026-08-15 21:51:33,586 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.1 pTM=0.772 ipTM=0.209
2026-08-15 21:51:39,719 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.2 pTM=0.768 ipTM=0.199 tol=0.707
2026-08-15 21:51:45,915 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.4 pTM=0.77 ipTM=0.183 tol=0.226
2026-08-15 21:51:45,916 alphafold2_multimer_v3_model_1_seed_000 took 18.5s (2 recycles)
2026-08-15 21:51:45,925 reranking models by 'multimer' metric
2026-08-15 21:51:45,925 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.4 pTM=0.77 ipTM=0.183 ipSAE=0.00704 pDockQ2=0.0223
2026-08-15 21:51:46,254 Query 8/20: rfd3_input_anexina_binder_design_0_model_0_top17_score1.004 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:51:46,550 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 21:51:57,451 Sleeping for 5s. Reason: PENDING
2026-08-15 21:52:09,541 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=88 pTM=0.795 ipTM=0.0933
2026-08-15 21:52:15,708 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=88.2 pTM=0.801 ipTM=0.11 tol=0.845
2026-08-15 21:52:21,955 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=88.1 pTM=0.799 ipTM=0.112 tol=0.582
2026-08-15 21:52:28,301 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=88.1 pTM=0.801 ipTM=0.131 tol=0.613
2026-08-15 21:52:28,302 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 21:52:28,311 reranking models by 'multimer' metric
2026-08-15 21:52:28,311 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=88.1 pTM=0.801 ipTM=0.131 ipSAE=0.00527 pDockQ2=0.0145
2026-08-15 21:52:28,648 Query 9/20: rfd3_input_anexina_binder_design_0_model_0_top18_score1.003 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:24 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:52:29,016 Sleeping for 5s. Reason: PENDING
2026-08-15 21:52:34,351 Sleeping for 9s. Reason: RUNNING
2026-08-15 21:52:43,666 Sleeping for 8s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-15 21:52:53,084 Sleeping for 5s. Reason: PENDING
2026-08-15 21:53:40,676 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86.7 pTM=0.803 ipTM=0.202
2026-08-15 21:54:20,187 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.6 pTM=0.812 ipTM=0.231 tol=0.965
2026-08-15 21:54:27,215 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.2 pTM=0.806 ipTM=0.208 tol=1.09
2026-08-15 21:54:34,387 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=87.4 pTM=0.81 ipTM=0.237 tol=1.95
2026-08-15 21:54:34,387 alphafold2_multimer_v3_model_1_seed_000 took 95.1s (3 recycles)
2026-08-15 21:54:34,396 reranking models by 'multimer' metric
2026-08-15 21:54:34,396 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.4 pTM=0.81 ipTM=0.237 ipSAE=0.0127 pDockQ2=0.0495
2026-08-15 21:54:34,727 Query 10/20: rfd3_input_anexina_binder_design_0_model_0_top19_score1.004 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:54:35,071 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 21:54:46,057 Sleeping for 7s. Reason: PENDING
2026-08-15 21:55:00,479 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.1 pTM=0.769 ipTM=0.139
2026-08-15 21:55:06,845 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.3 pTM=0.768 ipTM=0.122 tol=0.699
2026-08-15 21:55:13,321 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.4 pTM=0.77 ipTM=0.113 tol=1.15
2026-08-15 21:55:19,893 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85.1 pTM=0.78 ipTM=0.15 tol=0.663
2026-08-15 21:55:19,893 alphafold2_multimer_v3_model_1_seed_000 took 25.8s (3 recycles)
2026-08-15 21:55:19,901 reranking models by 'multimer' metric
2026-08-15 21:55:19,901 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.1 pTM=0.78 ipTM=0.15 ipSAE=0.00577 pDockQ2=0.015
2026-08-15 21:55:20,219 Query 11/20: rfd3_input_anexina_binder_design_0_model_0_top1_score0.913 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:17 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:55:20,555 Sleeping for 6s. Reason: PENDING
2026-08-15 21:55:26,878 Sleeping for 10s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:17 remaining: 00:00]

2026-08-15 21:55:37,876 Sleeping for 10s. Reason: PENDING
2026-08-15 21:55:48,202 Sleeping for 6s. Reason: PENDING
2026-08-15 21:56:01,606 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.8 pTM=0.771 ipTM=0.107
2026-08-15 21:56:08,067 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.4 pTM=0.769 ipTM=0.12 tol=0.528
2026-08-15 21:56:14,630 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.4 pTM=0.77 ipTM=0.113 tol=0.358
2026-08-15 21:56:14,631 alphafold2_multimer_v3_model_1_seed_000 took 19.5s (2 recycles)
2026-08-15 21:56:14,640 reranking models by 'multimer' metric
2026-08-15 21:56:14,640 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.4 pTM=0.77 ipTM=0.113 ipSAE=0.0046 pDockQ2=0.0132
2026-08-15 21:56:14,978 Query 12/20: rfd3_input_anexina_binder_design_0_model_0_top20_score1.010 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:56:15,285 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:45 remaining: 00:00]

2026-08-15 21:56:26,177 Sleeping for 8s. Reason: PENDING
2026-08-15 21:56:34,486 Sleeping for 5s. Reason: PENDING
2026-08-15 21:56:39,786 Sleeping for 6s. Reason: PENDING
2026-08-15 21:56:46,084 Sleeping for 9s. Reason: PENDING
2026-08-15 21:56:55,378 Sleeping for 9s. Reason: PENDING
2026-08-15 21:57:04,682 Sleeping for 6s. Reason: PENDING
2026-08-15 21:57:18,223 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79.4 pTM=0.732 ipTM=0.0865
2026-08-15 21:57:24,719 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.5 pTM=0.738 ipTM=0.0987 tol=0.691
2026-08-15 21:57:31,306 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.6 pTM=0.748 ipTM=0.1 tol=0.344
2026-08-15 21:57:31,307 alphafold2_multimer_v3_model_1_seed_000 took 19.6s (2 recycles)
2026-08-15 21:57:31,315 reranking models by 'multimer' metric
2026-08-15 21:57:31,315 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=81.6 pTM=0.748 ipTM=0.1 ipSAE=0.0045 pDockQ2=0.0141
2026-08-15 21:57:31,890 Query 13/20: rfd3_input_anexina_binder_design_0_model_0_top2_score0.954 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:16 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:57:32,183 Sleeping for 6s. Reason: PENDING
2026-08-15 21:57:38,498 Sleeping for 9s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 01:00 remaining: 00:00]

2026-08-15 21:57:48,423 Sleeping for 8s. Reason: PENDING
2026-08-15 21:57:56,733 Sleeping for 7s. Reason: PENDING
2026-08-15 21:58:04,054 Sleeping for 9s. Reason: PENDING
2026-08-15 21:58:13,369 Sleeping for 8s. Reason: PENDING
2026-08-15 21:58:21,706 Sleeping for 10s. Reason: PENDING
2026-08-15 21:58:32,046 Sleeping for 10s. Reason: PENDING
2026-08-15 21:58:42,368 Sleeping for 6s. Reason: PENDING
2026-08-15 21:58:55,778 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.4 pTM=0.787 ipTM=0.212
2026-08-15 21:59:02,067 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=86.1 pTM=0.781 ipTM=0.175 tol=1.27
2026-08-15 21:59:08,382 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.9 pTM=0.779 ipTM=0.17 tol=0.675
2026-08-15 21:59:14,745 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=86.2 pTM=0.783 ipTM=0.179 tol=1.25
2026-08-15 21:59:14,745 alphafold2_multimer_v3_model_1_seed_000 took 25.4s (3 recycles)
2026-08-15 21:59:14,754 reranking models by 'multimer' metric
2026-08-15 21:59:14,754 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=86.2 pTM=0.783 ipTM=0.179 ipSAE=0.00667 pDockQ2=0.0186
2026-08-15 21:59:15,093 Query 14/20: rfd3_input_anexina_binder_design_0_model_0_top3_score0.961 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:59:15,451 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 21:59:21,429 Sleeping for 6s. Reason: PENDING
2026-08-15 21:59:34,915 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.1 pTM=0.773 ipTM=0.133
2026-08-15 21:59:41,320 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.8 pTM=0.78 ipTM=0.163 tol=0.878
2026-08-15 21:59:47,819 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.6 pTM=0.778 ipTM=0.151 tol=0.334
2026-08-15 21:59:47,819 alphafold2_multimer_v3_model_1_seed_000 took 19.4s (2 recycles)
2026-08-15 21:59:47,828 reranking models by 'multimer' metric
2026-08-15 21:59:47,828 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.6 pTM=0.778 ipTM=0.151 ipSAE=0.00595 pDockQ2=0.0179
2026-08-15 21:59:48,166 Query 15/20: rfd3_input_anexina_binder_design_0_model_0_top4_score0.957 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 21:59:48,499 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 21:59:56,513 Sleeping for 10s. Reason: PENDING
2026-08-15 22:00:13,940 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.8 pTM=0.72 ipTM=0.108
2026-08-15 22:00:20,345 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79.6 pTM=0.716 ipTM=0.109 tol=0.867
2026-08-15 22:00:26,849 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.9 pTM=0.732 ipTM=0.117 tol=0.259
2026-08-15 22:00:26,849 alphafold2_multimer_v3_model_1_seed_000 took 19.3s (2 recycles)
2026-08-15 22:00:26,857 reranking models by 'multimer' metric
2026-08-15 22:00:26,857 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.9 pTM=0.732 ipTM=0.117 ipSAE=0.00481 pDockQ2=0.0143
2026-08-15 22:00:27,201 Query 16/20: rfd3_input_anexina_binder_design_0_model_0_top5_score0.962 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:00:27,535 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:00:38,476 Sleeping for 10s. Reason: PENDING
2026-08-15 22:00:55,839 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=87.4 pTM=0.796 ipTM=0.369
2026-08-15 22:01:02,259 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.9 pTM=0.8 ipTM=0.357 tol=0.364
2026-08-15 22:01:02,260 alphafold2_multimer_v3_model_1_seed_000 took 12.8s (1 recycles)
2026-08-15 22:01:02,268 reranking models by 'multimer' metric
2026-08-15 22:01:02,268 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.9 pTM=0.8 ipTM=0.357 ipSAE=0.0202 pDockQ2=0.0846
2026-08-15 22:01:02,586 Query 17/20: rfd3_input_anexina_binder_design_0_model_0_top6_score0.970 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:01:02,885 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:01:12,752 Sleeping for 8s. Reason: PENDING
2026-08-15 22:01:28,322 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.4 pTM=0.771 ipTM=0.185
2026-08-15 22:01:34,772 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.9 pTM=0.78 ipTM=0.152 tol=0.737
2026-08-15 22:01:41,281 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.4 pTM=0.774 ipTM=0.141 tol=0.515
2026-08-15 22:01:47,792 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85.7 pTM=0.777 ipTM=0.151 tol=0.187
2026-08-15 22:01:47,792 alphafold2_multimer_v3_model_1_seed_000 took 26.0s (3 recycles)
2026-08-15 22:01:47,800 reranking models by 'multimer' metric
2026-08-15 22:01:47,800 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.7 pTM=0.777 ipTM=0.151 ipSAE=0.00603 pDockQ2=0.0169
2026-08-15 22:01:48,133 Query 18/20: rfd3_input_anexina_binder_design_0_model_0_top7_score0.965 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:01:48,444 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 22:01:55,332 Sleeping for 5s. Reason: PENDING
2026-08-15 22:02:07,630 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.9 pTM=0.779 ipTM=0.149
2026-08-15 22:02:13,970 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=86.4 pTM=0.779 ipTM=0.0827 tol=2.16
2026-08-15 22:02:20,417 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.8 pTM=0.776 ipTM=0.0927 tol=0.838
2026-08-15 22:02:26,930 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85.9 pTM=0.778 ipTM=0.105 tol=0.41
2026-08-15 22:02:26,931 alphafold2_multimer_v3_model_1_seed_000 took 25.7s (3 recycles)
2026-08-15 22:02:26,938 reranking models by 'multimer' metric
2026-08-15 22:02:26,938 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.9 pTM=0.778 ipTM=0.105 ipSAE=0 pDockQ2=0.0132
2026-08-15 22:02:27,268 Query 19/20: rfd3_input_anexina_binder_design_0_model_0_top8_score0.972 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:02:27,600 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 22:02:34,521 Sleeping for 8s. Reason: PENDING
2026-08-15 22:02:49,844 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=87.2 pTM=0.785 ipTM=0.109
2026-08-15 22:02:56,268 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=86.7 pTM=0.778 ipTM=0.0884 tol=1.8
2026-08-15 22:03:02,773 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=86.3 pTM=0.774 ipTM=0.0905 tol=1.11
2026-08-15 22:03:09,363 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=86.4 pTM=0.77 ipTM=0.0954 tol=0.461
2026-08-15 22:03:09,363 alphafold2_multimer_v3_model_1_seed_000 took 25.9s (3 recycles)
2026-08-15 22:03:09,372 reranking models by 'multimer' metric
2026-08-15 22:03:09,372 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=86.4 pTM=0.77 ipTM=0.0954 ipSAE=0 pDockQ2=0.0124
2026-08-15 22:03:09,704 Query 20/20: rfd3_input_anexina_binder_design_0_model_0_top9_score0.977 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:03:10,029 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 22:03:18,027 Sleeping for 5s. Reason: PENDING
2026-08-15 22:03:30,487 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85 pTM=0.775 ipTM=0.122
2026-08-15 22:03:36,908 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.7 pTM=0.771 ipTM=0.123 tol=0.813
2026-08-15 22:03:43,418 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.9 pTM=0.774 ipTM=0.103 tol=0.432
2026-08-15 22:03:43,419 alphafold2_multimer_v3_model_1_seed_000 took 19.4s (2 recycles)
2026-08-15 22:03:43,427 reranking models by 'multimer' metric
2026-08-15 22:03:43,427 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.9 pTM=0.774 ipTM=0.103 ipSAE=0 pDockQ2=0.0118
2026-08-15 22:03:43,748 Done
Validando sequências do design: rfd3_input_anexina_binder_design_0_model_16

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-15 22:03:46,571 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-15 22:03:47,365 Running on GPU
2026-08-15 22:03:47,629 Found 5 citations for tools or databases
2026-08-15 22:03:47,886 Query 1/20: rfd3_input_anexina_binder_design_0_model_16_top10_score0.802 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:03:49,023 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-15 22:03:57,016 Sleeping for 6s. Reason: PENDING
2026-08-15 22:04:49,979 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=58.1 pTM=0.43 ipTM=0.0594
2026-08-15 22:05:26,166 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=61.8 pTM=0.444 ipTM=0.0579 tol=1.79
2026-08-15 22:05:32,174 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=63.6 pTM=0.45 ipTM=0.0598 tol=0.522
2026-08-15 22:05:38,242 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=62.4 pTM=0.451 ipTM=0.0676 tol=0.974
2026-08-15 22:05:38,243 alphafold2_multimer_v3_model_1_seed_000 took 86.9s (3 recycles)
2026-08-15 22:05:38,250 reranking models by 'multimer' metric
2026-08-15 22:05:38,250 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=62.4 pTM=0.451 ipTM=0.0676 ipSAE=0 pDockQ2=0.0099
2026-08-15 22:05:38,562 Query 2/20: rfd3_input_anexina_binder_design_0_model_16_top11_score0.800 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:05:38,908 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:05:49,902 Sleeping for 9s. Reason: PENDING
2026-08-15 22:06:06,066 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=73.4 pTM=0.559 ipTM=0.0549
2026-08-15 22:06:12,167 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=69.4 pTM=0.52 ipTM=0.0506 tol=1.42
2026-08-15 22:06:18,313 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=68.4 pTM=0.524 ipTM=0.0645 tol=1.9
2026-08-15 22:06:24,530 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=67.4 pTM=0.517 ipTM=0.0767 tol=0.592
2026-08-15 22:06:24,530 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 22:06:24,538 reranking models by 'multimer' metric
2026-08-15 22:06:24,538 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=67.4 pTM=0.517 ipTM=0.0767 ipSAE=0 pDockQ2=0.0101
2026-08-15 22:06:24,857 Query 3/20: rfd3_input_anexina_binder_design_0_model_16_top12_score0.801 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:06:25,212 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 22:06:36,219 Sleeping for 6s. Reason: PENDING
2026-08-15 22:06:49,353 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=87.9 pTM=0.736 ipTM=0.0754
2026-08-15 22:06:55,488 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.1 pTM=0.74 ipTM=0.0823 tol=1.66
2026-08-15 22:07:01,676 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=86.6 pTM=0.737 ipTM=0.0897 tol=0.816
2026-08-15 22:07:07,923 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=86.9 pTM=0.738 ipTM=0.0942 tol=0.564
2026-08-15 22:07:07,924 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-15 22:07:07,932 reranking models by 'multimer' metric
2026-08-15 22:07:07,932 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=86.9 pTM=0.738 ipTM=0.0942 ipSAE=0 pDockQ2=0.0127
2026-08-15 22:07:08,258 Query 4/20: rfd3_input_anexina_binder_design_0_model_16_top13_score0.798 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:07:08,623 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 22:07:14,643 Sleeping for 6s. Reason: PENDING
2026-08-15 22:07:27,759 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=64.4 pTM=0.476 ipTM=0.071
2026-08-15 22:07:33,865 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.8 pTM=0.68 ipTM=0.0746 tol=3.99
2026-08-15 22:07:40,035 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.8 pTM=0.674 ipTM=0.0865 tol=0.67
2026-08-15 22:07:46,298 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=80.4 pTM=0.669 ipTM=0.0902 tol=0.585
2026-08-15 22:07:46,299 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-15 22:07:46,307 reranking models by 'multimer' metric
2026-08-15 22:07:46,307 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.4 pTM=0.669 ipTM=0.0902 ipSAE=0 pDockQ2=0.0107
2026-08-15 22:07:46,633 Query 5/20: rfd3_input_anexina_binder_design_0_model_16_top14_score0.801 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:07:46,970 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:07:52,930 Sleeping for 9s. Reason: PENDING
2026-08-15 22:08:09,079 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=56.6 pTM=0.404 ipTM=0.0316
2026-08-15 22:08:15,209 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=69.9 pTM=0.554 ipTM=0.0514 tol=4.16
2026-08-15 22:08:21,417 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=70 pTM=0.549 ipTM=0.0496 tol=2.36
2026-08-15 22:08:27,716 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=64.9 pTM=0.494 ipTM=0.0522 tol=2.12
2026-08-15 22:08:27,717 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 22:08:27,725 reranking models by 'multimer' metric
2026-08-15 22:08:27,725 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=64.9 pTM=0.494 ipTM=0.0522 ipSAE=0 pDockQ2=0.0088
2026-08-15 22:08:28,034 Query 6/20: rfd3_input_anexina_binder_design_0_model_16_top15_score0.805 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:08:28,377 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 22:08:37,396 Sleeping for 5s. Reason: PENDING
2026-08-15 22:08:49,520 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.4 pTM=0.68 ipTM=0.0383
2026-08-15 22:08:55,659 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=82.9 pTM=0.688 ipTM=0.0934 tol=2.61
2026-08-15 22:09:01,858 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=82.6 pTM=0.679 ipTM=0.0988 tol=1.04
2026-08-15 22:09:08,151 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=83.4 pTM=0.69 ipTM=0.0978 tol=0.399
2026-08-15 22:09:08,152 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 22:09:08,160 reranking models by 'multimer' metric
2026-08-15 22:09:08,160 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.4 pTM=0.69 ipTM=0.0978 ipSAE=0 pDockQ2=0.0115
2026-08-15 22:09:08,476 Query 7/20: rfd3_input_anexina_binder_design_0_model_16_top16_score0.807 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:09:08,826 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 22:09:19,878 Sleeping for 5s. Reason: PENDING
2026-08-15 22:09:32,017 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=87.1 pTM=0.712 ipTM=0.0442
2026-08-15 22:09:38,134 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.6 pTM=0.72 ipTM=0.0784 tol=5.27
2026-08-15 22:09:44,337 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.4 pTM=0.724 ipTM=0.0964 tol=2.95
2026-08-15 22:09:50,637 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=86.1 pTM=0.729 ipTM=0.0931 tol=1.06
2026-08-15 22:09:50,637 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 22:09:50,645 reranking models by 'multimer' metric
2026-08-15 22:09:50,645 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=86.1 pTM=0.729 ipTM=0.0931 ipSAE=0 pDockQ2=0.0129
2026-08-15 22:09:50,969 Query 8/20: rfd3_input_anexina_binder_design_0_model_16_top17_score0.804 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:09:51,296 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 22:09:58,302 Sleeping for 5s. Reason: PENDING
2026-08-15 22:10:10,500 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82.7 pTM=0.68 ipTM=0.0408
2026-08-15 22:10:16,657 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=82.1 pTM=0.678 ipTM=0.0398 tol=0.808
2026-08-15 22:10:22,872 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.3 pTM=0.663 ipTM=0.0465 tol=1.2
2026-08-15 22:10:29,137 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.1 pTM=0.647 ipTM=0.0479 tol=0.802
2026-08-15 22:10:29,138 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 22:10:29,145 reranking models by 'multimer' metric
2026-08-15 22:10:29,145 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.1 pTM=0.647 ipTM=0.0479 ipSAE=0 pDockQ2=0.0095
2026-08-15 22:10:29,486 Query 9/20: rfd3_input_anexina_binder_design_0_model_16_top18_score0.810 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:10:29,811 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 22:10:37,823 Sleeping for 7s. Reason: PENDING
2026-08-15 22:10:51,896 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.4 pTM=0.651 ipTM=0.039
2026-08-15 22:10:57,969 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.1 pTM=0.691 ipTM=0.0424 tol=1.67
2026-08-15 22:11:04,128 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.3 pTM=0.688 ipTM=0.0469 tol=0.801
2026-08-15 22:11:10,379 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84.2 pTM=0.702 ipTM=0.0499 tol=0.954
2026-08-15 22:11:10,379 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 22:11:10,387 reranking models by 'multimer' metric
2026-08-15 22:11:10,387 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.2 pTM=0.702 ipTM=0.0499 ipSAE=0 pDockQ2=0.0107
2026-08-15 22:11:10,706 Query 10/20: rfd3_input_anexina_binder_design_0_model_16_top19_score0.814 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:11:11,050 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 22:11:18,029 Sleeping for 7s. Reason: PENDING
2026-08-15 22:11:32,251 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82.8 pTM=0.666 ipTM=0.0356
2026-08-15 22:11:38,437 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.4 pTM=0.678 ipTM=0.0482 tol=3.82
2026-08-15 22:11:44,684 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=82.2 pTM=0.689 ipTM=0.0584 tol=1.6
2026-08-15 22:11:50,973 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=82.4 pTM=0.687 ipTM=0.0655 tol=0.87
2026-08-15 22:11:50,973 alphafold2_multimer_v3_model_1_seed_000 took 25.0s (3 recycles)
2026-08-15 22:11:50,980 reranking models by 'multimer' metric
2026-08-15 22:11:50,980 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.4 pTM=0.687 ipTM=0.0655 ipSAE=0 pDockQ2=0.0107
2026-08-15 22:11:51,334 Query 11/20: rfd3_input_anexina_binder_design_0_model_16_top1_score0.758 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:11:51,684 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:11:59,669 Sleeping for 10s. Reason: PENDING
2026-08-15 22:12:16,743 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=62.2 pTM=0.431 ipTM=0.0331
2026-08-15 22:12:22,819 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=63 pTM=0.469 ipTM=0.0506 tol=3.09
2026-08-15 22:12:28,977 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=63.3 pTM=0.461 ipTM=0.0576 tol=1.13
2026-08-15 22:12:35,229 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=64.5 pTM=0.478 ipTM=0.0657 tol=0.943
2026-08-15 22:12:35,229 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 22:12:35,237 reranking models by 'multimer' metric
2026-08-15 22:12:35,237 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=64.5 pTM=0.478 ipTM=0.0657 ipSAE=0 pDockQ2=0.0094
2026-08-15 22:12:35,545 Query 12/20: rfd3_input_anexina_binder_design_0_model_16_top20_score0.820 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:12:35,865 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:12:44,885 Sleeping for 9s. Reason: PENDING
2026-08-15 22:13:01,307 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=66.1 pTM=0.525 ipTM=0.0417
2026-08-15 22:13:07,484 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=69.2 pTM=0.515 ipTM=0.0596 tol=3.03
2026-08-15 22:13:13,742 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=72.7 pTM=0.559 ipTM=0.0872 tol=1.59
2026-08-15 22:13:20,058 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=73.2 pTM=0.566 ipTM=0.0704 tol=1.29
2026-08-15 22:13:20,058 alphafold2_multimer_v3_model_1_seed_000 took 25.0s (3 recycles)
2026-08-15 22:13:20,066 reranking models by 'multimer' metric
2026-08-15 22:13:20,066 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=73.2 pTM=0.566 ipTM=0.0704 ipSAE=0 pDockQ2=0.0095
2026-08-15 22:13:20,380 Query 13/20: rfd3_input_anexina_binder_design_0_model_16_top2_score0.779 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:13:20,732 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:13:27,741 Sleeping for 10s. Reason: PENDING
2026-08-15 22:13:44,816 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.4 pTM=0.669 ipTM=0.028
2026-08-15 22:13:50,914 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.2 pTM=0.689 ipTM=0.0327 tol=3.22
2026-08-15 22:13:57,086 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=82.6 pTM=0.687 ipTM=0.0449 tol=6.1
2026-08-15 22:14:03,374 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=83.8 pTM=0.7 ipTM=0.0649 tol=1.76
2026-08-15 22:14:03,375 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-15 22:14:03,382 reranking models by 'multimer' metric
2026-08-15 22:14:03,382 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.8 pTM=0.7 ipTM=0.0649 ipSAE=0 pDockQ2=0.0096
2026-08-15 22:14:03,702 Query 14/20: rfd3_input_anexina_binder_design_0_model_16_top3_score0.785 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:14:04,049 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:14:15,015 Sleeping for 9s. Reason: PENDING
2026-08-15 22:14:31,135 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=68.1 pTM=0.465 ipTM=0.0288
2026-08-15 22:14:37,299 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=67.5 pTM=0.501 ipTM=0.0297 tol=3.85
2026-08-15 22:14:43,541 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=63.7 pTM=0.471 ipTM=0.0531 tol=6.42
2026-08-15 22:14:49,862 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=66.1 pTM=0.491 ipTM=0.0591 tol=1.36
2026-08-15 22:14:49,862 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 22:14:49,870 reranking models by 'multimer' metric
2026-08-15 22:14:49,870 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=66.1 pTM=0.491 ipTM=0.0591 ipSAE=0 pDockQ2=0.0091
2026-08-15 22:14:50,184 Query 15/20: rfd3_input_anexina_binder_design_0_model_16_top4_score0.782 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:14:50,510 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:54 remaining: 00:00]

2026-08-15 22:15:01,541 Sleeping for 7s. Reason: PENDING
2026-08-15 22:15:08,880 Sleeping for 5s. Reason: PENDING
2026-08-15 22:15:14,210 Sleeping for 5s. Reason: PENDING
2026-08-15 22:15:19,538 Sleeping for 5s. Reason: PENDING
2026-08-15 22:15:24,855 Sleeping for 5s. Reason: PENDING
2026-08-15 22:15:30,187 Sleeping for 10s. Reason: PENDING
2026-08-15 22:15:40,520 Sleeping for 9s. Reason: PENDING
2026-08-15 22:15:49,838 Sleeping for 5s. Reason: RUNNING
2026-08-15 22:16:02,007 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=66.4 pTM=0.462 ipTM=0.0242
2026-08-15 22:16:08,198 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=75.4 pTM=0.607 ipTM=0.0609 tol=8.73
2026-08-15 22:16:14,449 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.6 pTM=0.66 ipTM=0.043 tol=3.33
2026-08-15 22:16:20,760 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=78.1 pTM=0.646 ipTM=0.0507 tol=2.06
2026-08-15 22:16:20,761 alphafold2_multimer_v3_model_1_seed_000 took 25.0s (3 recycles)
2026-08-15 22:16:20,768 reranking models by 'multimer' metric
2026-08-15 22:16:20,769 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=78.1 pTM=0.646 ipTM=0.0507 ipSAE=0 pDockQ2=0.0091
2026-08-15 22:16:21,081 Query 16/20: rfd3_input_anexina_binder_design_0_model_16_top5_score0.784 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:16:21,447 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:16:31,430 Sleeping for 10s. Reason: PENDING
2026-08-15 22:16:48,546 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=69.7 pTM=0.521 ipTM=0.0314
2026-08-15 22:16:54,654 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=68.4 pTM=0.536 ipTM=0.0443 tol=5.55
2026-08-15 22:17:00,827 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=66 pTM=0.481 ipTM=0.0399 tol=1.49
2026-08-15 22:17:07,078 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=63.6 pTM=0.463 ipTM=0.0408 tol=1.16
2026-08-15 22:17:07,078 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-15 22:17:07,085 reranking models by 'multimer' metric
2026-08-15 22:17:07,085 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=63.6 pTM=0.463 ipTM=0.0408 ipSAE=0 pDockQ2=0
2026-08-15 22:17:07,398 Query 17/20: rfd3_input_anexina_binder_design_0_model_16_top6_score0.790 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:17:07,721 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:17:15,704 Sleeping for 7s. Reason: PENDING
2026-08-15 22:17:29,849 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.6 pTM=0.67 ipTM=0.0466
2026-08-15 22:17:35,994 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=82.8 pTM=0.7 ipTM=0.106 tol=6.14
2026-08-15 22:17:42,214 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.1 pTM=0.708 ipTM=0.079 tol=0.738
2026-08-15 22:17:48,513 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=83.5 pTM=0.706 ipTM=0.0844 tol=0.212
2026-08-15 22:17:48,514 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 22:17:48,521 reranking models by 'multimer' metric
2026-08-15 22:17:48,521 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.5 pTM=0.706 ipTM=0.0844 ipSAE=0 pDockQ2=0.012
2026-08-15 22:17:48,836 Query 18/20: rfd3_input_anexina_binder_design_0_model_16_top7_score0.794 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:17:49,190 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 22:17:57,152 Sleeping for 7s. Reason: PENDING
2026-08-15 22:18:11,255 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=67.9 pTM=0.494 ipTM=0.0426
2026-08-15 22:18:17,392 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=67.4 pTM=0.501 ipTM=0.0463 tol=1.62
2026-08-15 22:18:23,594 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.2 pTM=0.667 ipTM=0.0457 tol=6.13
2026-08-15 22:18:29,881 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=80.9 pTM=0.669 ipTM=0.0509 tol=1.01
2026-08-15 22:18:29,881 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 22:18:29,889 reranking models by 'multimer' metric
2026-08-15 22:18:29,889 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.9 pTM=0.669 ipTM=0.0509 ipSAE=0 pDockQ2=0.0094
2026-08-15 22:18:30,210 Query 19/20: rfd3_input_anexina_binder_design_0_model_16_top8_score0.797 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:18:30,541 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:18:40,536 Sleeping for 9s. Reason: PENDING
2026-08-15 22:18:56,649 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.7 pTM=0.584 ipTM=0.0332
2026-08-15 22:19:02,785 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79.1 pTM=0.628 ipTM=0.0401 tol=3.22
2026-08-15 22:19:08,989 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.8 pTM=0.663 ipTM=0.0443 tol=1.56
2026-08-15 22:19:15,294 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.9 pTM=0.659 ipTM=0.043 tol=1.24
2026-08-15 22:19:15,294 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 22:19:15,302 reranking models by 'multimer' metric
2026-08-15 22:19:15,302 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.9 pTM=0.659 ipTM=0.043 ipSAE=0 pDockQ2=0.009
2026-08-15 22:19:15,611 Query 20/20: rfd3_input_anexina_binder_design_0_model_16_top9_score0.800 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:19:15,946 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 22:19:26,931 Sleeping for 7s. Reason: PENDING
2026-08-15 22:19:41,089 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82.4 pTM=0.683 ipTM=0.0669
2026-08-15 22:19:47,233 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.7 pTM=0.686 ipTM=0.0724 tol=1.43
2026-08-15 22:19:53,457 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=82.2 pTM=0.684 ipTM=0.0916 tol=0.717
2026-08-15 22:19:59,767 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=82 pTM=0.682 ipTM=0.0887 tol=0.271
2026-08-15 22:19:59,768 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 22:19:59,775 reranking models by 'multimer' metric
2026-08-15 22:19:59,775 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82 pTM=0.682 ipTM=0.0887 ipSAE=0 pDockQ2=0.0119
2026-08-15 22:20:00,122 Done
Validando sequências do design: rfd3_input_anexina_binder_design_0_model_11

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-15 22:20:02,755 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-15 22:20:03,549 Running on GPU
2026-08-15 22:20:03,814 Found 5 citations for tools or databases
2026-08-15 22:20:04,068 Query 1/20: rfd3_input_anexina_binder_design_0_model_11_top10_score0.934 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:13 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:20:04,805 Sleeping for 6s. Reason: PENDING
2026-08-15 22:20:11,138 Sleeping for 6s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-15 22:20:18,132 Sleeping for 9s. Reason: PENDING
2026-08-15 22:21:13,176 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.1 pTM=0.771 ipTM=0.167
2026-08-15 22:21:48,991 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.7 pTM=0.774 ipTM=0.145 tol=0.951
2026-08-15 22:21:54,954 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.6 pTM=0.776 ipTM=0.151 tol=1.31
2026-08-15 22:22:00,954 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85.5 pTM=0.775 ipTM=0.141 tol=0.484
2026-08-15 22:22:00,954 alphafold2_multimer_v3_model_1_seed_000 took 85.6s (3 recycles)
2026-08-15 22:22:00,963 reranking models by 'multimer' metric
2026-08-15 22:22:00,963 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.5 pTM=0.775 ipTM=0.141 ipSAE=0.00564 pDockQ2=0.0196
2026-08-15 22:22:01,289 Query 2/20: rfd3_input_anexina_binder_design_0_model_11_top11_score0.938 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:22:01,642 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:22:08,650 Sleeping for 9s. Reason: PENDING
2026-08-15 22:22:24,738 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.2 pTM=0.696 ipTM=0.159
2026-08-15 22:22:30,780 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=75.4 pTM=0.683 ipTM=0.15 tol=1.38
2026-08-15 22:22:36,886 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=72.8 pTM=0.645 ipTM=0.157 tol=0.371
2026-08-15 22:22:36,886 alphafold2_multimer_v3_model_1_seed_000 took 18.3s (2 recycles)
2026-08-15 22:22:36,894 reranking models by 'multimer' metric
2026-08-15 22:22:36,894 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=72.8 pTM=0.645 ipTM=0.157 ipSAE=0.00683 pDockQ2=0.0192
2026-08-15 22:22:37,217 Query 3/20: rfd3_input_anexina_binder_design_0_model_11_top12_score0.935 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:22:37,564 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 22:22:48,550 Sleeping for 8s. Reason: PENDING
2026-08-15 22:23:03,640 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82.5 pTM=0.758 ipTM=0.139
2026-08-15 22:23:09,665 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79.7 pTM=0.722 ipTM=0.123 tol=0.825
2026-08-15 22:23:15,742 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.7 pTM=0.728 ipTM=0.133 tol=0.669
2026-08-15 22:23:21,842 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.9 pTM=0.733 ipTM=0.135 tol=0.416
2026-08-15 22:23:21,842 alphafold2_multimer_v3_model_1_seed_000 took 24.3s (3 recycles)
2026-08-15 22:23:21,850 reranking models by 'multimer' metric
2026-08-15 22:23:21,850 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.9 pTM=0.733 ipTM=0.135 ipSAE=0.00564 pDockQ2=0.0164
2026-08-15 22:23:22,171 Query 4/20: rfd3_input_anexina_binder_design_0_model_11_top13_score0.949 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:23:22,509 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 22:23:32,551 Sleeping for 6s. Reason: PENDING
2026-08-15 22:23:45,684 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=80.1 pTM=0.725 ipTM=0.0874
2026-08-15 22:23:51,760 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.9 pTM=0.716 ipTM=0.11 tol=0.732
2026-08-15 22:23:57,918 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.4 pTM=0.717 ipTM=0.13 tol=0.438
2026-08-15 22:23:57,919 alphafold2_multimer_v3_model_1_seed_000 took 18.4s (2 recycles)
2026-08-15 22:23:57,927 reranking models by 'multimer' metric
2026-08-15 22:23:57,927 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.4 pTM=0.717 ipTM=0.13 ipSAE=0.00542 pDockQ2=0.016
2026-08-15 22:23:58,240 Query 5/20: rfd3_input_anexina_binder_design_0_model_11_top14_score0.947 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:19 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:23:58,587 Sleeping for 9s. Reason: PENDING
2026-08-15 22:24:07,916 Sleeping for 9s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 22:24:17,878 Sleeping for 7s. Reason: PENDING
2026-08-15 22:24:31,961 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=80.9 pTM=0.73 ipTM=0.12
2026-08-15 22:24:38,052 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.9 pTM=0.75 ipTM=0.217 tol=1.04
2026-08-15 22:24:44,217 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.6 pTM=0.75 ipTM=0.205 tol=0.29
2026-08-15 22:24:44,217 alphafold2_multimer_v3_model_1_seed_000 took 18.4s (2 recycles)
2026-08-15 22:24:44,225 reranking models by 'multimer' metric
2026-08-15 22:24:44,225 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.6 pTM=0.75 ipTM=0.205 ipSAE=0.00855 pDockQ2=0.0296
2026-08-15 22:24:44,541 Query 6/20: rfd3_input_anexina_binder_design_0_model_11_top15_score0.947 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:24:44,883 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 22:24:54,885 Sleeping for 7s. Reason: PENDING
2026-08-15 22:25:08,966 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.6 pTM=0.775 ipTM=0.196
2026-08-15 22:25:15,066 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=88.8 pTM=0.827 ipTM=0.485 tol=2.18
2026-08-15 22:25:21,225 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=86.9 pTM=0.803 ipTM=0.228 tol=0.588
2026-08-15 22:25:27,411 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=86.8 pTM=0.797 ipTM=0.191 tol=0.676
2026-08-15 22:25:27,412 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 22:25:27,420 reranking models by 'multimer' metric
2026-08-15 22:25:27,420 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=86.8 pTM=0.797 ipTM=0.191 ipSAE=0.00804 pDockQ2=0.0279
2026-08-15 22:25:27,734 Query 7/20: rfd3_input_anexina_binder_design_0_model_11_top16_score0.967 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:25:28,080 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:25:36,078 Sleeping for 9s. Reason: PENDING
2026-08-15 22:25:52,113 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.5 pTM=0.711 ipTM=0.119
2026-08-15 22:25:58,142 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79.4 pTM=0.743 ipTM=0.188 tol=2.38
2026-08-15 22:26:04,258 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=77.8 pTM=0.734 ipTM=0.113 tol=0.877
2026-08-15 22:26:10,461 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=77.5 pTM=0.735 ipTM=0.133 tol=3.67
2026-08-15 22:26:10,461 alphafold2_multimer_v3_model_1_seed_000 took 24.4s (3 recycles)
2026-08-15 22:26:10,469 reranking models by 'multimer' metric
2026-08-15 22:26:10,469 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=77.5 pTM=0.735 ipTM=0.133 ipSAE=0.00577 pDockQ2=0.0175
2026-08-15 22:26:10,786 Query 8/20: rfd3_input_anexina_binder_design_0_model_11_top17_score0.965 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:26:11,120 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:26:17,103 Sleeping for 9s. Reason: PENDING
2026-08-15 22:26:33,204 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82.6 pTM=0.754 ipTM=0.193
2026-08-15 22:26:39,300 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79.3 pTM=0.719 ipTM=0.168 tol=0.984
2026-08-15 22:26:45,478 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=78.4 pTM=0.704 ipTM=0.158 tol=0.639
2026-08-15 22:26:51,694 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=81.6 pTM=0.726 ipTM=0.153 tol=0.882
2026-08-15 22:26:51,694 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 22:26:51,702 reranking models by 'multimer' metric
2026-08-15 22:26:51,703 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=81.6 pTM=0.726 ipTM=0.153 ipSAE=0.00574 pDockQ2=0.0187
2026-08-15 22:26:52,025 Query 9/20: rfd3_input_anexina_binder_design_0_model_11_top18_score0.959 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:26:52,377 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:26:58,335 Sleeping for 9s. Reason: PENDING
2026-08-15 22:27:14,411 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.5 pTM=0.749 ipTM=0.103
2026-08-15 22:27:20,439 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.9 pTM=0.773 ipTM=0.143 tol=1.01
2026-08-15 22:27:26,575 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.9 pTM=0.789 ipTM=0.19 tol=0.512
2026-08-15 22:27:32,776 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=86.9 pTM=0.79 ipTM=0.223 tol=0.256
2026-08-15 22:27:32,777 alphafold2_multimer_v3_model_1_seed_000 took 24.5s (3 recycles)
2026-08-15 22:27:32,786 reranking models by 'multimer' metric
2026-08-15 22:27:32,786 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=86.9 pTM=0.79 ipTM=0.223 ipSAE=0.00929 pDockQ2=0.0387
2026-08-15 22:27:33,109 Query 10/20: rfd3_input_anexina_binder_design_0_model_11_top19_score0.957 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:27:33,442 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:27:42,419 Sleeping for 9s. Reason: PENDING
2026-08-15 22:27:58,532 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.3 pTM=0.762 ipTM=0.229
2026-08-15 22:28:04,622 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.6 pTM=0.767 ipTM=0.333 tol=1.56
2026-08-15 22:28:10,802 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.3 pTM=0.743 ipTM=0.258 tol=0.365
2026-08-15 22:28:10,802 alphafold2_multimer_v3_model_1_seed_000 took 18.4s (2 recycles)
2026-08-15 22:28:10,811 reranking models by 'multimer' metric
2026-08-15 22:28:10,811 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.3 pTM=0.743 ipTM=0.258 ipSAE=0.0201 pDockQ2=0.0431
2026-08-15 22:28:11,136 Query 11/20: rfd3_input_anexina_binder_design_0_model_11_top1_score0.902 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:28:11,471 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 22:28:17,441 Sleeping for 8s. Reason: PENDING
2026-08-15 22:28:32,607 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.1 pTM=0.769 ipTM=0.14
2026-08-15 22:28:38,717 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.8 pTM=0.77 ipTM=0.15 tol=0.843
2026-08-15 22:28:44,903 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.4 pTM=0.772 ipTM=0.147 tol=0.264
2026-08-15 22:28:44,903 alphafold2_multimer_v3_model_1_seed_000 took 18.5s (2 recycles)
2026-08-15 22:28:44,911 reranking models by 'multimer' metric
2026-08-15 22:28:44,911 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.4 pTM=0.772 ipTM=0.147 ipSAE=0.0057 pDockQ2=0.0182
2026-08-15 22:28:45,228 Query 12/20: rfd3_input_anexina_binder_design_0_model_11_top20_score0.962 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:28:45,572 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:28:55,581 Sleeping for 10s. Reason: PENDING
2026-08-15 22:29:12,914 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86 pTM=0.785 ipTM=0.226
2026-08-15 22:29:18,972 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=86.4 pTM=0.787 ipTM=0.199 tol=0.945
2026-08-15 22:29:25,125 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.9 pTM=0.782 ipTM=0.205 tol=0.522
2026-08-15 22:29:31,351 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=86.1 pTM=0.781 ipTM=0.183 tol=0.497
2026-08-15 22:29:31,352 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 22:29:31,360 reranking models by 'multimer' metric
2026-08-15 22:29:31,360 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=86.1 pTM=0.781 ipTM=0.183 ipSAE=0.00743 pDockQ2=0.0268
2026-08-15 22:29:31,685 Query 13/20: rfd3_input_anexina_binder_design_0_model_11_top2_score0.893 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:29:32,026 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]

2026-08-15 22:29:39,036 Sleeping for 10s. Reason: PENDING
2026-08-15 22:29:56,128 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=59.2 pTM=0.498 ipTM=0.098
2026-08-15 22:30:02,214 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.9 pTM=0.719 ipTM=0.163 tol=2.69
2026-08-15 22:30:08,378 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.1 pTM=0.718 ipTM=0.166 tol=0.678
2026-08-15 22:30:14,597 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=80.8 pTM=0.714 ipTM=0.163 tol=0.231
2026-08-15 22:30:14,597 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 22:30:14,605 reranking models by 'multimer' metric
2026-08-15 22:30:14,605 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.8 pTM=0.714 ipTM=0.163 ipSAE=0.00685 pDockQ2=0.0202
2026-08-15 22:30:14,926 Query 14/20: rfd3_input_anexina_binder_design_0_model_11_top3_score0.910 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:30:15,282 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 22:30:23,320 Sleeping for 5s. Reason: PENDING
2026-08-15 22:30:35,389 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=49.7 pTM=0.396 ipTM=0.069
2026-08-15 22:30:41,435 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=57.1 pTM=0.49 ipTM=0.0812 tol=3.08
2026-08-15 22:30:47,549 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=62.1 pTM=0.518 ipTM=0.0887 tol=1.45
2026-08-15 22:30:53,732 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=64.5 pTM=0.533 ipTM=0.0809 tol=0.895
2026-08-15 22:30:53,732 alphafold2_multimer_v3_model_1_seed_000 took 24.4s (3 recycles)
2026-08-15 22:30:53,739 reranking models by 'multimer' metric
2026-08-15 22:30:53,740 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=64.5 pTM=0.533 ipTM=0.0809 ipSAE=0 pDockQ2=0.0108
2026-08-15 22:30:54,054 Query 15/20: rfd3_input_anexina_binder_design_0_model_11_top4_score0.913 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:30:54,398 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 22:31:05,377 Sleeping for 5s. Reason: PENDING
2026-08-15 22:31:17,417 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.9 pTM=0.746 ipTM=0.137
2026-08-15 22:31:23,487 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.3 pTM=0.712 ipTM=0.134 tol=1
2026-08-15 22:31:29,641 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=78.6 pTM=0.714 ipTM=0.141 tol=0.833
2026-08-15 22:31:35,873 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=78.4 pTM=0.713 ipTM=0.148 tol=0.275
2026-08-15 22:31:35,874 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 22:31:35,882 reranking models by 'multimer' metric
2026-08-15 22:31:35,882 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=78.4 pTM=0.713 ipTM=0.148 ipSAE=0.00616 pDockQ2=0.0187
2026-08-15 22:31:36,203 Query 16/20: rfd3_input_anexina_binder_design_0_model_11_top5_score0.924 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:31:36,548 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 22:31:46,528 Sleeping for 7s. Reason: PENDING
2026-08-15 22:32:00,565 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.6 pTM=0.741 ipTM=0.197
2026-08-15 22:32:06,641 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.4 pTM=0.726 ipTM=0.145 tol=1.08
2026-08-15 22:32:12,795 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.7 pTM=0.745 ipTM=0.158 tol=0.268
2026-08-15 22:32:12,796 alphafold2_multimer_v3_model_1_seed_000 took 18.3s (2 recycles)
2026-08-15 22:32:12,804 reranking models by 'multimer' metric
2026-08-15 22:32:12,804 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=81.7 pTM=0.745 ipTM=0.158 ipSAE=0.00582 pDockQ2=0.0148
2026-08-15 22:32:13,115 Query 17/20: rfd3_input_anexina_binder_design_0_model_11_top6_score0.909 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:32:13,442 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:32:19,441 Sleeping for 9s. Reason: PENDING
2026-08-15 22:32:35,561 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=49.2 pTM=0.376 ipTM=0.109
2026-08-15 22:32:41,661 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.9 pTM=0.765 ipTM=0.173 tol=7.52
2026-08-15 22:32:47,836 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.8 pTM=0.778 ipTM=0.289 tol=2.19
2026-08-15 22:32:54,084 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84.8 pTM=0.764 ipTM=0.196 tol=0.482
2026-08-15 22:32:54,085 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 22:32:54,092 reranking models by 'multimer' metric
2026-08-15 22:32:54,093 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.8 pTM=0.764 ipTM=0.196 ipSAE=0.00825 pDockQ2=0.0266
2026-08-15 22:32:54,426 Query 18/20: rfd3_input_anexina_binder_design_0_model_11_top7_score0.923 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:32:54,766 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 22:33:03,741 Sleeping for 8s. Reason: PENDING
2026-08-15 22:33:18,826 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.9 pTM=0.769 ipTM=0.23
2026-08-15 22:33:24,885 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.2 pTM=0.723 ipTM=0.106 tol=1.4
2026-08-15 22:33:31,027 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=78.8 pTM=0.723 ipTM=0.141 tol=0.758
2026-08-15 22:33:37,239 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=76.6 pTM=0.708 ipTM=0.108 tol=0.642
2026-08-15 22:33:37,240 alphafold2_multimer_v3_model_1_seed_000 took 24.5s (3 recycles)
2026-08-15 22:33:37,247 reranking models by 'multimer' metric
2026-08-15 22:33:37,248 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=76.6 pTM=0.708 ipTM=0.108 ipSAE=0.00479 pDockQ2=0.0129
2026-08-15 22:33:37,566 Query 19/20: rfd3_input_anexina_binder_design_0_model_11_top8_score0.929 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:33:37,890 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:33:48,919 Sleeping for 9s. Reason: PENDING
2026-08-15 22:34:05,004 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82.1 pTM=0.739 ipTM=0.0923
2026-08-15 22:34:11,081 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.2 pTM=0.747 ipTM=0.125 tol=1.57
2026-08-15 22:34:17,247 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.4 pTM=0.747 ipTM=0.121 tol=0.247
2026-08-15 22:34:17,248 alphafold2_multimer_v3_model_1_seed_000 took 18.3s (2 recycles)
2026-08-15 22:34:17,255 reranking models by 'multimer' metric
2026-08-15 22:34:17,256 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.4 pTM=0.747 ipTM=0.121 ipSAE=0.00499 pDockQ2=0.0155
2026-08-15 22:34:17,567 Query 20/20: rfd3_input_anexina_binder_design_0_model_11_top9_score0.935 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:34:17,938 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:34:23,922 Sleeping for 10s. Reason: PENDING
2026-08-15 22:34:41,045 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82 pTM=0.741 ipTM=0.114
2026-08-15 22:34:47,183 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.1 pTM=0.731 ipTM=0.121 tol=0.714
2026-08-15 22:34:53,412 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.6 pTM=0.736 ipTM=0.126 tol=0.333
2026-08-15 22:34:53,413 alphafold2_multimer_v3_model_1_seed_000 took 18.5s (2 recycles)
2026-08-15 22:34:53,421 reranking models by 'multimer' metric
2026-08-15 22:34:53,421 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=81.6 pTM=0.736 ipTM=0.126 ipSAE=0.00539 pDockQ2=0.0169
2026-08-15 22:34:53,751 Done
Validando sequências do design: rfd3_input_anexina_binder_design_0_model_4

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-15 22:34:56,309 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-15 22:34:57,096 Running on GPU
2026-08-15 22:34:57,359 Found 5 citations for tools or databases
2026-08-15 22:34:57,618 Query 1/20: rfd3_input_anexina_binder_design_0_model_4_top10_score0.975 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 02:31 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:34:58,368 Sleeping for 6s. Reason: PENDING
2026-08-15 22:35:04,708 Sleeping for 9s. Reason: PENDING
2026-08-15 22:35:14,055 Sleeping for 6s. Reason: PENDING
2026-08-15 22:35:20,389 Sleeping for 7s. Reason: PENDING
2026-08-15 22:35:27,729 Sleeping for 5s. Reason: PENDING
2026-08-15 22:35:33,058 Sleeping for 8s. Reason: PENDING
2026-08-15 22:35:41,726 Sleeping for 6s. Reason: PENDING
2026-08-15 22:35:48,046 Sleeping for 10s. Reason: PENDING
2026-08-15 22:35:58,372 Sleeping for 8s. Reason: PENDING
2026-08-15 22:36:06,702 Sleeping for 6s. Reason: PENDING
2026-08-15 22:36:13,019 Sleeping for 6s. Reason: PENDING
2026-08-15 22:36:19,357 Sleeping for 6s. Reason: PENDING
2026-08-15 22:36:25,691 Sleeping for 8s. Reason: PENDING
2026-08-15 22:36:34,024 Sleeping for 6s. Reason: PENDING
2026-08-15 22:36:40,358 Sleeping for 8s. Reason: PENDING
2026-08-15 22:36:48,671 Sleeping for 8s. Reason: PENDING
2026-08-15 22:36:56,996 Sleeping for 10s. Reason: PENDING
2026-08-15 22:37:07,295 Sleeping for 5s. Reason: PENDING
2026-08-15 22:37:12,596 Sleeping for 6s. Reason: PENDING
2026-08-15 22:37:18,905 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:18 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-15 22:37:29,780 Sleeping for 7s. Reason: PENDING
2026-08-15 22:37:37,069 Sleeping for 10s. Reason: PENDING
2026-08-15 22:38:33,164 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=64.8 pTM=0.566 ipTM=0.0777
2026-08-15 22:39:09,221 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=64.7 pTM=0.563 ipTM=0.0928 tol=1.28
2026-08-15 22:39:15,021 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=66 pTM=0.576 ipTM=0.0982 tol=1.56
2026-08-15 22:39:20,884 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=65.4 pTM=0.563 ipTM=0.0986 tol=0.621
2026-08-15 22:39:20,884 alphafold2_multimer_v3_model_1_seed_000 took 85.5s (3 recycles)
2026-08-15 22:39:20,893 reranking models by 'multimer' metric
2026-08-15 22:39:20,893 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=65.4 pTM=0.563 ipTM=0.0986 ipSAE=0.00457 pDockQ2=0.0118
2026-08-15 22:39:21,214 Query 2/20: rfd3_input_anexina_binder_design_0_model_4_top11_score0.981 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:39:21,527 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:39:31,457 Sleeping for 9s. Reason: PENDING
2026-08-15 22:39:47,368 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86.9 pTM=0.802 ipTM=0.178
2026-08-15 22:39:53,281 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=88.2 pTM=0.813 ipTM=0.181 tol=0.441
2026-08-15 22:39:53,281 alphafold2_multimer_v3_model_1_seed_000 took 11.9s (1 recycles)
2026-08-15 22:39:53,289 reranking models by 'multimer' metric
2026-08-15 22:39:53,290 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=88.2 pTM=0.813 ipTM=0.181 ipSAE=0.00669 pDockQ2=0.0204
2026-08-15 22:39:53,615 Query 3/20: rfd3_input_anexina_binder_design_0_model_4_top12_score0.979 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:39:53,935 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 22:40:04,818 Sleeping for 5s. Reason: PENDING
2026-08-15 22:40:16,725 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=87.8 pTM=0.807 ipTM=0.153
2026-08-15 22:40:22,692 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.9 pTM=0.814 ipTM=0.156 tol=1.56
2026-08-15 22:40:28,687 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.6 pTM=0.816 ipTM=0.188 tol=0.321
2026-08-15 22:40:28,687 alphafold2_multimer_v3_model_1_seed_000 took 18.0s (2 recycles)
2026-08-15 22:40:28,696 reranking models by 'multimer' metric
2026-08-15 22:40:28,696 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.6 pTM=0.816 ipTM=0.188 ipSAE=0.00724 pDockQ2=0.0239
2026-08-15 22:40:29,032 Query 4/20: rfd3_input_anexina_binder_design_0_model_4_top13_score0.984 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:40:29,326 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:40:39,214 Sleeping for 10s. Reason: PENDING
2026-08-15 22:40:56,225 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=87.6 pTM=0.81 ipTM=0.175
2026-08-15 22:41:02,242 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=88.7 pTM=0.809 ipTM=0.122 tol=0.656
2026-08-15 22:41:08,276 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=88.2 pTM=0.809 ipTM=0.149 tol=0.292
2026-08-15 22:41:08,276 alphafold2_multimer_v3_model_1_seed_000 took 18.1s (2 recycles)
2026-08-15 22:41:08,285 reranking models by 'multimer' metric
2026-08-15 22:41:08,285 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=88.2 pTM=0.809 ipTM=0.149 ipSAE=0.00575 pDockQ2=0.02
2026-08-15 22:41:08,627 Query 5/20: rfd3_input_anexina_binder_design_0_model_4_top14_score0.987 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:41:08,931 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:41:17,820 Sleeping for 9s. Reason: PENDING
2026-08-15 22:41:33,828 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86.4 pTM=0.79 ipTM=0.171
2026-08-15 22:41:39,864 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.9 pTM=0.807 ipTM=0.204 tol=0.831
2026-08-15 22:41:45,930 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.6 pTM=0.804 ipTM=0.172 tol=0.135
2026-08-15 22:41:45,931 alphafold2_multimer_v3_model_1_seed_000 took 18.2s (2 recycles)
2026-08-15 22:41:45,940 reranking models by 'multimer' metric
2026-08-15 22:41:45,940 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.6 pTM=0.804 ipTM=0.172 ipSAE=0.00663 pDockQ2=0.0207
2026-08-15 22:41:46,268 Query 6/20: rfd3_input_anexina_binder_design_0_model_4_top15_score0.991 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:41:46,568 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:41:55,490 Sleeping for 9s. Reason: PENDING
2026-08-15 22:42:11,564 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=87.1 pTM=0.803 ipTM=0.155
2026-08-15 22:42:17,639 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=88.1 pTM=0.811 ipTM=0.151 tol=1.04
2026-08-15 22:42:23,743 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=88.1 pTM=0.813 ipTM=0.184 tol=0.765
2026-08-15 22:42:29,934 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=88.3 pTM=0.813 ipTM=0.184 tol=0.449
2026-08-15 22:42:29,935 alphafold2_multimer_v3_model_1_seed_000 took 24.5s (3 recycles)
2026-08-15 22:42:29,943 reranking models by 'multimer' metric
2026-08-15 22:42:29,943 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=88.3 pTM=0.813 ipTM=0.184 ipSAE=0.00749 pDockQ2=0.0223
2026-08-15 22:42:30,287 Query 7/20: rfd3_input_anexina_binder_design_0_model_4_top16_score0.989 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:42:30,579 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 22:42:40,494 Sleeping for 8s. Reason: PENDING
2026-08-15 22:42:55,593 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=88.6 pTM=0.791 ipTM=0.061
2026-08-15 22:43:01,711 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=88.2 pTM=0.802 ipTM=0.0907 tol=3.82
2026-08-15 22:43:07,855 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=88 pTM=0.806 ipTM=0.121 tol=2.04
2026-08-15 22:43:14,069 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=88.1 pTM=0.807 ipTM=0.131 tol=0.44
2026-08-15 22:43:14,069 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-15 22:43:14,079 reranking models by 'multimer' metric
2026-08-15 22:43:14,079 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=88.1 pTM=0.807 ipTM=0.131 ipSAE=0.00517 pDockQ2=0.0159
2026-08-15 22:43:14,408 Query 8/20: rfd3_input_anexina_binder_design_0_model_4_top17_score0.986 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:43:14,728 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 22:43:22,739 Sleeping for 5s. Reason: PENDING
2026-08-15 22:43:34,897 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.9 pTM=0.795 ipTM=0.166
2026-08-15 22:43:41,051 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.4 pTM=0.808 ipTM=0.192 tol=1.47
2026-08-15 22:43:47,283 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.4 pTM=0.809 ipTM=0.191 tol=0.267
2026-08-15 22:43:47,284 alphafold2_multimer_v3_model_1_seed_000 took 18.6s (2 recycles)
2026-08-15 22:43:47,293 reranking models by 'multimer' metric
2026-08-15 22:43:47,293 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.4 pTM=0.809 ipTM=0.191 ipSAE=0.00726 pDockQ2=0.023
2026-08-15 22:43:47,632 Query 9/20: rfd3_input_anexina_binder_design_0_model_4_top18_score0.983 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:43:47,974 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 22:43:58,951 Sleeping for 7s. Reason: PENDING
2026-08-15 22:44:13,100 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86.7 pTM=0.785 ipTM=0.147
2026-08-15 22:44:19,256 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.4 pTM=0.792 ipTM=0.136 tol=1.08
2026-08-15 22:44:25,485 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.6 pTM=0.796 ipTM=0.163 tol=0.356
2026-08-15 22:44:25,485 alphafold2_multimer_v3_model_1_seed_000 took 18.6s (2 recycles)
2026-08-15 22:44:25,494 reranking models by 'multimer' metric
2026-08-15 22:44:25,494 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.6 pTM=0.796 ipTM=0.163 ipSAE=0.00571 pDockQ2=0.0162
2026-08-15 22:44:25,841 Query 10/20: rfd3_input_anexina_binder_design_0_model_4_top19_score0.992 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:44:26,189 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:44:37,214 Sleeping for 9s. Reason: PENDING
2026-08-15 22:44:53,434 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=88 pTM=0.786 ipTM=0.0612
2026-08-15 22:44:59,648 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=88.1 pTM=0.798 ipTM=0.0968 tol=1.71
2026-08-15 22:45:05,935 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.9 pTM=0.798 ipTM=0.108 tol=0.4
2026-08-15 22:45:05,936 alphafold2_multimer_v3_model_1_seed_000 took 18.7s (2 recycles)
2026-08-15 22:45:05,944 reranking models by 'multimer' metric
2026-08-15 22:45:05,944 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.9 pTM=0.798 ipTM=0.108 ipSAE=0.00448 pDockQ2=0.0129
2026-08-15 22:45:06,276 Query 11/20: rfd3_input_anexina_binder_design_0_model_4_top1_score0.925 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:45:06,601 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:45:14,590 Sleeping for 9s. Reason: PENDING
2026-08-15 22:45:30,763 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86.4 pTM=0.796 ipTM=0.195
2026-08-15 22:45:36,941 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=88.1 pTM=0.812 ipTM=0.215 tol=0.32
2026-08-15 22:45:36,941 alphafold2_multimer_v3_model_1_seed_000 took 12.4s (1 recycles)
2026-08-15 22:45:36,951 reranking models by 'multimer' metric
2026-08-15 22:45:36,951 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=88.1 pTM=0.812 ipTM=0.215 ipSAE=0.00778 pDockQ2=0.0245
2026-08-15 22:45:37,290 Query 12/20: rfd3_input_anexina_binder_design_0_model_4_top20_score0.998 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:45:37,630 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 22:45:48,809 Sleeping for 6s. Reason: PENDING
2026-08-15 22:46:02,275 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86.8 pTM=0.794 ipTM=0.109
2026-08-15 22:46:08,485 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.5 pTM=0.796 ipTM=0.104 tol=0.495
2026-08-15 22:46:08,486 alphafold2_multimer_v3_model_1_seed_000 took 12.5s (1 recycles)
2026-08-15 22:46:08,496 reranking models by 'multimer' metric
2026-08-15 22:46:08,496 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.5 pTM=0.796 ipTM=0.104 ipSAE=0 pDockQ2=0.012
2026-08-15 22:46:08,866 Query 13/20: rfd3_input_anexina_binder_design_0_model_4_top2_score0.952 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:46:09,156 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 22:46:18,010 Sleeping for 8s. Reason: PENDING
2026-08-15 22:46:33,150 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86.6 pTM=0.79 ipTM=0.106
2026-08-15 22:46:39,312 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.8 pTM=0.804 ipTM=0.112 tol=1.22
2026-08-15 22:46:45,518 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.8 pTM=0.806 ipTM=0.135 tol=0.338
2026-08-15 22:46:45,519 alphafold2_multimer_v3_model_1_seed_000 took 18.6s (2 recycles)
2026-08-15 22:46:45,527 reranking models by 'multimer' metric
2026-08-15 22:46:45,528 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.8 pTM=0.806 ipTM=0.135 ipSAE=0.0051 pDockQ2=0.0159
2026-08-15 22:46:45,864 Query 14/20: rfd3_input_anexina_binder_design_0_model_4_top3_score0.960 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:46:46,167 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:46:52,065 Sleeping for 9s. Reason: PENDING
2026-08-15 22:47:08,119 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=87 pTM=0.787 ipTM=0.106
2026-08-15 22:47:14,243 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=86.9 pTM=0.801 ipTM=0.127 tol=4.3
2026-08-15 22:47:20,430 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=86.9 pTM=0.802 ipTM=0.124 tol=0.74
2026-08-15 22:47:26,735 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=87.1 pTM=0.8 ipTM=0.149 tol=0.528
2026-08-15 22:47:26,736 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 22:47:26,744 reranking models by 'multimer' metric
2026-08-15 22:47:26,744 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.1 pTM=0.8 ipTM=0.149 ipSAE=0.00571 pDockQ2=0.0161
2026-08-15 22:47:27,087 Query 15/20: rfd3_input_anexina_binder_design_0_model_4_top4_score0.966 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:47:27,383 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 22:47:38,293 Sleeping for 6s. Reason: PENDING
2026-08-15 22:47:51,381 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=87.4 pTM=0.783 ipTM=0.0764
2026-08-15 22:47:57,523 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.8 pTM=0.794 ipTM=0.0803 tol=5.81
2026-08-15 22:48:03,746 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.4 pTM=0.801 ipTM=0.103 tol=1.38
2026-08-15 22:48:10,076 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=87.6 pTM=0.801 ipTM=0.116 tol=0.302
2026-08-15 22:48:10,077 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 22:48:10,085 reranking models by 'multimer' metric
2026-08-15 22:48:10,085 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.6 pTM=0.801 ipTM=0.116 ipSAE=0.00447 pDockQ2=0.0131
2026-08-15 22:48:10,434 Query 16/20: rfd3_input_anexina_binder_design_0_model_4_top5_score0.972 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:48:10,746 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:48:18,660 Sleeping for 9s. Reason: PENDING
2026-08-15 22:48:34,755 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=87.3 pTM=0.779 ipTM=0.0725
2026-08-15 22:48:40,916 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87 pTM=0.797 ipTM=0.142 tol=6.56
2026-08-15 22:48:47,164 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.8 pTM=0.798 ipTM=0.116 tol=1.27
2026-08-15 22:48:53,494 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=87.6 pTM=0.798 ipTM=0.119 tol=0.351
2026-08-15 22:48:53,494 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 22:48:53,502 reranking models by 'multimer' metric
2026-08-15 22:48:53,502 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.6 pTM=0.798 ipTM=0.119 ipSAE=0.00471 pDockQ2=0.0144
2026-08-15 22:48:53,841 Query 17/20: rfd3_input_anexina_binder_design_0_model_4_top6_score0.969 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:48:54,141 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:49:01,097 Sleeping for 10s. Reason: PENDING
2026-08-15 22:49:18,182 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86.1 pTM=0.751 ipTM=0.0565
2026-08-15 22:49:24,310 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.6 pTM=0.781 ipTM=0.096 tol=2.04
2026-08-15 22:49:30,535 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87 pTM=0.78 ipTM=0.105 tol=1.22
2026-08-15 22:49:36,852 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=87.1 pTM=0.78 ipTM=0.103 tol=0.748
2026-08-15 22:49:36,852 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 22:49:36,860 reranking models by 'multimer' metric
2026-08-15 22:49:36,861 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.1 pTM=0.78 ipTM=0.103 ipSAE=0.00458 pDockQ2=0.0135
2026-08-15 22:49:37,236 Query 18/20: rfd3_input_anexina_binder_design_0_model_4_top7_score0.975 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:49:37,539 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 22:49:43,487 Sleeping for 7s. Reason: PENDING
2026-08-15 22:49:57,661 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86.8 pTM=0.788 ipTM=0.0973
2026-08-15 22:50:03,830 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.5 pTM=0.799 ipTM=0.102 tol=1.51
2026-08-15 22:50:10,062 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.1 pTM=0.798 ipTM=0.104 tol=1.5
2026-08-15 22:50:16,356 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=87.2 pTM=0.799 ipTM=0.107 tol=0.464
2026-08-15 22:50:16,356 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 22:50:16,365 reranking models by 'multimer' metric
2026-08-15 22:50:16,365 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.2 pTM=0.799 ipTM=0.107 ipSAE=0.00472 pDockQ2=0.0142
2026-08-15 22:50:16,724 Query 19/20: rfd3_input_anexina_binder_design_0_model_4_top8_score0.973 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:50:17,025 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:50:25,943 Sleeping for 9s. Reason: PENDING
2026-08-15 22:50:42,008 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86.6 pTM=0.786 ipTM=0.0787
2026-08-15 22:50:48,142 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.3 pTM=0.799 ipTM=0.12 tol=0.95
2026-08-15 22:50:54,340 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.2 pTM=0.797 ipTM=0.118 tol=0.467
2026-08-15 22:50:54,340 alphafold2_multimer_v3_model_1_seed_000 took 18.5s (2 recycles)
2026-08-15 22:50:54,349 reranking models by 'multimer' metric
2026-08-15 22:50:54,349 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.2 pTM=0.797 ipTM=0.118 ipSAE=0.00473 pDockQ2=0.014
2026-08-15 22:50:54,704 Query 20/20: rfd3_input_anexina_binder_design_0_model_4_top9_score0.972 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:50:54,996 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 22:51:01,896 Sleeping for 5s. Reason: PENDING
2026-08-15 22:51:14,167 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86.6 pTM=0.759 ipTM=0.0417
2026-08-15 22:51:20,449 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.4 pTM=0.781 ipTM=0.0598 tol=3.05
2026-08-15 22:51:26,780 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.3 pTM=0.778 ipTM=0.0723 tol=0.719
2026-08-15 22:51:33,125 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=87.6 pTM=0.78 ipTM=0.0717 tol=0.277
2026-08-15 22:51:33,125 alphafold2_multimer_v3_model_1_seed_000 took 25.3s (3 recycles)
2026-08-15 22:51:33,134 reranking models by 'multimer' metric
2026-08-15 22:51:33,134 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.6 pTM=0.78 ipTM=0.0717 ipSAE=0 pDockQ2=0.011
2026-08-15 22:51:33,487 Done
Validando sequências do design: rfd3_input_anexina_binder_design_0_model_3

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-15 22:51:36,137 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-15 22:51:36,945 Running on GPU
2026-08-15 22:51:37,217 Found 5 citations for tools or databases
2026-08-15 22:51:37,476 Query 1/20: rfd3_input_anexina_binder_design_0_model_3_top10_score1.016 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:51:38,222 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-15 22:51:48,120 Sleeping for 10s. Reason: PENDING
2026-08-15 22:52:46,543 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.8 pTM=0.773 ipTM=0.203
2026-08-15 22:53:23,953 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.4 pTM=0.767 ipTM=0.181 tol=0.965
2026-08-15 22:53:30,230 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.2 pTM=0.78 ipTM=0.192 tol=0.42
2026-08-15 22:53:30,231 alphafold2_multimer_v3_model_1_seed_000 took 83.6s (2 recycles)
2026-08-15 22:53:30,239 reranking models by 'multimer' metric
2026-08-15 22:53:30,239 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.2 pTM=0.78 ipTM=0.192 ipSAE=0.00714 pDockQ2=0.0221
2026-08-15 22:53:30,580 Query 2/20: rfd3_input_anexina_binder_design_0_model_3_top11_score1.022 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:53:30,896 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:53:40,800 Sleeping for 9s. Reason: PENDING
2026-08-15 22:53:57,020 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=68.2 pTM=0.576 ipTM=0.11
2026-08-15 22:54:03,264 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=74 pTM=0.684 ipTM=0.161 tol=1.64
2026-08-15 22:54:09,587 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=73 pTM=0.667 ipTM=0.19 tol=5.5
2026-08-15 22:54:15,944 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=72.6 pTM=0.657 ipTM=0.106 tol=5.07
2026-08-15 22:54:15,944 alphafold2_multimer_v3_model_1_seed_000 took 25.2s (3 recycles)
2026-08-15 22:54:15,953 reranking models by 'multimer' metric
2026-08-15 22:54:15,953 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=72.6 pTM=0.657 ipTM=0.106 ipSAE=0.00543 pDockQ2=0.0111
2026-08-15 22:54:16,290 Query 3/20: rfd3_input_anexina_binder_design_0_model_3_top12_score1.024 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:54:16,589 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:54:26,468 Sleeping for 9s. Reason: PENDING
2026-08-15 22:54:42,535 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=87.8 pTM=0.812 ipTM=0.241
2026-08-15 22:54:48,663 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.9 pTM=0.819 ipTM=0.224 tol=0.587
2026-08-15 22:54:54,873 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.5 pTM=0.819 ipTM=0.219 tol=0.275
2026-08-15 22:54:54,873 alphafold2_multimer_v3_model_1_seed_000 took 18.5s (2 recycles)
2026-08-15 22:54:54,882 reranking models by 'multimer' metric
2026-08-15 22:54:54,883 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.5 pTM=0.819 ipTM=0.219 ipSAE=0.00735 pDockQ2=0.0206
2026-08-15 22:54:55,220 Query 4/20: rfd3_input_anexina_binder_design_0_model_3_top13_score1.020 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:54:55,529 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 22:55:01,432 Sleeping for 7s. Reason: PENDING
2026-08-15 22:55:15,705 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.2 pTM=0.776 ipTM=0.103
2026-08-15 22:55:22,015 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.1 pTM=0.76 ipTM=0.112 tol=2.8
2026-08-15 22:55:28,409 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.4 pTM=0.767 ipTM=0.207 tol=2.21
2026-08-15 22:55:34,768 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=81.8 pTM=0.753 ipTM=0.115 tol=1.02
2026-08-15 22:55:34,768 alphafold2_multimer_v3_model_1_seed_000 took 25.4s (3 recycles)
2026-08-15 22:55:34,777 reranking models by 'multimer' metric
2026-08-15 22:55:34,777 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=81.8 pTM=0.753 ipTM=0.115 ipSAE=0.00516 pDockQ2=0.0139
2026-08-15 22:55:35,107 Query 5/20: rfd3_input_anexina_binder_design_0_model_3_top14_score1.023 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:55:35,412 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 22:55:43,329 Sleeping for 6s. Reason: PENDING
2026-08-15 22:55:56,373 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=62.7 pTM=0.496 ipTM=0.0652
2026-08-15 22:56:02,443 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=82.3 pTM=0.754 ipTM=0.191 tol=5.95
2026-08-15 22:56:08,605 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.8 pTM=0.765 ipTM=0.267 tol=0.362
2026-08-15 22:56:08,606 alphafold2_multimer_v3_model_1_seed_000 took 18.4s (2 recycles)
2026-08-15 22:56:08,614 reranking models by 'multimer' metric
2026-08-15 22:56:08,614 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.8 pTM=0.765 ipTM=0.267 ipSAE=0.0174 pDockQ2=0.0243
2026-08-15 22:56:08,953 Query 6/20: rfd3_input_anexina_binder_design_0_model_3_top15_score1.026 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:56:09,244 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:56:18,160 Sleeping for 10s. Reason: PENDING
2026-08-15 22:56:35,303 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79 pTM=0.727 ipTM=0.144
2026-08-15 22:56:41,533 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.1 pTM=0.788 ipTM=0.188 tol=0.746
2026-08-15 22:56:47,852 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.8 pTM=0.779 ipTM=0.188 tol=0.451
2026-08-15 22:56:47,852 alphafold2_multimer_v3_model_1_seed_000 took 18.8s (2 recycles)
2026-08-15 22:56:47,861 reranking models by 'multimer' metric
2026-08-15 22:56:47,861 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.8 pTM=0.779 ipTM=0.188 ipSAE=0.00771 pDockQ2=0.0221
2026-08-15 22:56:48,204 Query 7/20: rfd3_input_anexina_binder_design_0_model_3_top16_score1.030 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:56:48,518 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:56:58,433 Sleeping for 10s. Reason: PENDING
2026-08-15 22:57:15,631 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=75.8 pTM=0.676 ipTM=0.0903
2026-08-15 22:57:21,801 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=76.6 pTM=0.716 ipTM=0.118 tol=7
2026-08-15 22:57:28,080 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=74.8 pTM=0.701 ipTM=0.116 tol=0.727
2026-08-15 22:57:34,426 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=74.5 pTM=0.695 ipTM=0.113 tol=0.275
2026-08-15 22:57:34,427 alphafold2_multimer_v3_model_1_seed_000 took 25.0s (3 recycles)
2026-08-15 22:57:34,435 reranking models by 'multimer' metric
2026-08-15 22:57:34,435 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=74.5 pTM=0.695 ipTM=0.113 ipSAE=0.00524 pDockQ2=0.0121
2026-08-15 22:57:34,768 Query 8/20: rfd3_input_anexina_binder_design_0_model_3_top17_score1.026 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:57:35,078 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 22:57:45,999 Sleeping for 7s. Reason: PENDING
2026-08-15 22:58:00,094 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=75.4 pTM=0.698 ipTM=0.1
2026-08-15 22:58:06,250 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.8 pTM=0.783 ipTM=0.161 tol=1.99
2026-08-15 22:58:12,496 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.9 pTM=0.793 ipTM=0.197 tol=0.506
2026-08-15 22:58:18,813 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85.8 pTM=0.798 ipTM=0.203 tol=0.474
2026-08-15 22:58:18,813 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 22:58:18,822 reranking models by 'multimer' metric
2026-08-15 22:58:18,822 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.8 pTM=0.798 ipTM=0.203 ipSAE=0.00773 pDockQ2=0.0252
2026-08-15 22:58:19,172 Query 9/20: rfd3_input_anexina_binder_design_0_model_3_top18_score1.037 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:58:19,518 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 22:58:30,554 Sleeping for 7s. Reason: PENDING
2026-08-15 22:58:44,726 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.4 pTM=0.771 ipTM=0.203
2026-08-15 22:58:50,900 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.5 pTM=0.778 ipTM=0.141 tol=1.72
2026-08-15 22:58:57,157 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.1 pTM=0.775 ipTM=0.148 tol=0.855
2026-08-15 22:59:03,502 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84.2 pTM=0.776 ipTM=0.162 tol=0.505
2026-08-15 22:59:03,502 alphafold2_multimer_v3_model_1_seed_000 took 25.0s (3 recycles)
2026-08-15 22:59:03,510 reranking models by 'multimer' metric
2026-08-15 22:59:03,510 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.2 pTM=0.776 ipTM=0.162 ipSAE=0.00571 pDockQ2=0.0188
2026-08-15 22:59:03,855 Query 10/20: rfd3_input_anexina_binder_design_0_model_3_top19_score1.037 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:59:04,197 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 22:59:12,200 Sleeping for 10s. Reason: PENDING
2026-08-15 22:59:29,342 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79.6 pTM=0.735 ipTM=0.202
2026-08-15 22:59:35,491 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.6 pTM=0.775 ipTM=0.233 tol=1.43
2026-08-15 22:59:41,743 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.4 pTM=0.753 ipTM=0.185 tol=0.511
2026-08-15 22:59:48,067 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=82.4 pTM=0.759 ipTM=0.213 tol=0.224
2026-08-15 22:59:48,067 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 22:59:48,075 reranking models by 'multimer' metric
2026-08-15 22:59:48,076 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.4 pTM=0.759 ipTM=0.213 ipSAE=0.00749 pDockQ2=0.0212
2026-08-15 22:59:48,417 Query 11/20: rfd3_input_anexina_binder_design_0_model_3_top1_score0.947 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 22:59:48,737 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 22:59:56,763 Sleeping for 8s. Reason: PENDING
2026-08-15 23:00:11,909 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=75.3 pTM=0.529 ipTM=0.032
2026-08-15 23:00:18,035 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=68.6 pTM=0.498 ipTM=0.0348 tol=6.59
2026-08-15 23:00:24,241 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=56.1 pTM=0.443 ipTM=0.0371 tol=17.8
2026-08-15 23:00:30,547 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=59.9 pTM=0.497 ipTM=0.071 tol=5.19
2026-08-15 23:00:30,547 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 23:00:30,555 reranking models by 'multimer' metric
2026-08-15 23:00:30,555 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=59.9 pTM=0.497 ipTM=0.071 ipSAE=0 pDockQ2=0.0092
2026-08-15 23:00:30,872 Query 12/20: rfd3_input_anexina_binder_design_0_model_3_top20_score1.036 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:00:31,206 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 23:00:39,254 Sleeping for 9s. Reason: PENDING
2026-08-15 23:00:55,709 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=68.4 pTM=0.612 ipTM=0.103
2026-08-15 23:01:01,870 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=69.1 pTM=0.615 ipTM=0.128 tol=2.35
2026-08-15 23:01:08,129 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=73 pTM=0.653 ipTM=0.121 tol=0.697
2026-08-15 23:01:14,467 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=70.9 pTM=0.625 ipTM=0.107 tol=0.886
2026-08-15 23:01:14,467 alphafold2_multimer_v3_model_1_seed_000 took 25.0s (3 recycles)
2026-08-15 23:01:14,475 reranking models by 'multimer' metric
2026-08-15 23:01:14,475 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=70.9 pTM=0.625 ipTM=0.107 ipSAE=0.0052 pDockQ2=0.0122
2026-08-15 23:01:14,800 Query 13/20: rfd3_input_anexina_binder_design_0_model_3_top2_score0.986 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:01:15,165 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 23:01:24,152 Sleeping for 9s. Reason: PENDING
2026-08-15 23:01:40,324 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.2 pTM=0.768 ipTM=0.125
2026-08-15 23:01:46,474 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.4 pTM=0.751 ipTM=0.122 tol=2.35
2026-08-15 23:01:52,721 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.3 pTM=0.752 ipTM=0.157 tol=1.92
2026-08-15 23:01:59,042 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=80.6 pTM=0.747 ipTM=0.148 tol=0.133
2026-08-15 23:01:59,042 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 23:01:59,050 reranking models by 'multimer' metric
2026-08-15 23:01:59,050 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.6 pTM=0.747 ipTM=0.148 ipSAE=0.00685 pDockQ2=0.0192
2026-08-15 23:01:59,413 Query 14/20: rfd3_input_anexina_binder_design_0_model_3_top3_score0.999 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:01:59,778 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]

2026-08-15 23:02:10,800 Sleeping for 10s. Reason: PENDING
2026-08-15 23:02:27,975 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=80.4 pTM=0.745 ipTM=0.0898
2026-08-15 23:02:34,152 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83 pTM=0.772 ipTM=0.202 tol=3.18
2026-08-15 23:02:40,445 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.6 pTM=0.788 ipTM=0.24 tol=0.436
2026-08-15 23:02:40,445 alphafold2_multimer_v3_model_1_seed_000 took 18.7s (2 recycles)
2026-08-15 23:02:40,454 reranking models by 'multimer' metric
2026-08-15 23:02:40,454 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.6 pTM=0.788 ipTM=0.24 ipSAE=0.00974 pDockQ2=0.0335
2026-08-15 23:02:40,793 Query 15/20: rfd3_input_anexina_binder_design_0_model_3_top4_score1.010 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:02:41,093 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 23:02:49,005 Sleeping for 10s. Reason: PENDING
2026-08-15 23:03:06,131 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=80.6 pTM=0.73 ipTM=0.131
2026-08-15 23:03:12,340 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.4 pTM=0.769 ipTM=0.176 tol=1.12
2026-08-15 23:03:18,637 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.1 pTM=0.747 ipTM=0.101 tol=1.29
2026-08-15 23:03:24,982 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.2 pTM=0.738 ipTM=0.101 tol=5.02
2026-08-15 23:03:24,983 alphafold2_multimer_v3_model_1_seed_000 took 25.1s (3 recycles)
2026-08-15 23:03:24,991 reranking models by 'multimer' metric
2026-08-15 23:03:24,991 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.2 pTM=0.738 ipTM=0.101 ipSAE=0 pDockQ2=0.0124
2026-08-15 23:03:25,322 Query 16/20: rfd3_input_anexina_binder_design_0_model_3_top5_score1.010 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:03:25,630 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 23:03:34,507 Sleeping for 8s. Reason: PENDING
2026-08-15 23:03:49,612 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.9 pTM=0.741 ipTM=0.115
2026-08-15 23:03:55,744 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=76.9 pTM=0.709 ipTM=0.122 tol=3.81
2026-08-15 23:04:01,972 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.8 pTM=0.739 ipTM=0.137 tol=0.646
2026-08-15 23:04:08,286 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=78.4 pTM=0.722 ipTM=0.149 tol=0.662
2026-08-15 23:04:08,286 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 23:04:08,294 reranking models by 'multimer' metric
2026-08-15 23:04:08,295 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=78.4 pTM=0.722 ipTM=0.149 ipSAE=0.00607 pDockQ2=0.0175
2026-08-15 23:04:08,617 Query 17/20: rfd3_input_anexina_binder_design_0_model_3_top6_score1.015 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:04:08,907 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:04:14,833 Sleeping for 7s. Reason: PENDING
2026-08-15 23:04:28,939 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.3 pTM=0.729 ipTM=0.2
2026-08-15 23:04:35,125 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=82.2 pTM=0.76 ipTM=0.161 tol=1.01
2026-08-15 23:04:41,386 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.2 pTM=0.751 ipTM=0.138 tol=1.1
2026-08-15 23:04:47,690 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=82.7 pTM=0.763 ipTM=0.166 tol=0.471
2026-08-15 23:04:47,690 alphafold2_multimer_v3_model_1_seed_000 took 25.0s (3 recycles)
2026-08-15 23:04:47,698 reranking models by 'multimer' metric
2026-08-15 23:04:47,699 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.7 pTM=0.763 ipTM=0.166 ipSAE=0.00617 pDockQ2=0.0165
2026-08-15 23:04:48,028 Query 18/20: rfd3_input_anexina_binder_design_0_model_3_top7_score1.011 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:04:48,357 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 23:04:54,357 Sleeping for 6s. Reason: PENDING
2026-08-15 23:05:07,452 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=53 pTM=0.353 ipTM=0.0988
2026-08-15 23:05:13,575 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.1 pTM=0.771 ipTM=0.276 tol=3.49
2026-08-15 23:05:19,782 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.8 pTM=0.804 ipTM=0.299 tol=0.715
2026-08-15 23:05:26,064 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=87.7 pTM=0.806 ipTM=0.278 tol=0.639
2026-08-15 23:05:26,064 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-15 23:05:26,073 reranking models by 'multimer' metric
2026-08-15 23:05:26,073 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.7 pTM=0.806 ipTM=0.278 ipSAE=0.0226 pDockQ2=0.0508
2026-08-15 23:05:26,406 Query 19/20: rfd3_input_anexina_binder_design_0_model_3_top8_score1.015 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:15 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:05:26,763 Sleeping for 5s. Reason: PENDING
2026-08-15 23:05:32,110 Sleeping for 9s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]

2026-08-15 23:05:42,149 Sleeping for 10s. Reason: PENDING
2026-08-15 23:05:59,309 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.9 pTM=0.733 ipTM=0.0969
2026-08-15 23:06:05,474 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79 pTM=0.734 ipTM=0.161 tol=4.11
2026-08-15 23:06:11,729 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=78.9 pTM=0.736 ipTM=0.11 tol=2.05
2026-08-15 23:06:18,071 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=77.9 pTM=0.73 ipTM=0.107 tol=1.02
2026-08-15 23:06:18,071 alphafold2_multimer_v3_model_1_seed_000 took 25.0s (3 recycles)
2026-08-15 23:06:18,079 reranking models by 'multimer' metric
2026-08-15 23:06:18,079 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=77.9 pTM=0.73 ipTM=0.107 ipSAE=0.00487 pDockQ2=0.0123
2026-08-15 23:06:18,410 Query 20/20: rfd3_input_anexina_binder_design_0_model_3_top9_score1.007 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:06:18,735 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:06:29,708 Sleeping for 7s. Reason: PENDING
2026-08-15 23:06:43,901 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.2 pTM=0.783 ipTM=0.258
2026-08-15 23:06:50,060 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.8 pTM=0.786 ipTM=0.196 tol=1.33
2026-08-15 23:06:56,323 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.2 pTM=0.787 ipTM=0.186 tol=0.741
2026-08-15 23:07:02,654 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84.6 pTM=0.791 ipTM=0.186 tol=0.645
2026-08-15 23:07:02,654 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 23:07:02,662 reranking models by 'multimer' metric
2026-08-15 23:07:02,662 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.6 pTM=0.791 ipTM=0.186 ipSAE=0.00842 pDockQ2=0.0325
2026-08-15 23:07:02,990 Done
Validando sequências do design: rfd3_input_anexina_binder_design_0_model_5

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-15 23:07:05,560 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-15 23:07:06,346 Running on GPU
2026-08-15 23:07:06,610 Found 5 citations for tools or databases
2026-08-15 23:07:06,864 Query 1/20: rfd3_input_anexina_binder_design_0_model_5_top10_score1.046 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:07:07,617 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-15 23:07:18,595 Sleeping for 6s. Reason: PENDING
2026-08-15 23:08:11,393 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=71.1 pTM=0.527 ipTM=0.0859
2026-08-15 23:08:47,483 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=74.4 pTM=0.593 ipTM=0.11 tol=1.33
2026-08-15 23:08:53,633 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=76.7 pTM=0.618 ipTM=0.118 tol=0.196
2026-08-15 23:08:53,634 alphafold2_multimer_v3_model_1_seed_000 took 80.8s (2 recycles)
2026-08-15 23:08:53,642 reranking models by 'multimer' metric
2026-08-15 23:08:53,642 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=76.7 pTM=0.618 ipTM=0.118 ipSAE=0.00492 pDockQ2=0.0137
2026-08-15 23:08:53,962 Query 2/20: rfd3_input_anexina_binder_design_0_model_5_top11_score1.061 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:08:54,303 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 23:09:01,297 Sleeping for 8s. Reason: PENDING
2026-08-15 23:09:16,458 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.9 pTM=0.699 ipTM=0.101
2026-08-15 23:09:22,587 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.5 pTM=0.723 ipTM=0.111 tol=2.97
2026-08-15 23:09:28,745 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.8 pTM=0.725 ipTM=0.111 tol=0.545
2026-08-15 23:09:34,966 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84.1 pTM=0.727 ipTM=0.111 tol=0.79
2026-08-15 23:09:34,966 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-15 23:09:34,974 reranking models by 'multimer' metric
2026-08-15 23:09:34,975 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.1 pTM=0.727 ipTM=0.111 ipSAE=0.00492 pDockQ2=0.0163
2026-08-15 23:09:35,293 Query 3/20: rfd3_input_anexina_binder_design_0_model_5_top12_score1.054 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:09:35,649 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 23:09:45,657 Sleeping for 8s. Reason: PENDING
2026-08-15 23:10:00,815 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.6 pTM=0.705 ipTM=0.076
2026-08-15 23:10:06,984 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.5 pTM=0.728 ipTM=0.0897 tol=1.92
2026-08-15 23:10:13,255 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.6 pTM=0.73 ipTM=0.0974 tol=1.35
2026-08-15 23:10:19,607 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=83.9 pTM=0.73 ipTM=0.092 tol=0.866
2026-08-15 23:10:19,608 alphafold2_multimer_v3_model_1_seed_000 took 25.0s (3 recycles)
2026-08-15 23:10:19,617 reranking models by 'multimer' metric
2026-08-15 23:10:19,617 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.9 pTM=0.73 ipTM=0.092 ipSAE=0.0046 pDockQ2=0.0126
2026-08-15 23:10:19,940 Query 4/20: rfd3_input_anexina_binder_design_0_model_5_top13_score1.060 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:10:20,279 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 23:10:27,257 Sleeping for 6s. Reason: PENDING
2026-08-15 23:10:40,437 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.2 pTM=0.698 ipTM=0.0737
2026-08-15 23:10:46,598 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.9 pTM=0.733 ipTM=0.0912 tol=3.17
2026-08-15 23:10:52,835 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.1 pTM=0.742 ipTM=0.103 tol=2.3
2026-08-15 23:10:59,121 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85.9 pTM=0.744 ipTM=0.106 tol=2.28
2026-08-15 23:10:59,121 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 23:10:59,129 reranking models by 'multimer' metric
2026-08-15 23:10:59,129 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.9 pTM=0.744 ipTM=0.106 ipSAE=0.00499 pDockQ2=0.0168
2026-08-15 23:10:59,472 Query 5/20: rfd3_input_anexina_binder_design_0_model_5_top14_score1.071 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:10:59,814 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:11:10,817 Sleeping for 7s. Reason: PENDING
2026-08-15 23:11:24,929 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.8 pTM=0.719 ipTM=0.132
2026-08-15 23:11:31,057 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.4 pTM=0.728 ipTM=0.153 tol=0.756
2026-08-15 23:11:37,244 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.4 pTM=0.724 ipTM=0.137 tol=0.344
2026-08-15 23:11:37,245 alphafold2_multimer_v3_model_1_seed_000 took 18.5s (2 recycles)
2026-08-15 23:11:37,253 reranking models by 'multimer' metric
2026-08-15 23:11:37,254 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.4 pTM=0.724 ipTM=0.137 ipSAE=0.00532 pDockQ2=0.0175
2026-08-15 23:11:37,570 Query 6/20: rfd3_input_anexina_binder_design_0_model_5_top15_score1.074 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:17 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:11:37,876 Sleeping for 6s. Reason: PENDING
2026-08-15 23:11:44,181 Sleeping for 10s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 23:11:55,083 Sleeping for 5s. Reason: PENDING
2026-08-15 23:12:07,309 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.4 pTM=0.747 ipTM=0.131
2026-08-15 23:12:13,655 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=86.6 pTM=0.764 ipTM=0.19 tol=1.01
2026-08-15 23:12:20,054 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=86.9 pTM=0.762 ipTM=0.201 tol=0.625
2026-08-15 23:12:26,410 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=87 pTM=0.76 ipTM=0.198 tol=0.141
2026-08-15 23:12:26,410 alphafold2_multimer_v3_model_1_seed_000 took 25.4s (3 recycles)
2026-08-15 23:12:26,419 reranking models by 'multimer' metric
2026-08-15 23:12:26,419 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87 pTM=0.76 ipTM=0.198 ipSAE=0.00826 pDockQ2=0.022
2026-08-15 23:12:26,729 Query 7/20: rfd3_input_anexina_binder_design_0_model_5_top16_score1.078 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:12:27,028 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 23:12:35,926 Sleeping for 10s. Reason: PENDING
2026-08-15 23:12:52,919 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.6 pTM=0.732 ipTM=0.183
2026-08-15 23:12:59,011 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=86.8 pTM=0.751 ipTM=0.156 tol=0.743
2026-08-15 23:13:05,162 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=86.4 pTM=0.746 ipTM=0.147 tol=0.257
2026-08-15 23:13:05,162 alphafold2_multimer_v3_model_1_seed_000 took 18.3s (2 recycles)
2026-08-15 23:13:05,170 reranking models by 'multimer' metric
2026-08-15 23:13:05,170 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=86.4 pTM=0.746 ipTM=0.147 ipSAE=0.00518 pDockQ2=0.0134
2026-08-15 23:13:05,493 Query 8/20: rfd3_input_anexina_binder_design_0_model_5_top17_score1.077 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:13:05,787 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 23:13:11,665 Sleeping for 5s. Reason: PENDING
2026-08-15 23:13:23,863 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.8 pTM=0.758 ipTM=0.11
2026-08-15 23:13:30,210 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.9 pTM=0.763 ipTM=0.105 tol=0.955
2026-08-15 23:13:36,611 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.8 pTM=0.763 ipTM=0.102 tol=0.749
2026-08-15 23:13:42,985 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=86 pTM=0.762 ipTM=0.103 tol=0.312
2026-08-15 23:13:42,986 alphafold2_multimer_v3_model_1_seed_000 took 25.4s (3 recycles)
2026-08-15 23:13:42,995 reranking models by 'multimer' metric
2026-08-15 23:13:42,995 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=86 pTM=0.762 ipTM=0.103 ipSAE=0.00469 pDockQ2=0.0148
2026-08-15 23:13:43,340 Query 9/20: rfd3_input_anexina_binder_design_0_model_5_top18_score1.086 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:13:43,648 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 23:13:50,544 Sleeping for 9s. Reason: PENDING
2026-08-15 23:14:06,591 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.8 pTM=0.713 ipTM=0.111
2026-08-15 23:14:12,681 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.9 pTM=0.725 ipTM=0.1 tol=2.77
2026-08-15 23:14:18,825 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.6 pTM=0.728 ipTM=0.1 tol=2.78
2026-08-15 23:14:25,069 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84.8 pTM=0.723 ipTM=0.102 tol=1.58
2026-08-15 23:14:25,070 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 23:14:25,078 reranking models by 'multimer' metric
2026-08-15 23:14:25,078 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.8 pTM=0.723 ipTM=0.102 ipSAE=0.00483 pDockQ2=0.0154
2026-08-15 23:14:25,398 Query 10/20: rfd3_input_anexina_binder_design_0_model_5_top19_score1.087 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:14:25,703 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 23:14:36,572 Sleeping for 10s. Reason: PENDING
2026-08-15 23:14:53,720 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=87 pTM=0.759 ipTM=0.176
2026-08-15 23:14:59,926 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.6 pTM=0.764 ipTM=0.194 tol=1.13
2026-08-15 23:15:06,219 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.6 pTM=0.763 ipTM=0.198 tol=0.367
2026-08-15 23:15:06,219 alphafold2_multimer_v3_model_1_seed_000 took 18.7s (2 recycles)
2026-08-15 23:15:06,227 reranking models by 'multimer' metric
2026-08-15 23:15:06,228 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.6 pTM=0.763 ipTM=0.198 ipSAE=0.00768 pDockQ2=0.023
2026-08-15 23:15:06,553 Query 11/20: rfd3_input_anexina_binder_design_0_model_5_top1_score0.929 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:15:06,897 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 23:15:12,791 Sleeping for 9s. Reason: PENDING
2026-08-15 23:15:28,947 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.5 pTM=0.623 ipTM=0.0855
2026-08-15 23:15:35,130 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=77.5 pTM=0.64 ipTM=0.0798 tol=2.4
2026-08-15 23:15:41,403 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.8 pTM=0.676 ipTM=0.0931 tol=1.45
2026-08-15 23:15:47,725 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=81.6 pTM=0.691 ipTM=0.0934 tol=1.35
2026-08-15 23:15:47,726 alphafold2_multimer_v3_model_1_seed_000 took 25.0s (3 recycles)
2026-08-15 23:15:47,734 reranking models by 'multimer' metric
2026-08-15 23:15:47,734 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=81.6 pTM=0.691 ipTM=0.0934 ipSAE=0 pDockQ2=0.0127
2026-08-15 23:15:48,059 Query 12/20: rfd3_input_anexina_binder_design_0_model_5_top20_score1.079 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:15:48,363 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:15:55,253 Sleeping for 7s. Reason: PENDING
2026-08-15 23:16:09,634 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86.7 pTM=0.759 ipTM=0.141
2026-08-15 23:16:15,760 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87 pTM=0.762 ipTM=0.154 tol=0.634
2026-08-15 23:16:21,942 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=86.8 pTM=0.761 ipTM=0.162 tol=0.27
2026-08-15 23:16:21,942 alphafold2_multimer_v3_model_1_seed_000 took 18.5s (2 recycles)
2026-08-15 23:16:21,951 reranking models by 'multimer' metric
2026-08-15 23:16:21,951 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=86.8 pTM=0.761 ipTM=0.162 ipSAE=0.00702 pDockQ2=0.0204
2026-08-15 23:16:22,270 Query 13/20: rfd3_input_anexina_binder_design_0_model_5_top2_score0.953 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:21 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:16:22,568 Sleeping for 10s. Reason: PENDING
2026-08-15 23:16:32,871 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 01:26 remaining: 00:00]

2026-08-15 23:16:43,821 Sleeping for 6s. Reason: PENDING
2026-08-15 23:16:50,106 Sleeping for 6s. Reason: PENDING
2026-08-15 23:16:56,408 Sleeping for 7s. Reason: PENDING
2026-08-15 23:17:03,710 Sleeping for 5s. Reason: PENDING
2026-08-15 23:17:09,014 Sleeping for 9s. Reason: PENDING
2026-08-15 23:17:18,313 Sleeping for 8s. Reason: PENDING
2026-08-15 23:17:26,609 Sleeping for 8s. Reason: PENDING
2026-08-15 23:17:34,899 Sleeping for 8s. Reason: PENDING
2026-08-15 23:17:43,188 Sleeping for 7s. Reason: PENDING
2026-08-15 23:17:50,506 Sleeping for 9s. Reason: PENDING
2026-08-15 23:17:59,805 Sleeping for 10s. Reason: PENDING
2026-08-15 23:18:16,771 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.8 pTM=0.712 ipTM=0.0589
2026-08-15 23:18:22,741 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.4 pTM=0.73 ipTM=0.0845 tol=1.35
2026-08-15 23:18:28,757 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.7 pTM=0.732 ipTM=0.0891 tol=0.867
2026-08-15 23:18:34,865 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85.2 pTM=0.733 ipTM=0.0858 tol=0.384
2026-08-15 23:18:34,865 alphafold2_multimer_v3_model_1_seed_000 took 24.1s (3 recycles)
2026-08-15 23:18:34,873 reranking models by 'multimer' metric
2026-08-15 23:18:34,873 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.2 pTM=0.733 ipTM=0.0858 ipSAE=0 pDockQ2=0.015
2026-08-15 23:18:35,190 Query 14/20: rfd3_input_anexina_binder_design_0_model_5_top3_score1.007 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:18:35,529 Sleeping for 5s. Reason: PENDING
2026-08-15 23:18:40,859 Sleeping for 5s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:18:46,840 Sleeping for 7s. Reason: PENDING
2026-08-15 23:19:00,989 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.6 pTM=0.663 ipTM=0.0842
2026-08-15 23:19:07,108 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79.9 pTM=0.691 ipTM=0.0833 tol=2.09
2026-08-15 23:19:13,235 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.1 pTM=0.686 ipTM=0.0931 tol=5.3
2026-08-15 23:19:19,402 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.9 pTM=0.689 ipTM=0.0852 tol=0.834
2026-08-15 23:19:19,402 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 23:19:19,410 reranking models by 'multimer' metric
2026-08-15 23:19:19,410 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.9 pTM=0.689 ipTM=0.0852 ipSAE=0 pDockQ2=0.0137
2026-08-15 23:19:19,727 Query 15/20: rfd3_input_anexina_binder_design_0_model_5_top4_score1.007 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:15 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:19:20,055 Sleeping for 5s. Reason: PENDING
2026-08-15 23:19:25,385 Sleeping for 9s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 23:19:35,356 Sleeping for 6s. Reason: PENDING
2026-08-15 23:19:48,485 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79 pTM=0.628 ipTM=0.107
2026-08-15 23:19:54,610 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79.3 pTM=0.641 ipTM=0.0822 tol=1.44
2026-08-15 23:20:00,800 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.4 pTM=0.663 ipTM=0.0866 tol=1.59
2026-08-15 23:20:07,072 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=81.1 pTM=0.674 ipTM=0.0831 tol=2.03
2026-08-15 23:20:07,073 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 23:20:07,081 reranking models by 'multimer' metric
2026-08-15 23:20:07,081 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=81.1 pTM=0.674 ipTM=0.0831 ipSAE=0 pDockQ2=0.013
2026-08-15 23:20:07,406 Query 16/20: rfd3_input_anexina_binder_design_0_model_5_top5_score1.027 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:20:07,750 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 23:20:18,812 Sleeping for 9s. Reason: PENDING
2026-08-15 23:20:34,970 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.4 pTM=0.718 ipTM=0.107
2026-08-15 23:20:41,135 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.3 pTM=0.723 ipTM=0.125 tol=0.446
2026-08-15 23:20:41,135 alphafold2_multimer_v3_model_1_seed_000 took 12.3s (1 recycles)
2026-08-15 23:20:41,144 reranking models by 'multimer' metric
2026-08-15 23:20:41,144 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.3 pTM=0.723 ipTM=0.125 ipSAE=0.00562 pDockQ2=0.0137
2026-08-15 23:20:41,465 Query 17/20: rfd3_input_anexina_binder_design_0_model_5_top6_score1.025 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:20:41,811 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]

2026-08-15 23:20:52,847 Sleeping for 10s. Reason: PENDING
2026-08-15 23:21:09,992 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.5 pTM=0.699 ipTM=0.0939
2026-08-15 23:21:16,159 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.2 pTM=0.727 ipTM=0.125 tol=0.504
2026-08-15 23:21:22,375 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.8 pTM=0.728 ipTM=0.128 tol=0.224
2026-08-15 23:21:22,376 alphafold2_multimer_v3_model_1_seed_000 took 18.6s (2 recycles)
2026-08-15 23:21:22,384 reranking models by 'multimer' metric
2026-08-15 23:21:22,384 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.8 pTM=0.728 ipTM=0.128 ipSAE=0.005 pDockQ2=0.0143
2026-08-15 23:21:22,708 Query 18/20: rfd3_input_anexina_binder_design_0_model_5_top7_score1.025 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:21:23,029 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 23:21:29,034 Sleeping for 5s. Reason: PENDING
2026-08-15 23:21:41,203 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.4 pTM=0.707 ipTM=0.0851
2026-08-15 23:21:47,350 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.9 pTM=0.739 ipTM=0.0907 tol=2.89
2026-08-15 23:21:53,563 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.8 pTM=0.741 ipTM=0.0928 tol=2.02
2026-08-15 23:21:59,824 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=86.2 pTM=0.74 ipTM=0.0941 tol=0.684
2026-08-15 23:21:59,825 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 23:21:59,834 reranking models by 'multimer' metric
2026-08-15 23:21:59,834 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=86.2 pTM=0.74 ipTM=0.0941 ipSAE=0.00452 pDockQ2=0.0166
2026-08-15 23:22:00,157 Query 19/20: rfd3_input_anexina_binder_design_0_model_5_top8_score1.041 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:22:00,504 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 23:22:11,495 Sleeping for 8s. Reason: PENDING
2026-08-15 23:22:26,622 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=76.2 pTM=0.631 ipTM=0.0948
2026-08-15 23:22:32,743 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.2 pTM=0.68 ipTM=0.0793 tol=2.14
2026-08-15 23:22:38,945 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.8 pTM=0.682 ipTM=0.116 tol=1.21
2026-08-15 23:22:45,240 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.9 pTM=0.679 ipTM=0.106 tol=0.63
2026-08-15 23:22:45,240 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 23:22:45,249 reranking models by 'multimer' metric
2026-08-15 23:22:45,249 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.9 pTM=0.679 ipTM=0.106 ipSAE=0 pDockQ2=0.012
2026-08-15 23:22:45,571 Query 20/20: rfd3_input_anexina_binder_design_0_model_5_top9_score1.045 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:22:45,897 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:22:53,891 Sleeping for 7s. Reason: PENDING
2026-08-15 23:23:08,130 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.5 pTM=0.725 ipTM=0.112
2026-08-15 23:23:14,339 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.6 pTM=0.756 ipTM=0.215 tol=1.02
2026-08-15 23:23:20,620 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87 pTM=0.754 ipTM=0.183 tol=0.317
2026-08-15 23:23:20,620 alphafold2_multimer_v3_model_1_seed_000 took 18.8s (2 recycles)
2026-08-15 23:23:20,629 reranking models by 'multimer' metric
2026-08-15 23:23:20,629 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87 pTM=0.754 ipTM=0.183 ipSAE=0.00599 pDockQ2=0.0189
2026-08-15 23:23:20,963 Done
Validando sequências do design: rfd3_input_anexina_binder_design_0_model_18

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-15 23:23:23,551 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-15 23:23:24,367 Running on GPU
2026-08-15 23:23:24,630 Found 5 citations for tools or databases
2026-08-15 23:23:24,885 Query 1/20: rfd3_input_anexina_binder_design_0_model_18_top10_score1.012 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:23:25,650 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-15 23:23:36,646 Sleeping for 6s. Reason: PENDING
2026-08-15 23:24:29,386 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.8 pTM=0.784 ipTM=0.15
2026-08-15 23:25:05,353 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.4 pTM=0.783 ipTM=0.136 tol=1.02
2026-08-15 23:25:11,348 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85 pTM=0.781 ipTM=0.143 tol=1.29
2026-08-15 23:25:17,411 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85.8 pTM=0.787 ipTM=0.165 tol=0.539
2026-08-15 23:25:17,411 alphafold2_multimer_v3_model_1_seed_000 took 86.4s (3 recycles)
2026-08-15 23:25:17,419 reranking models by 'multimer' metric
2026-08-15 23:25:17,420 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.8 pTM=0.787 ipTM=0.165 ipSAE=0.00717 pDockQ2=0.0167
2026-08-15 23:25:17,739 Query 2/20: rfd3_input_anexina_binder_design_0_model_18_top11_score1.016 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:25:18,081 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 23:25:27,083 Sleeping for 5s. Reason: PENDING
2026-08-15 23:25:39,266 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.7 pTM=0.708 ipTM=0.103
2026-08-15 23:25:45,395 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.2 pTM=0.73 ipTM=0.124 tol=1.78
2026-08-15 23:25:51,578 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.6 pTM=0.721 ipTM=0.143 tol=0.263
2026-08-15 23:25:51,578 alphafold2_multimer_v3_model_1_seed_000 took 18.5s (2 recycles)
2026-08-15 23:25:51,587 reranking models by 'multimer' metric
2026-08-15 23:25:51,587 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.6 pTM=0.721 ipTM=0.143 ipSAE=0.00597 pDockQ2=0.0149
2026-08-15 23:25:51,903 Query 3/20: rfd3_input_anexina_binder_design_0_model_18_top12_score1.012 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:25:52,242 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 23:26:02,253 Sleeping for 8s. Reason: PENDING
2026-08-15 23:26:17,364 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.6 pTM=0.722 ipTM=0.155
2026-08-15 23:26:23,464 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.4 pTM=0.772 ipTM=0.105 tol=1.71
2026-08-15 23:26:29,612 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.2 pTM=0.776 ipTM=0.104 tol=1.06
2026-08-15 23:26:35,823 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=83.8 pTM=0.778 ipTM=0.116 tol=1.15
2026-08-15 23:26:35,823 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 23:26:35,831 reranking models by 'multimer' metric
2026-08-15 23:26:35,832 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.8 pTM=0.778 ipTM=0.116 ipSAE=0.00496 pDockQ2=0.0153
2026-08-15 23:26:36,151 Query 4/20: rfd3_input_anexina_binder_design_0_model_18_top13_score1.018 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:26:36,483 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 23:26:46,468 Sleeping for 10s. Reason: PENDING
2026-08-15 23:27:03,599 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.1 pTM=0.779 ipTM=0.127
2026-08-15 23:27:09,752 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.8 pTM=0.775 ipTM=0.119 tol=0.824
2026-08-15 23:27:15,965 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84 pTM=0.78 ipTM=0.13 tol=3.05
2026-08-15 23:27:22,278 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84.6 pTM=0.782 ipTM=0.15 tol=0.732
2026-08-15 23:27:22,279 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 23:27:22,288 reranking models by 'multimer' metric
2026-08-15 23:27:22,288 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.6 pTM=0.782 ipTM=0.15 ipSAE=0.00577 pDockQ2=0.0162
2026-08-15 23:27:22,609 Query 5/20: rfd3_input_anexina_binder_design_0_model_18_top14_score1.020 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:13 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:27:22,951 Sleeping for 5s. Reason: PENDING
2026-08-15 23:27:28,273 Sleeping for 7s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:27:36,277 Sleeping for 8s. Reason: PENDING
2026-08-15 23:27:51,451 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.5 pTM=0.786 ipTM=0.185
2026-08-15 23:27:57,604 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.8 pTM=0.783 ipTM=0.104 tol=0.93
2026-08-15 23:28:03,855 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.4 pTM=0.783 ipTM=0.0996 tol=0.53
2026-08-15 23:28:10,163 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84.8 pTM=0.784 ipTM=0.105 tol=0.213
2026-08-15 23:28:10,164 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 23:28:10,172 reranking models by 'multimer' metric
2026-08-15 23:28:10,172 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.8 pTM=0.784 ipTM=0.105 ipSAE=0.00468 pDockQ2=0.0153
2026-08-15 23:28:10,507 Query 6/20: rfd3_input_anexina_binder_design_0_model_18_top15_score1.028 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:13 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:28:10,804 Sleeping for 7s. Reason: PENDING
2026-08-15 23:28:18,091 Sleeping for 5s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 23:28:24,044 Sleeping for 9s. Reason: PENDING
2026-08-15 23:28:40,119 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.4 pTM=0.782 ipTM=0.179
2026-08-15 23:28:46,284 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.5 pTM=0.783 ipTM=0.165 tol=0.522
2026-08-15 23:28:52,524 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.7 pTM=0.789 ipTM=0.182 tol=0.271
2026-08-15 23:28:52,525 alphafold2_multimer_v3_model_1_seed_000 took 18.6s (2 recycles)
2026-08-15 23:28:52,533 reranking models by 'multimer' metric
2026-08-15 23:28:52,533 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.7 pTM=0.789 ipTM=0.182 ipSAE=0.00807 pDockQ2=0.0269
2026-08-15 23:28:52,842 Query 7/20: rfd3_input_anexina_binder_design_0_model_18_top16_score1.029 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:24 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:28:53,130 Sleeping for 10s. Reason: PENDING
2026-08-15 23:29:03,415 Sleeping for 8s. Reason: PENDING
2026-08-15 23:29:11,715 Sleeping for 5s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 23:29:17,600 Sleeping for 8s. Reason: PENDING
2026-08-15 23:29:32,764 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82 pTM=0.752 ipTM=0.123
2026-08-15 23:29:38,966 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83 pTM=0.758 ipTM=0.119 tol=0.785
2026-08-15 23:29:45,169 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.6 pTM=0.767 ipTM=0.117 tol=0.281
2026-08-15 23:29:45,170 alphafold2_multimer_v3_model_1_seed_000 took 18.6s (2 recycles)
2026-08-15 23:29:45,178 reranking models by 'multimer' metric
2026-08-15 23:29:45,179 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.6 pTM=0.767 ipTM=0.117 ipSAE=0.00537 pDockQ2=0.0133
2026-08-15 23:29:45,498 Query 8/20: rfd3_input_anexina_binder_design_0_model_18_top17_score1.031 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:34 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:29:45,792 Sleeping for 5s. Reason: PENDING
2026-08-15 23:29:51,093 Sleeping for 6s. Reason: PENDING
2026-08-15 23:29:57,398 Sleeping for 5s. Reason: PENDING
2026-08-15 23:30:02,730 Sleeping for 6s. Reason: PENDING
2026-08-15 23:30:09,031 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 23:30:20,039 Sleeping for 8s. Reason: PENDING
2026-08-15 23:30:35,155 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.9 pTM=0.775 ipTM=0.144
2026-08-15 23:30:41,255 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.6 pTM=0.784 ipTM=0.147 tol=0.767
2026-08-15 23:30:47,405 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.5 pTM=0.793 ipTM=0.169 tol=0.419
2026-08-15 23:30:47,406 alphafold2_multimer_v3_model_1_seed_000 took 18.4s (2 recycles)
2026-08-15 23:30:47,415 reranking models by 'multimer' metric
2026-08-15 23:30:47,415 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.5 pTM=0.793 ipTM=0.169 ipSAE=0.00719 pDockQ2=0.0193
2026-08-15 23:30:47,742 Query 9/20: rfd3_input_anexina_binder_design_0_model_18_top18_score1.026 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:30:48,082 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 23:30:57,032 Sleeping for 5s. Reason: PENDING
2026-08-15 23:31:09,216 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.2 pTM=0.748 ipTM=0.106
2026-08-15 23:31:15,348 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.9 pTM=0.767 ipTM=0.104 tol=1.5
2026-08-15 23:31:21,497 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.7 pTM=0.772 ipTM=0.131 tol=0.854
2026-08-15 23:31:27,690 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85.4 pTM=0.776 ipTM=0.132 tol=0.434
2026-08-15 23:31:27,691 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-15 23:31:27,699 reranking models by 'multimer' metric
2026-08-15 23:31:27,699 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.4 pTM=0.776 ipTM=0.132 ipSAE=0.00524 pDockQ2=0.0149
2026-08-15 23:31:28,019 Query 10/20: rfd3_input_anexina_binder_design_0_model_18_top19_score1.029 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:31:28,369 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 23:31:39,361 Sleeping for 9s. Reason: PENDING
2026-08-15 23:31:55,524 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.9 pTM=0.76 ipTM=0.113
2026-08-15 23:32:01,674 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.1 pTM=0.772 ipTM=0.0927 tol=1.38
2026-08-15 23:32:07,900 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.9 pTM=0.784 ipTM=0.119 tol=0.58
2026-08-15 23:32:14,219 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85.2 pTM=0.787 ipTM=0.135 tol=0.492
2026-08-15 23:32:14,219 alphafold2_multimer_v3_model_1_seed_000 took 24.9s (3 recycles)
2026-08-15 23:32:14,228 reranking models by 'multimer' metric
2026-08-15 23:32:14,228 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.2 pTM=0.787 ipTM=0.135 ipSAE=0.00536 pDockQ2=0.0174
2026-08-15 23:32:14,541 Query 11/20: rfd3_input_anexina_binder_design_0_model_18_top1_score0.981 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:32:14,872 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 23:32:22,893 Sleeping for 9s. Reason: PENDING
2026-08-15 23:32:39,045 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=86.1 pTM=0.786 ipTM=0.155
2026-08-15 23:32:45,199 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=86.7 pTM=0.795 ipTM=0.142 tol=1.72
2026-08-15 23:32:51,406 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87 pTM=0.797 ipTM=0.164 tol=0.47
2026-08-15 23:32:51,407 alphafold2_multimer_v3_model_1_seed_000 took 18.5s (2 recycles)
2026-08-15 23:32:51,415 reranking models by 'multimer' metric
2026-08-15 23:32:51,415 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87 pTM=0.797 ipTM=0.164 ipSAE=0.00635 pDockQ2=0.0213
2026-08-15 23:32:51,739 Query 12/20: rfd3_input_anexina_binder_design_0_model_18_top20_score1.036 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:32:52,084 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:33:01,411 Sleeping for 6s. Reason: PENDING
2026-08-15 23:33:14,858 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=75.4 pTM=0.68 ipTM=0.0834
2026-08-15 23:33:21,031 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.4 pTM=0.71 ipTM=0.0966 tol=0.583
2026-08-15 23:33:27,278 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.1 pTM=0.722 ipTM=0.116 tol=0.746
2026-08-15 23:33:33,590 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=80.1 pTM=0.731 ipTM=0.114 tol=0.367
2026-08-15 23:33:33,590 alphafold2_multimer_v3_model_1_seed_000 took 25.0s (3 recycles)
2026-08-15 23:33:33,598 reranking models by 'multimer' metric
2026-08-15 23:33:33,598 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.1 pTM=0.731 ipTM=0.114 ipSAE=0.00503 pDockQ2=0.0144
2026-08-15 23:33:33,914 Query 13/20: rfd3_input_anexina_binder_design_0_model_18_top2_score0.984 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:33:34,261 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:33:42,299 Sleeping for 7s. Reason: PENDING
2026-08-15 23:33:56,414 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=80.2 pTM=0.723 ipTM=0.113
2026-08-15 23:34:02,535 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.4 pTM=0.731 ipTM=0.135 tol=0.872
2026-08-15 23:34:08,722 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.8 pTM=0.734 ipTM=0.175 tol=0.448
2026-08-15 23:34:08,723 alphafold2_multimer_v3_model_1_seed_000 took 18.5s (2 recycles)
2026-08-15 23:34:08,731 reranking models by 'multimer' metric
2026-08-15 23:34:08,731 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=81.8 pTM=0.734 ipTM=0.175 ipSAE=0.00709 pDockQ2=0.0197
2026-08-15 23:34:09,061 Query 14/20: rfd3_input_anexina_binder_design_0_model_18_top3_score0.975 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:34:09,405 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 23:34:18,396 Sleeping for 9s. Reason: PENDING
2026-08-15 23:34:34,598 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.1 pTM=0.782 ipTM=0.184
2026-08-15 23:34:40,796 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.4 pTM=0.792 ipTM=0.192 tol=1.07
2026-08-15 23:34:47,083 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=86.1 pTM=0.801 ipTM=0.209 tol=0.99
2026-08-15 23:34:53,466 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=86.5 pTM=0.806 ipTM=0.219 tol=2.11
2026-08-15 23:34:53,467 alphafold2_multimer_v3_model_1_seed_000 took 25.1s (3 recycles)
2026-08-15 23:34:53,476 reranking models by 'multimer' metric
2026-08-15 23:34:53,476 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=86.5 pTM=0.806 ipTM=0.219 ipSAE=0.0108 pDockQ2=0.0279
2026-08-15 23:34:53,797 Query 15/20: rfd3_input_anexina_binder_design_0_model_18_top4_score1.012 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:34:54,147 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 23:35:02,181 Sleeping for 7s. Reason: PENDING
2026-08-15 23:35:16,312 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.1 pTM=0.759 ipTM=0.0522
2026-08-15 23:35:22,431 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.3 pTM=0.771 ipTM=0.106 tol=1.96
2026-08-15 23:35:28,626 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.2 pTM=0.782 ipTM=0.11 tol=0.905
2026-08-15 23:35:34,910 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85.4 pTM=0.78 ipTM=0.124 tol=0.5
2026-08-15 23:35:34,910 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 23:35:34,918 reranking models by 'multimer' metric
2026-08-15 23:35:34,918 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.4 pTM=0.78 ipTM=0.124 ipSAE=0.00505 pDockQ2=0.0149
2026-08-15 23:35:35,237 Query 16/20: rfd3_input_anexina_binder_design_0_model_18_top5_score1.016 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:35:35,580 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:35:41,588 Sleeping for 6s. Reason: PENDING
2026-08-15 23:35:54,766 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.9 pTM=0.758 ipTM=0.137
2026-08-15 23:36:00,908 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=82.7 pTM=0.757 ipTM=0.199 tol=0.892
2026-08-15 23:36:07,120 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=82.9 pTM=0.757 ipTM=0.182 tol=0.449
2026-08-15 23:36:07,121 alphafold2_multimer_v3_model_1_seed_000 took 18.5s (2 recycles)
2026-08-15 23:36:07,129 reranking models by 'multimer' metric
2026-08-15 23:36:07,129 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.9 pTM=0.757 ipTM=0.182 ipSAE=0.00773 pDockQ2=0.0205
2026-08-15 23:36:07,448 Query 17/20: rfd3_input_anexina_binder_design_0_model_18_top6_score1.014 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:36:07,777 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 23:36:14,745 Sleeping for 5s. Reason: PENDING
2026-08-15 23:36:26,913 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.4 pTM=0.78 ipTM=0.131
2026-08-15 23:36:33,076 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.1 pTM=0.787 ipTM=0.127 tol=0.565
2026-08-15 23:36:39,297 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.4 pTM=0.793 ipTM=0.146 tol=0.372
2026-08-15 23:36:39,297 alphafold2_multimer_v3_model_1_seed_000 took 18.6s (2 recycles)
2026-08-15 23:36:39,305 reranking models by 'multimer' metric
2026-08-15 23:36:39,306 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.4 pTM=0.793 ipTM=0.146 ipSAE=0.00585 pDockQ2=0.0177
2026-08-15 23:36:39,619 Query 18/20: rfd3_input_anexina_binder_design_0_model_18_top7_score1.011 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:36:39,961 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 23:36:45,929 Sleeping for 9s. Reason: PENDING
2026-08-15 23:37:02,099 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=80.7 pTM=0.746 ipTM=0.14
2026-08-15 23:37:08,237 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79.8 pTM=0.722 ipTM=0.123 tol=0.567
2026-08-15 23:37:14,447 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.1 pTM=0.728 ipTM=0.133 tol=0.17
2026-08-15 23:37:14,448 alphafold2_multimer_v3_model_1_seed_000 took 18.5s (2 recycles)
2026-08-15 23:37:14,456 reranking models by 'multimer' metric
2026-08-15 23:37:14,457 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.1 pTM=0.728 ipTM=0.133 ipSAE=0.00571 pDockQ2=0.0145
2026-08-15 23:37:14,772 Query 19/20: rfd3_input_anexina_binder_design_0_model_18_top8_score1.022 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:37:15,117 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]

2026-08-15 23:37:24,111 Sleeping for 10s. Reason: PENDING
2026-08-15 23:37:41,316 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.9 pTM=0.722 ipTM=0.13
2026-08-15 23:37:47,498 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.9 pTM=0.756 ipTM=0.101 tol=0.562
2026-08-15 23:37:53,774 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.9 pTM=0.759 ipTM=0.129 tol=1.2
2026-08-15 23:38:00,145 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=82.1 pTM=0.758 ipTM=0.125 tol=0.656
2026-08-15 23:38:00,145 alphafold2_multimer_v3_model_1_seed_000 took 25.1s (3 recycles)
2026-08-15 23:38:00,153 reranking models by 'multimer' metric
2026-08-15 23:38:00,154 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.1 pTM=0.758 ipTM=0.125 ipSAE=0.00529 pDockQ2=0.0161
2026-08-15 23:38:00,474 Query 20/20: rfd3_input_anexina_binder_design_0_model_18_top9_score1.024 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:38:00,818 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 23:38:11,823 Sleeping for 8s. Reason: PENDING
2026-08-15 23:38:26,932 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.2 pTM=0.758 ipTM=0.14
2026-08-15 23:38:33,066 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.4 pTM=0.761 ipTM=0.128 tol=1.39
2026-08-15 23:38:39,275 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.2 pTM=0.761 ipTM=0.154 tol=1.12
2026-08-15 23:38:45,579 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84.3 pTM=0.768 ipTM=0.15 tol=0.926
2026-08-15 23:38:45,580 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 23:38:45,588 reranking models by 'multimer' metric
2026-08-15 23:38:45,588 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.3 pTM=0.768 ipTM=0.15 ipSAE=0.0063 pDockQ2=0.0207
2026-08-15 23:38:45,911 Done
Validando sequências do design: rfd3_input_anexina_binder_design_0_model_17

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-15 23:38:48,476 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-15 23:38:49,294 Running on GPU
2026-08-15 23:38:49,560 Found 5 citations for tools or databases
2026-08-15 23:38:49,814 Query 1/20: rfd3_input_anexina_binder_design_0_model_17_top10_score0.799 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:38:50,573 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:17 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-15 23:38:59,563 Sleeping for 6s. Reason: PENDING
2026-08-15 23:39:05,902 Sleeping for 10s. Reason: PENDING
2026-08-15 23:40:02,160 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.2 pTM=0.737 ipTM=0.168
2026-08-15 23:40:37,981 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.6 pTM=0.746 ipTM=0.166 tol=1.39
2026-08-15 23:40:43,965 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.1 pTM=0.754 ipTM=0.159 tol=1.12
2026-08-15 23:40:50,014 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=82.4 pTM=0.773 ipTM=0.17 tol=1.07
2026-08-15 23:40:50,015 alphafold2_multimer_v3_model_1_seed_000 took 85.9s (3 recycles)
2026-08-15 23:40:50,023 reranking models by 'multimer' metric
2026-08-15 23:40:50,023 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.4 pTM=0.773 ipTM=0.17 ipSAE=0.00704 pDockQ2=0.0218
2026-08-15 23:40:50,334 Query 2/20: rfd3_input_anexina_binder_design_0_model_17_top11_score0.797 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:40:50,677 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:41:00,679 Sleeping for 7s. Reason: PENDING
2026-08-15 23:41:14,805 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=71.2 pTM=0.658 ipTM=0.16
2026-08-15 23:41:20,898 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=68.6 pTM=0.622 ipTM=0.132 tol=0.811
2026-08-15 23:41:27,059 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=66.9 pTM=0.61 ipTM=0.15 tol=0.407
2026-08-15 23:41:27,060 alphafold2_multimer_v3_model_1_seed_000 took 18.4s (2 recycles)
2026-08-15 23:41:27,068 reranking models by 'multimer' metric
2026-08-15 23:41:27,068 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=66.9 pTM=0.61 ipTM=0.15 ipSAE=0.00636 pDockQ2=0.0157
2026-08-15 23:41:27,383 Query 3/20: rfd3_input_anexina_binder_design_0_model_17_top12_score0.803 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:41:27,721 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 23:41:38,696 Sleeping for 9s. Reason: PENDING
2026-08-15 23:41:54,783 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.5 pTM=0.774 ipTM=0.215
2026-08-15 23:42:00,850 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.8 pTM=0.786 ipTM=0.13 tol=0.957
2026-08-15 23:42:06,983 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.4 pTM=0.796 ipTM=0.167 tol=1.11
2026-08-15 23:42:13,150 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84.4 pTM=0.789 ipTM=0.132 tol=0.409
2026-08-15 23:42:13,151 alphafold2_multimer_v3_model_1_seed_000 took 24.5s (3 recycles)
2026-08-15 23:42:13,159 reranking models by 'multimer' metric
2026-08-15 23:42:13,159 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.4 pTM=0.789 ipTM=0.132 ipSAE=0.00538 pDockQ2=0.0167
2026-08-15 23:42:13,472 Query 4/20: rfd3_input_anexina_binder_design_0_model_17_top13_score0.807 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:42:13,806 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 23:42:23,816 Sleeping for 10s. Reason: PENDING
2026-08-15 23:42:40,936 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79.1 pTM=0.745 ipTM=0.143
2026-08-15 23:42:47,050 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=82.4 pTM=0.769 ipTM=0.184 tol=1.23
2026-08-15 23:42:53,262 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.9 pTM=0.761 ipTM=0.176 tol=0.732
2026-08-15 23:42:59,540 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=82.3 pTM=0.765 ipTM=0.18 tol=0.381
2026-08-15 23:42:59,541 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 23:42:59,548 reranking models by 'multimer' metric
2026-08-15 23:42:59,548 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.3 pTM=0.765 ipTM=0.18 ipSAE=0.00725 pDockQ2=0.0215
2026-08-15 23:42:59,864 Query 5/20: rfd3_input_anexina_binder_design_0_model_17_top14_score0.812 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:43:00,218 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:43:11,212 Sleeping for 7s. Reason: PENDING
2026-08-15 23:43:25,311 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=75 pTM=0.701 ipTM=0.156
2026-08-15 23:43:31,421 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.2 pTM=0.716 ipTM=0.13 tol=1.1
2026-08-15 23:43:37,616 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.6 pTM=0.718 ipTM=0.15 tol=0.347
2026-08-15 23:43:37,617 alphafold2_multimer_v3_model_1_seed_000 took 18.5s (2 recycles)
2026-08-15 23:43:37,624 reranking models by 'multimer' metric
2026-08-15 23:43:37,625 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.6 pTM=0.718 ipTM=0.15 ipSAE=0.00609 pDockQ2=0.0189
2026-08-15 23:43:37,934 Query 6/20: rfd3_input_anexina_binder_design_0_model_17_top15_score0.806 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:43:38,269 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 23:43:48,289 Sleeping for 5s. Reason: PENDING
2026-08-15 23:44:00,408 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=80.2 pTM=0.751 ipTM=0.182
2026-08-15 23:44:06,534 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.8 pTM=0.755 ipTM=0.138 tol=0.938
2026-08-15 23:44:12,752 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.5 pTM=0.758 ipTM=0.172 tol=0.856
2026-08-15 23:44:19,036 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=82.7 pTM=0.768 ipTM=0.159 tol=0.628
2026-08-15 23:44:19,036 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 23:44:19,044 reranking models by 'multimer' metric
2026-08-15 23:44:19,044 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.7 pTM=0.768 ipTM=0.159 ipSAE=0.006 pDockQ2=0.0168
2026-08-15 23:44:19,394 Query 7/20: rfd3_input_anexina_binder_design_0_model_17_top16_score0.814 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:44:19,735 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 23:44:25,714 Sleeping for 10s. Reason: PENDING
2026-08-15 23:44:42,802 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=63.2 pTM=0.548 ipTM=0.116
2026-08-15 23:44:48,875 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.4 pTM=0.749 ipTM=0.147 tol=1.32
2026-08-15 23:44:55,037 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79 pTM=0.732 ipTM=0.139 tol=0.82
2026-08-15 23:45:01,283 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.4 pTM=0.735 ipTM=0.145 tol=0.573
2026-08-15 23:45:01,283 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 23:45:01,290 reranking models by 'multimer' metric
2026-08-15 23:45:01,291 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.4 pTM=0.735 ipTM=0.145 ipSAE=0.00603 pDockQ2=0.0182
2026-08-15 23:45:01,613 Query 8/20: rfd3_input_anexina_binder_design_0_model_17_top17_score0.828 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:45:01,941 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 23:45:10,917 Sleeping for 7s. Reason: PENDING
2026-08-15 23:45:25,084 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.7 pTM=0.792 ipTM=0.228
2026-08-15 23:45:31,215 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.2 pTM=0.779 ipTM=0.111 tol=0.538
2026-08-15 23:45:37,421 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.6 pTM=0.791 ipTM=0.147 tol=0.549
2026-08-15 23:45:43,712 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=83.1 pTM=0.787 ipTM=0.11 tol=0.614
2026-08-15 23:45:43,712 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 23:45:43,721 reranking models by 'multimer' metric
2026-08-15 23:45:43,721 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.1 pTM=0.787 ipTM=0.11 ipSAE=0.0049 pDockQ2=0.0139
2026-08-15 23:45:44,034 Query 9/20: rfd3_input_anexina_binder_design_0_model_17_top18_score0.822 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:45:44,373 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 23:45:53,357 Sleeping for 10s. Reason: PENDING
2026-08-15 23:46:10,437 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.5 pTM=0.769 ipTM=0.207
2026-08-15 23:46:16,526 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.6 pTM=0.783 ipTM=0.163 tol=1.14
2026-08-15 23:46:22,691 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.7 pTM=0.779 ipTM=0.154 tol=0.484
2026-08-15 23:46:22,692 alphafold2_multimer_v3_model_1_seed_000 took 18.4s (2 recycles)
2026-08-15 23:46:22,700 reranking models by 'multimer' metric
2026-08-15 23:46:22,700 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.7 pTM=0.779 ipTM=0.154 ipSAE=0.00604 pDockQ2=0.0183
2026-08-15 23:46:23,014 Query 10/20: rfd3_input_anexina_binder_design_0_model_17_top19_score0.821 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:46:23,351 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 23:46:32,337 Sleeping for 6s. Reason: PENDING
2026-08-15 23:46:45,560 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79.2 pTM=0.751 ipTM=0.207
2026-08-15 23:46:51,765 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.8 pTM=0.786 ipTM=0.18 tol=0.937
2026-08-15 23:46:58,074 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=82.4 pTM=0.791 ipTM=0.168 tol=0.447
2026-08-15 23:46:58,074 alphafold2_multimer_v3_model_1_seed_000 took 18.8s (2 recycles)
2026-08-15 23:46:58,082 reranking models by 'multimer' metric
2026-08-15 23:46:58,082 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.4 pTM=0.791 ipTM=0.168 ipSAE=0.00783 pDockQ2=0.0233
2026-08-15 23:46:58,391 Query 11/20: rfd3_input_anexina_binder_design_0_model_17_top1_score0.761 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:46:58,733 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-15 23:47:05,716 Sleeping for 8s. Reason: PENDING
2026-08-15 23:47:20,782 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=80.4 pTM=0.758 ipTM=0.217
2026-08-15 23:47:26,852 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.6 pTM=0.736 ipTM=0.161 tol=1.51
2026-08-15 23:47:33,009 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=77.8 pTM=0.724 ipTM=0.163 tol=1.05
2026-08-15 23:47:39,225 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=78.6 pTM=0.731 ipTM=0.158 tol=0.57
2026-08-15 23:47:39,225 alphafold2_multimer_v3_model_1_seed_000 took 24.5s (3 recycles)
2026-08-15 23:47:39,240 reranking models by 'multimer' metric
2026-08-15 23:47:39,240 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=78.6 pTM=0.731 ipTM=0.158 ipSAE=0.0063 pDockQ2=0.0179
2026-08-15 23:47:39,565 Query 12/20: rfd3_input_anexina_binder_design_0_model_17_top20_score0.828 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:47:39,911 Sleeping for 5s. Reason: PENDING
2026-08-15 23:47:45,232 Sleeping for 5s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 23:47:51,233 Sleeping for 6s. Reason: PENDING
2026-08-15 23:48:04,536 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.1 pTM=0.726 ipTM=0.161
2026-08-15 23:48:10,637 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.1 pTM=0.763 ipTM=0.139 tol=0.73
2026-08-15 23:48:16,826 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.9 pTM=0.761 ipTM=0.171 tol=0.53
2026-08-15 23:48:23,085 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=80.5 pTM=0.755 ipTM=0.148 tol=0.383
2026-08-15 23:48:23,085 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-15 23:48:23,093 reranking models by 'multimer' metric
2026-08-15 23:48:23,093 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.5 pTM=0.755 ipTM=0.148 ipSAE=0.00631 pDockQ2=0.0192
2026-08-15 23:48:23,409 Query 13/20: rfd3_input_anexina_binder_design_0_model_17_top2_score0.769 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:48:23,756 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 23:48:29,782 Sleeping for 5s. Reason: PENDING
2026-08-15 23:48:41,967 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=68.1 pTM=0.608 ipTM=0.141
2026-08-15 23:48:48,101 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=70.3 pTM=0.621 ipTM=0.145 tol=1.06
2026-08-15 23:48:54,301 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=69.4 pTM=0.608 ipTM=0.134 tol=0.624
2026-08-15 23:49:00,524 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=69 pTM=0.605 ipTM=0.141 tol=0.497
2026-08-15 23:49:00,525 alphafold2_multimer_v3_model_1_seed_000 took 24.8s (3 recycles)
2026-08-15 23:49:00,534 reranking models by 'multimer' metric
2026-08-15 23:49:00,534 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=69 pTM=0.605 ipTM=0.141 ipSAE=0.00592 pDockQ2=0.0143
2026-08-15 23:49:00,903 Query 14/20: rfd3_input_anexina_binder_design_0_model_17_top3_score0.771 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:49:01,246 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-15 23:49:07,263 Sleeping for 8s. Reason: PENDING
2026-08-15 23:49:22,361 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.6 pTM=0.801 ipTM=0.217
2026-08-15 23:49:28,393 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.4 pTM=0.779 ipTM=0.156 tol=0.573
2026-08-15 23:49:34,523 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=82.4 pTM=0.771 ipTM=0.154 tol=0.264
2026-08-15 23:49:34,524 alphafold2_multimer_v3_model_1_seed_000 took 18.2s (2 recycles)
2026-08-15 23:49:34,532 reranking models by 'multimer' metric
2026-08-15 23:49:34,532 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.4 pTM=0.771 ipTM=0.154 ipSAE=0.00578 pDockQ2=0.0183
2026-08-15 23:49:34,845 Query 15/20: rfd3_input_anexina_binder_design_0_model_17_top4_score0.779 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:49:35,176 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:49:43,153 Sleeping for 7s. Reason: PENDING
2026-08-15 23:49:57,379 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.8 pTM=0.731 ipTM=0.152
2026-08-15 23:50:03,644 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.2 pTM=0.749 ipTM=0.16 tol=1.08
2026-08-15 23:50:09,985 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.8 pTM=0.752 ipTM=0.171 tol=0.355
2026-08-15 23:50:09,986 alphafold2_multimer_v3_model_1_seed_000 took 18.9s (2 recycles)
2026-08-15 23:50:09,993 reranking models by 'multimer' metric
2026-08-15 23:50:09,993 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.8 pTM=0.752 ipTM=0.171 ipSAE=0.00716 pDockQ2=0.0215
2026-08-15 23:50:10,302 Query 16/20: rfd3_input_anexina_binder_design_0_model_17_top5_score0.790 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:50:10,633 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 23:50:16,632 Sleeping for 5s. Reason: PENDING
2026-08-15 23:50:28,748 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82.4 pTM=0.761 ipTM=0.112
2026-08-15 23:50:34,832 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.8 pTM=0.719 ipTM=0.122 tol=1.56
2026-08-15 23:50:40,990 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.9 pTM=0.732 ipTM=0.132 tol=0.467
2026-08-15 23:50:40,990 alphafold2_multimer_v3_model_1_seed_000 took 18.4s (2 recycles)
2026-08-15 23:50:40,997 reranking models by 'multimer' metric
2026-08-15 23:50:40,998 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.9 pTM=0.732 ipTM=0.132 ipSAE=0.00518 pDockQ2=0.0152
2026-08-15 23:50:41,305 Query 17/20: rfd3_input_anexina_binder_design_0_model_17_top6_score0.789 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:50:41,649 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:50:49,679 Sleeping for 10s. Reason: PENDING
2026-08-15 23:51:06,779 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=64.6 pTM=0.554 ipTM=0.0783
2026-08-15 23:51:12,847 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.9 pTM=0.736 ipTM=0.127 tol=1.27
2026-08-15 23:51:19,012 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.8 pTM=0.738 ipTM=0.146 tol=0.56
2026-08-15 23:51:25,250 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=80.4 pTM=0.732 ipTM=0.141 tol=0.278
2026-08-15 23:51:25,250 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 23:51:25,258 reranking models by 'multimer' metric
2026-08-15 23:51:25,258 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.4 pTM=0.732 ipTM=0.141 ipSAE=0.00533 pDockQ2=0.0159
2026-08-15 23:51:25,575 Query 18/20: rfd3_input_anexina_binder_design_0_model_17_top7_score0.793 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:51:25,901 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 23:51:36,897 Sleeping for 5s. Reason: PENDING
2026-08-15 23:51:49,063 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82 pTM=0.779 ipTM=0.188
2026-08-15 23:51:55,222 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=82.3 pTM=0.77 ipTM=0.132 tol=0.715
2026-08-15 23:52:01,455 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=82.8 pTM=0.782 ipTM=0.172 tol=0.497
2026-08-15 23:52:01,455 alphafold2_multimer_v3_model_1_seed_000 took 18.6s (2 recycles)
2026-08-15 23:52:01,463 reranking models by 'multimer' metric
2026-08-15 23:52:01,464 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.8 pTM=0.782 ipTM=0.172 ipSAE=0.00704 pDockQ2=0.0213
2026-08-15 23:52:01,769 Query 19/20: rfd3_input_anexina_binder_design_0_model_17_top8_score0.795 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:52:02,109 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 23:52:13,099 Sleeping for 10s. Reason: PENDING
2026-08-15 23:52:30,176 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.5 pTM=0.729 ipTM=0.126
2026-08-15 23:52:36,295 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.4 pTM=0.734 ipTM=0.137 tol=0.504
2026-08-15 23:52:42,496 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=78.8 pTM=0.739 ipTM=0.146 tol=0.33
2026-08-15 23:52:42,496 alphafold2_multimer_v3_model_1_seed_000 took 18.4s (2 recycles)
2026-08-15 23:52:42,504 reranking models by 'multimer' metric
2026-08-15 23:52:42,504 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=78.8 pTM=0.739 ipTM=0.146 ipSAE=0.00639 pDockQ2=0.0195
2026-08-15 23:52:42,822 Query 20/20: rfd3_input_anexina_binder_design_0_model_17_top9_score0.800 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:52:43,141 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:52:51,160 Sleeping for 7s. Reason: PENDING
2026-08-15 23:53:05,387 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.4 pTM=0.736 ipTM=0.211
2026-08-15 23:53:11,581 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=82.5 pTM=0.771 ipTM=0.171 tol=0.708
2026-08-15 23:53:17,866 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.2 pTM=0.729 ipTM=0.17 tol=0.749
2026-08-15 23:53:24,167 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=81.8 pTM=0.761 ipTM=0.149 tol=0.435
2026-08-15 23:53:24,168 alphafold2_multimer_v3_model_1_seed_000 took 25.0s (3 recycles)
2026-08-15 23:53:24,175 reranking models by 'multimer' metric
2026-08-15 23:53:24,176 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=81.8 pTM=0.761 ipTM=0.149 ipSAE=0.00596 pDockQ2=0.0192
2026-08-15 23:53:24,478 Done
Validando sequências do design: rfd3_input_anexina_binder_design_0_model_13

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-15 23:53:27,046 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-15 23:53:27,798 Running on GPU
2026-08-15 23:53:28,062 Found 5 citations for tools or databases
2026-08-15 23:53:28,319 Query 1/20: rfd3_input_anexina_binder_design_0_model_13_top10_score0.674 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:53:29,070 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-15 23:53:38,059 Sleeping for 6s. Reason: PENDING
2026-08-15 23:54:32,429 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=64.2 pTM=0.562 ipTM=0.0492
2026-08-15 23:55:08,910 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=65.5 pTM=0.601 ipTM=0.208 tol=5.14
2026-08-15 23:55:14,919 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=62.7 pTM=0.573 ipTM=0.0856 tol=2.37
2026-08-15 23:55:20,974 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=59.1 pTM=0.534 ipTM=0.0968 tol=2.92
2026-08-15 23:55:20,974 alphafold2_multimer_v3_model_1_seed_000 took 88.4s (3 recycles)
2026-08-15 23:55:20,982 reranking models by 'multimer' metric
2026-08-15 23:55:20,982 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=59.1 pTM=0.534 ipTM=0.0968 ipSAE=0.0049 pDockQ2=0.0093
2026-08-15 23:55:21,305 Query 2/20: rfd3_input_anexina_binder_design_0_model_13_top11_score0.686 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:55:21,618 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 23:55:32,676 Sleeping for 5s. Reason: PENDING
2026-08-15 23:55:44,709 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=51.9 pTM=0.418 ipTM=0.0775
2026-08-15 23:55:50,743 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=59.1 pTM=0.513 ipTM=0.115 tol=10.3
2026-08-15 23:55:56,826 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=63.8 pTM=0.558 ipTM=0.13 tol=0.904
2026-08-15 23:56:02,973 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=67.6 pTM=0.6 ipTM=0.134 tol=0.311
2026-08-15 23:56:02,973 alphafold2_multimer_v3_model_1_seed_000 took 24.4s (3 recycles)
2026-08-15 23:56:02,981 reranking models by 'multimer' metric
2026-08-15 23:56:02,981 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=67.6 pTM=0.6 ipTM=0.134 ipSAE=0.00572 pDockQ2=0.0138
2026-08-15 23:56:03,293 Query 3/20: rfd3_input_anexina_binder_design_0_model_13_top12_score0.682 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:56:03,617 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-15 23:56:13,612 Sleeping for 5s. Reason: PENDING
2026-08-15 23:56:25,666 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=64 pTM=0.612 ipTM=0.122
2026-08-15 23:56:31,751 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=62.9 pTM=0.579 ipTM=0.104 tol=3.03
2026-08-15 23:56:37,904 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=61.2 pTM=0.558 ipTM=0.108 tol=1.34
2026-08-15 23:56:44,110 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=62.2 pTM=0.56 ipTM=0.111 tol=0.987
2026-08-15 23:56:44,111 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 23:56:44,118 reranking models by 'multimer' metric
2026-08-15 23:56:44,118 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=62.2 pTM=0.56 ipTM=0.111 ipSAE=0.00533 pDockQ2=0.0113
2026-08-15 23:56:44,422 Query 4/20: rfd3_input_anexina_binder_design_0_model_13_top13_score0.687 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:56:44,761 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-15 23:56:50,790 Sleeping for 6s. Reason: PENDING
2026-08-15 23:57:03,818 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=49.3 pTM=0.417 ipTM=0.0781
2026-08-15 23:57:09,878 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=54.4 pTM=0.484 ipTM=0.0923 tol=4.23
2026-08-15 23:57:15,999 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=57 pTM=0.498 ipTM=0.088 tol=0.824
2026-08-15 23:57:22,205 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=56 pTM=0.489 ipTM=0.0923 tol=0.526
2026-08-15 23:57:22,205 alphafold2_multimer_v3_model_1_seed_000 took 24.5s (3 recycles)
2026-08-15 23:57:22,213 reranking models by 'multimer' metric
2026-08-15 23:57:22,213 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=56 pTM=0.489 ipTM=0.0923 ipSAE=0.00503 pDockQ2=0.0104
2026-08-15 23:57:22,517 Query 5/20: rfd3_input_anexina_binder_design_0_model_13_top14_score0.677 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:57:22,842 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:57:33,840 Sleeping for 7s. Reason: PENDING
2026-08-15 23:57:47,908 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=58.2 pTM=0.403 ipTM=0.0744
2026-08-15 23:57:53,987 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=53.5 pTM=0.438 ipTM=0.0818 tol=12.3
2026-08-15 23:58:00,123 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=52.4 pTM=0.437 ipTM=0.0826 tol=2.56
2026-08-15 23:58:06,371 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=53.1 pTM=0.428 ipTM=0.0955 tol=12.7
2026-08-15 23:58:06,371 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 23:58:06,379 reranking models by 'multimer' metric
2026-08-15 23:58:06,379 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=53.1 pTM=0.428 ipTM=0.0955 ipSAE=0.00498 pDockQ2=0.0111
2026-08-15 23:58:06,698 Query 6/20: rfd3_input_anexina_binder_design_0_model_13_top15_score0.688 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:58:07,042 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-15 23:58:15,013 Sleeping for 7s. Reason: PENDING
2026-08-15 23:58:29,163 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=55.4 pTM=0.424 ipTM=0.0373
2026-08-15 23:58:35,261 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=53.1 pTM=0.438 ipTM=0.061 tol=5.67
2026-08-15 23:58:41,410 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=59.4 pTM=0.502 ipTM=0.0883 tol=3.41
2026-08-15 23:58:47,623 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=55.8 pTM=0.458 ipTM=0.0837 tol=1.29
2026-08-15 23:58:47,624 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-15 23:58:47,631 reranking models by 'multimer' metric
2026-08-15 23:58:47,631 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=55.8 pTM=0.458 ipTM=0.0837 ipSAE=0 pDockQ2=0.0098
2026-08-15 23:58:47,946 Query 7/20: rfd3_input_anexina_binder_design_0_model_13_top16_score0.682 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:58:48,276 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-15 23:58:58,249 Sleeping for 10s. Reason: PENDING
2026-08-15 23:59:15,339 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=53.5 pTM=0.385 ipTM=0.0196
2026-08-15 23:59:21,409 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=52.7 pTM=0.411 ipTM=0.0368 tol=9.38
2026-08-15 23:59:27,549 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=60.8 pTM=0.448 ipTM=0.0356 tol=7.43
2026-08-15 23:59:33,774 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=59.5 pTM=0.429 ipTM=0.0472 tol=2.51
2026-08-15 23:59:33,774 alphafold2_multimer_v3_model_1_seed_000 took 24.5s (3 recycles)
2026-08-15 23:59:33,782 reranking models by 'multimer' metric
2026-08-15 23:59:33,782 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=59.5 pTM=0.429 ipTM=0.0472 ipSAE=0 pDockQ2=0.0088
2026-08-15 23:59:34,087 Query 8/20: rfd3_input_anexina_binder_design_0_model_13_top17_score0.693 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-15 23:59:34,419 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:20 remaining: 00:00]

2026-08-15 23:59:41,434 Sleeping for 9s. Reason: PENDING
2026-08-15 23:59:50,769 Sleeping for 10s. Reason: PENDING
2026-08-16 00:00:07,879 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=53.5 pTM=0.484 ipTM=0.1
2026-08-16 00:00:13,990 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=67.7 pTM=0.547 ipTM=0.187 tol=14.7
2026-08-16 00:00:20,182 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=66.8 pTM=0.531 ipTM=0.185 tol=0.499
2026-08-16 00:00:20,183 alphafold2_multimer_v3_model_1_seed_000 took 18.4s (2 recycles)
2026-08-16 00:00:20,191 reranking models by 'multimer' metric
2026-08-16 00:00:20,191 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=66.8 pTM=0.531 ipTM=0.185 ipSAE=0.00623 pDockQ2=0.0149
2026-08-16 00:00:20,501 Query 9/20: rfd3_input_anexina_binder_design_0_model_13_top18_score0.684 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:00:20,803 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-16 00:00:28,697 Sleeping for 8s. Reason: PENDING
2026-08-16 00:00:43,772 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=54.5 pTM=0.384 ipTM=0.0672
2026-08-16 00:00:49,908 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=51.3 pTM=0.377 ipTM=0.0671 tol=1.69
2026-08-16 00:00:56,108 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=55.5 pTM=0.432 ipTM=0.0661 tol=1.89
2026-08-16 00:01:02,351 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=53.5 pTM=0.4 ipTM=0.0771 tol=1.99
2026-08-16 00:01:02,352 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-16 00:01:02,360 reranking models by 'multimer' metric
2026-08-16 00:01:02,360 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=53.5 pTM=0.4 ipTM=0.0771 ipSAE=0 pDockQ2=0.0092
2026-08-16 00:01:02,679 Query 10/20: rfd3_input_anexina_binder_design_0_model_13_top19_score0.688 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:01:02,971 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-16 00:01:12,883 Sleeping for 10s. Reason: PENDING
2026-08-16 00:01:29,849 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=52.3 pTM=0.443 ipTM=0.0936
2026-08-16 00:01:35,895 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=50.3 pTM=0.432 ipTM=0.132 tol=2.35
2026-08-16 00:01:41,992 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=51.3 pTM=0.434 ipTM=0.0867 tol=2.28
2026-08-16 00:01:48,187 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=52.4 pTM=0.446 ipTM=0.0942 tol=0.97
2026-08-16 00:01:48,187 alphafold2_multimer_v3_model_1_seed_000 took 24.4s (3 recycles)
2026-08-16 00:01:48,195 reranking models by 'multimer' metric
2026-08-16 00:01:48,195 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=52.4 pTM=0.446 ipTM=0.0942 ipSAE=0.00465 pDockQ2=0.0096
2026-08-16 00:01:48,513 Query 11/20: rfd3_input_anexina_binder_design_0_model_13_top1_score0.642 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:01:48,826 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-16 00:01:55,700 Sleeping for 10s. Reason: PENDING
2026-08-16 00:02:12,780 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=62.9 pTM=0.54 ipTM=0.0975
2026-08-16 00:02:18,909 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=59.1 pTM=0.497 ipTM=0.103 tol=0.878
2026-08-16 00:02:25,105 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=52.6 pTM=0.416 ipTM=0.0936 tol=1.22
2026-08-16 00:02:31,364 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=51.6 pTM=0.403 ipTM=0.0709 tol=1.31
2026-08-16 00:02:31,364 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-16 00:02:31,372 reranking models by 'multimer' metric
2026-08-16 00:02:31,372 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=51.6 pTM=0.403 ipTM=0.0709 ipSAE=0 pDockQ2=0.0096
2026-08-16 00:02:31,683 Query 12/20: rfd3_input_anexina_binder_design_0_model_13_top20_score0.694 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:02:31,977 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-16 00:02:38,904 Sleeping for 5s. Reason: PENDING
2026-08-16 00:02:51,229 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=59.5 pTM=0.525 ipTM=0.106
2026-08-16 00:02:57,279 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=68.6 pTM=0.623 ipTM=0.127 tol=2.24
2026-08-16 00:03:03,394 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=68.1 pTM=0.625 ipTM=0.126 tol=1.28
2026-08-16 00:03:09,577 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=67.9 pTM=0.613 ipTM=0.123 tol=0.522
2026-08-16 00:03:09,578 alphafold2_multimer_v3_model_1_seed_000 took 24.5s (3 recycles)
2026-08-16 00:03:09,585 reranking models by 'multimer' metric
2026-08-16 00:03:09,586 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=67.9 pTM=0.613 ipTM=0.123 ipSAE=0.00511 pDockQ2=0.0137
2026-08-16 00:03:09,891 Query 13/20: rfd3_input_anexina_binder_design_0_model_13_top2_score0.648 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:03:10,209 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-16 00:03:17,106 Sleeping for 10s. Reason: PENDING
2026-08-16 00:03:34,122 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=57 pTM=0.488 ipTM=0.0923
2026-08-16 00:03:40,188 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=52.7 pTM=0.453 ipTM=0.0967 tol=2.57
2026-08-16 00:03:46,323 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=51.8 pTM=0.433 ipTM=0.103 tol=1.09
2026-08-16 00:03:52,555 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=53.4 pTM=0.45 ipTM=0.0995 tol=0.726
2026-08-16 00:03:52,556 alphafold2_multimer_v3_model_1_seed_000 took 24.5s (3 recycles)
2026-08-16 00:03:52,563 reranking models by 'multimer' metric
2026-08-16 00:03:52,564 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=53.4 pTM=0.45 ipTM=0.0995 ipSAE=0.00477 pDockQ2=0.0101
2026-08-16 00:03:52,916 Query 14/20: rfd3_input_anexina_binder_design_0_model_13_top3_score0.638 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:03:53,224 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:03:59,207 Sleeping for 8s. Reason: PENDING
2026-08-16 00:04:14,289 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=61.4 pTM=0.381 ipTM=0.0246
2026-08-16 00:04:20,391 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=60.6 pTM=0.406 ipTM=0.0399 tol=12.5
2026-08-16 00:04:26,547 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=50 pTM=0.378 ipTM=0.0523 tol=15.8
2026-08-16 00:04:32,760 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=51.5 pTM=0.392 ipTM=0.053 tol=2.26
2026-08-16 00:04:32,761 alphafold2_multimer_v3_model_1_seed_000 took 24.6s (3 recycles)
2026-08-16 00:04:32,768 reranking models by 'multimer' metric
2026-08-16 00:04:32,768 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=51.5 pTM=0.392 ipTM=0.053 ipSAE=0 pDockQ2=0.0089
2026-08-16 00:04:33,075 Query 15/20: rfd3_input_anexina_binder_design_0_model_13_top4_score0.642 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:04:33,400 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-16 00:04:43,394 Sleeping for 9s. Reason: PENDING
2026-08-16 00:04:59,485 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=61.2 pTM=0.484 ipTM=0.0685
2026-08-16 00:05:05,531 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=55.6 pTM=0.461 ipTM=0.076 tol=1.28
2026-08-16 00:05:11,645 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=55 pTM=0.44 ipTM=0.0704 tol=2.78
2026-08-16 00:05:17,856 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=56.6 pTM=0.46 ipTM=0.0809 tol=1.95
2026-08-16 00:05:17,856 alphafold2_multimer_v3_model_1_seed_000 took 24.5s (3 recycles)
2026-08-16 00:05:17,864 reranking models by 'multimer' metric
2026-08-16 00:05:17,864 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=56.6 pTM=0.46 ipTM=0.0809 ipSAE=0 pDockQ2=0.0099
2026-08-16 00:05:18,165 Query 16/20: rfd3_input_anexina_binder_design_0_model_13_top5_score0.644 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:05:18,508 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-16 00:05:26,487 Sleeping for 9s. Reason: PENDING
2026-08-16 00:05:42,618 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=52.8 pTM=0.452 ipTM=0.0697
2026-08-16 00:05:48,739 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.4 pTM=0.675 ipTM=0.429 tol=16.5
2026-08-16 00:05:54,921 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=74.5 pTM=0.596 ipTM=0.193 tol=0.504
2026-08-16 00:06:01,168 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=74.6 pTM=0.606 ipTM=0.107 tol=1.05
2026-08-16 00:06:01,169 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-16 00:06:01,177 reranking models by 'multimer' metric
2026-08-16 00:06:01,177 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=74.6 pTM=0.606 ipTM=0.107 ipSAE=0 pDockQ2=0.0122
2026-08-16 00:06:01,483 Query 17/20: rfd3_input_anexina_binder_design_0_model_13_top6_score0.631 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:06:01,838 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:13 remaining: 00:00]

2026-08-16 00:06:08,839 Sleeping for 7s. Reason: RATELIMIT
2026-08-16 00:06:16,179 Sleeping for 5s. Reason: PENDING
2026-08-16 00:06:28,199 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=56.3 pTM=0.504 ipTM=0.0977
2026-08-16 00:06:34,245 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=58.9 pTM=0.523 ipTM=0.0891 tol=1.88
2026-08-16 00:06:40,359 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=57.7 pTM=0.497 ipTM=0.0931 tol=0.769
2026-08-16 00:06:46,565 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=57.3 pTM=0.491 ipTM=0.093 tol=0.332
2026-08-16 00:06:46,566 alphafold2_multimer_v3_model_1_seed_000 took 24.4s (3 recycles)
2026-08-16 00:06:46,573 reranking models by 'multimer' metric
2026-08-16 00:06:46,573 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=57.3 pTM=0.491 ipTM=0.093 ipSAE=0 pDockQ2=0.0098
2026-08-16 00:06:46,873 Query 18/20: rfd3_input_anexina_binder_design_0_model_13_top7_score0.651 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:14 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:06:47,191 Sleeping for 8s. Reason: RATELIMIT
2026-08-16 00:06:55,517 Sleeping for 5s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-16 00:07:01,523 Sleeping for 5s. Reason: PENDING
2026-08-16 00:07:13,647 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=51.2 pTM=0.395 ipTM=0.0529
2026-08-16 00:07:19,773 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=51 pTM=0.401 ipTM=0.072 tol=1.11
2026-08-16 00:07:25,962 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=50.6 pTM=0.392 ipTM=0.0603 tol=1.15
2026-08-16 00:07:32,228 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=51.9 pTM=0.403 ipTM=0.071 tol=0.708
2026-08-16 00:07:32,229 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-16 00:07:32,236 reranking models by 'multimer' metric
2026-08-16 00:07:32,236 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=51.9 pTM=0.403 ipTM=0.071 ipSAE=0 pDockQ2=0.0095
2026-08-16 00:07:32,541 Query 19/20: rfd3_input_anexina_binder_design_0_model_13_top8_score0.660 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:19 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:07:32,871 Sleeping for 9s. Reason: RATELIMIT
2026-08-16 00:07:42,201 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-16 00:07:52,174 Sleeping for 6s. Reason: PENDING
2026-08-16 00:08:05,235 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=59.9 pTM=0.366 ipTM=0.0183
2026-08-16 00:08:11,308 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=57.2 pTM=0.396 ipTM=0.0304 tol=27.9
2026-08-16 00:08:17,439 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=58.1 pTM=0.437 ipTM=0.0441 tol=5.3
2026-08-16 00:08:23,671 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=60.2 pTM=0.432 ipTM=0.0447 tol=0.977
2026-08-16 00:08:23,671 alphafold2_multimer_v3_model_1_seed_000 took 24.5s (3 recycles)
2026-08-16 00:08:23,678 reranking models by 'multimer' metric
2026-08-16 00:08:23,678 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=60.2 pTM=0.432 ipTM=0.0447 ipSAE=0 pDockQ2=0.0086
2026-08-16 00:08:23,981 Query 20/20: rfd3_input_anexina_binder_design_0_model_13_top9_score0.665 (length 98)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:16 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:08:24,302 Sleeping for 7s. Reason: RATELIMIT
2026-08-16 00:08:31,642 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:14 remaining: 00:00]

2026-08-16 00:08:40,647 Sleeping for 6s. Reason: RATELIMIT
2026-08-16 00:08:46,976 Sleeping for 7s. Reason: PENDING
2026-08-16 00:09:01,088 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=52.6 pTM=0.411 ipTM=0.0798
2026-08-16 00:09:07,208 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=59 pTM=0.442 ipTM=0.0522 tol=11.4
2026-08-16 00:09:13,394 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=59.2 pTM=0.457 ipTM=0.0621 tol=5.93
2026-08-16 00:09:19,660 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=52.7 pTM=0.411 ipTM=0.0829 tol=12.1
2026-08-16 00:09:19,660 alphafold2_multimer_v3_model_1_seed_000 took 24.7s (3 recycles)
2026-08-16 00:09:19,667 reranking models by 'multimer' metric
2026-08-16 00:09:19,667 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=52.7 pTM=0.411 ipTM=0.0829 ipSAE=0 pDockQ2=0.0095
2026-08-16 00:09:19,969 Done

In [18]:
import os
import glob
import json
import numpy as np
import pandas as pd

# como eu estou usando o dataset do outro notebook, 
# preciso comentar aqui, depois tem que descomentar quando for usar o kernel
af2_dir = "/kaggle/working/outputs/af2_predictions_multimer" 

# Comentar aqui quando for usar kernel
#af2_dir = "/kaggle/input/datasets/calistu/d40g-protein-design-outputs/outputs/af2_predictions_multimer"
resultados = []

print("Analisando as predições do AlphaFold2...")
score_files = glob.glob(f"{af2_dir}/*/*_scores_*.json")
if len(score_files) == 0:
    raise ValueError("Não foi encontrado os arquivos do alphafold2")

# A busca agora usa um coringa mais flexível para capturar os arquivos do ColabFold
for score_file in score_files:
    with open(score_file, 'r') as f:
        data = json.load(f)
        
    # Limpa o nome do arquivo para ficar apenas o nome do design original
    nome_base = os.path.basename(score_file).split("_scores_")[0]
    
    # Extrair pLDDT médio (Confiança no dobramento do binder)
    plddt_array = data.get("plddt", [])
    # Assumindo que a Cadeia A (binder) são os primeiros 60 resíduos gerados
    protein_plddt = np.mean(plddt_array[0:-60])
    binder_plddt = np.mean(plddt_array[-60:])
    
    # Extrair ipTM (Interface pTM - Confiança na ligação Binder/Alvo)
    iptm = data.get("iptm", 0)
    
    # Extrair pTM global (Confiança na estrutura inteira)
    ptm = data.get("ptm", 0)
    
    resultados.append({
        "Candidato": nome_base,
        "ipTM (Afinidade)": round(iptm, 3),
        "pLDDT do Binder": round(binder_plddt, 1),
        "pLDDT da Proteína": round(protein_plddt, 1),
        "pTM Global": round(ptm, 3)
    })

# Criar a tabela e ordenar pelos melhores
df_resultados = pd.DataFrame(resultados)

# O ranking foca em ipTM alto e binder estável
df_resultados = df_resultados.sort_values(by=["ipTM (Afinidade)", "pLDDT do Binder"], ascending=[False, False])
#df_resultados = df_resultados.sort_values(by=["pLDDT do Binder", "ipTM (Afinidade)"], ascending=[False, False])

melhor_modelo_inicial = df_resultados.iloc[0]["Candidato"]
melhor_estrutura_inicial = os.path.join(af2_dir, melhor_modelo_inicial)

NUM_RODADAS_REFINAMENTO = 6

print("🏆 RANKING DOS MELHORES BINDERS PARA A ANEXINA A11 (D40G) 🏆")
display(df_resultados.head(10))
print(f"\nMelhor estrutura inicial para refinamento: {melhor_modelo_inicial}")
print(f"Número de rodadas de refinamento configurado: {NUM_RODADAS_REFINAMENTO}")

Analisando as predições do AlphaFold2...
🏆 RANKING DOS MELHORES BINDERS PARA A ANEXINA A11 (D40G) 🏆

,Candidato,ipTM (Afinidade),pLDDT do Binder,pLDDT da Proteína,pTM Global
26,rfd3_input_anexina_binder_design_0_model_0_top...,0.36,94.3,78.0,0.80
39,rfd3_input_anexina_binder_design_0_model_0_top...,0.29,95.3,77.3,0.82
18,rfd3_input_anexina_binder_design_0_model_19_to...,0.29,93.4,78.7,0.80
108,rfd3_input_anexina_binder_design_0_model_3_top...,0.28,95.0,76.2,0.81
119,rfd3_input_anexina_binder_design_0_model_3_top...,0.27,91.0,72.3,0.77
67,rfd3_input_anexina_binder_design_0_model_11_to...,0.26,90.4,74.8,0.74
20,rfd3_input_anexina_binder_design_0_model_0_top...,0.24,95.2,75.1,0.81
114,rfd3_input_anexina_binder_design_0_model_3_top...,0.24,92.7,71.8,0.79
101,rfd3_input_anexina_binder_design_0_model_3_top...,0.22,95.7,74.5,0.82
83,rfd3_input_anexina_binder_design_0_model_4_top...,0.22,95.3,76.7,0.81

Melhor estrutura inicial para refinamento: rfd3_input_anexina_binder_design_0_model_0_top5_score0.962
Número de rodadas de refinamento configurado: 6

In [19]:
import gc
import gzip
import json
import os
import shutil
import subprocess
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from Bio.PDB import MMCIFParser, PDBIO, PDBParser, Select
from Bio.PDB.PDBExceptions import PDBConstructionWarning

try:
    import torch
except Exception:
    torch = None

NUM_RODADAS_REFINAMENTO = int(globals().get("NUM_RODADAS_REFINAMENTO", 1))

alvo_d40g_completo = "MSYPGYPPPPGGYPPAAPGGGPWGGAAYPPPPSMPPIGLGNVATYAGQFNQDYLSGMAANMSGTFGGANMPNLYPGAPGAGYPPVPPGGFGQPPSAQQPVPPYGMYPPPGGNPPSRMPSYPPYPGAPVPGQPMPPPGQQPPGAYPGQPPVTYPGQPPVPLPGQQQPVPSYPGYPGSGTVTPAVPPTQFGSRGTITDAPGFDPLRDAEVLRKAMKGFGTDEQAIIDCLGSRSNKQRQQILLSFKTAYGKDLIKDLKSELSGNFEKTILALMKTPVLFDIYEIKEAIKGVGTDEACLIEILASRSNEHIRELNRAYKAEFKKTLEEAIRSDTSGHFQRLLISLSQGNRDESTNVDMSLAQRDAQELYAAGENRLGTDESKFNAVLCSRSRAHLVAVFNEYQRMTGRDIEKSICREMSGDLEEGMLAVVKCLKNTPAFFAERLNKAMRGAGTKDRTLIRIMVSRSETDLLDIRSEYKRMYGKSLYHDISGDTSGDYRKILLKICGGND"
fragmento_d40g = alvo_d40g_completo[24:55]

alvo_contexto = "A1-11"
select_fixed_atoms = {
    "A1-2": [],
    "A3": "N,CA,C,O,CB",
    "A4": [],
    "A5": "N,CA,C,O,CB",
    "A6": [],
    "A7": "N,CA,C,O,CB",
    "A8-10": [],
    "A11": "N,CA,C,O,CB",
}
select_hotspots = {
    "A3": "CB",
    "A5": "CB",
    "A7": "CB",
    "A11": "CB",
}

PARTIAL_T_INICIAL = 3.0
PARTIAL_T_DECAY = 0.75
PARTIAL_T_MINIMO = 1.0
TOP_K_RESULTADOS_POR_RODADA = 4

REFINEMENT_ROOT = Path("/kaggle/working/outputs/level2/refinement_rounds")
SEED_AF2_DIR = Path("/kaggle/working/outputs/af2_predictions_multimer")


def preparar_diretorio_limpo(path: Path) -> None:
    shutil.rmtree(path, ignore_errors=True)
    path.mkdir(parents=True, exist_ok=True)


def localizar_pdb_rank_001(design_dir: Path) -> Path:
    if design_dir.is_file():
        design_dir = design_dir.parent

    candidatos = sorted(design_dir.rglob("*rank_001*.pdb"))
    if not candidatos:
        candidatos = sorted(design_dir.rglob("*.pdb"))
    if not candidatos:
        raise FileNotFoundError(f"Nenhum PDB encontrado em {design_dir}")
    return candidatos[0]


def resolver_pasta_colabfold(candidate_name: str, af2_dir: Path) -> Path:
    base_name = candidate_name.split("_top")[0]

    candidate_dir = af2_dir / candidate_name
    if candidate_dir.exists():
        return candidate_dir

    base_dir = af2_dir / base_name
    if base_dir.exists():
        return base_dir

    matches = sorted(af2_dir.glob(f"{base_name}*"))
    if matches:
        return matches[0]

    return candidate_dir


def carregar_ranking_af2(af2_dir: Path, tamanho_fragmento: int) -> pd.DataFrame:
    resultados = []
    score_files = sorted(af2_dir.glob("*/*_scores_*.json"))
    if not score_files:
        raise ValueError(f"Nao foi encontrado nenhum arquivo de score em {af2_dir}")

    for score_file in score_files:
        with open(score_file, "r") as f:
            data = json.load(f)

        nome_base = score_file.name.split("_scores_")[0]
        plddt_array = data.get("plddt", [])
        protein_plddt = np.mean(plddt_array[:tamanho_fragmento]) if len(plddt_array) >= tamanho_fragmento else np.mean(plddt_array)
        binder_plddt = np.mean(plddt_array[tamanho_fragmento:]) if len(plddt_array) > tamanho_fragmento else np.mean(plddt_array)
        iptm = data.get("iptm", 0)
        ptm = data.get("ptm", 0)

        resultados.append(
            {
                "Candidato": nome_base,
                "ipTM (Afinidade)": round(iptm, 3),
                "pLDDT do Binder": round(float(binder_plddt), 1),
                "pLDDT da Proteina": round(float(protein_plddt), 1),
                "pTM Global": round(ptm, 3),
            }
        )

    df = pd.DataFrame(resultados)
    if df.empty:
        raise ValueError(f"Nao foi possivel montar o ranking a partir de {af2_dir}")

    #return df.sort_values(by=["pLDDT do Binder", "ipTM (Afinidade)"], ascending=[False, False])
    return df.sort_values(by=["ipTM (Afinidade)", "pLDDT do Binder"], ascending=[False, False])


def converter_cifs_para_pdb(cif_dir: Path, pdb_dir: Path) -> None:
    parser = MMCIFParser()
    io = PDBIO()
    for file in sorted(cif_dir.iterdir()):
        if not file.name.endswith(".cif.gz"):
            continue

        base_name = file.name.replace(".cif.gz", "")
        gz_path = file
        cif_path = cif_dir / f"{base_name}.cif"
        pdb_path = pdb_dir / f"{base_name}.pdb"

        with gzip.open(gz_path, "rb") as f_in:
            with open(cif_path, "wb") as f_out:
                f_out.write(f_in.read())

        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", PDBConstructionWarning)
                structure = parser.get_structure(base_name, str(cif_path))

            io.set_structure(structure)
            io.save(str(pdb_path))
            print(f"✓ Convertido com sucesso: {pdb_path.name}")
        except Exception as e:
            print(f"✗ Erro ao converter {base_name}: {e}")


def filtrar_backbones(cif_dir: Path, pdb_dir: Path, filtered_pdb_dir: Path) -> pd.DataFrame:
    min_fracao_estruturada = 0.30
    max_clashes = 0
    top_k_backbones = 10

    candidatos = []
    print("Iniciando a filtragem rigorosa de backbones...")

    for file in sorted(cif_dir.iterdir()):
        if not file.name.endswith(".json"):
            continue

        base_name = file.stem
        json_path = file
        pdb_path = pdb_dir / f"{base_name}.pdb"

        if not pdb_path.exists():
            continue

        with open(json_path, "r") as f:
            data = json.load(f)
            metrics = data.get("metrics", {})

        fracao = metrics.get("non_loop_fraction", 0)
        clashes = metrics.get("n_clashing.interresidue_clashes_w_backbone", 999)
        desvio = metrics.get("max_ca_deviation", 999)

        candidatos.append(
            {
                "base_name": base_name,
                "pdb_path": pdb_path,
                "fracao": fracao,
                "desvio": desvio,
                "clashes": clashes,
            }
        )

    candidatos_estritos = [
        c for c in candidatos
        if c["fracao"] >= min_fracao_estruturada and c["clashes"] <= max_clashes
    ]

    candidatos_estritos.sort(key=lambda x: (-x["fracao"], x["desvio"], x["clashes"]))

    if candidatos_estritos:
        melhores = candidatos_estritos[:top_k_backbones]
        modo_filtro = "estrito"
    else:
        candidatos.sort(key=lambda x: (-x["fracao"], x["desvio"], x["clashes"]))
        melhores = candidatos[:max(1, top_k_backbones)]
        modo_filtro = "fallback"

    for backbone in melhores:
        destino = filtered_pdb_dir / f"{backbone['base_name']}.pdb"
        shutil.copy2(backbone["pdb_path"], destino)

    print("Filtragem concluida!")
    print(f"✓ Total avaliados: {len(candidatos)}")
    print(f"✓ Total no filtro estrito (fracao >= 0.30 e clashes <= 0): {len(candidatos_estritos)}")
    if modo_filtro == "fallback":
        print("⚠️ Nenhum backbone passou no filtro estrito; usando fallback com os melhores disponiveis.")
    print(f"🏆 Aprovados e enviados para o MPNN (Top {top_k_backbones}): {len(melhores)}")

    return pd.DataFrame(melhores)


def gerar_mpnn(pdb_dir: Path, output_base: Path) -> None:
    output_base.mkdir(parents=True, exist_ok=True)
    pdb_files = list(sorted(pdb_dir.glob("*.pdb")))

    if not pdb_files:
        raise ValueError(f"Nenhum arquivo .pdb encontrado em {pdb_dir}")

    for p in pdb_files:
        name = p.stem
        print(f"Desenhando sequencias para o backbone: {name}")

        out_folder = output_base / name
        out_folder.mkdir(parents=True, exist_ok=True)

        cmd = [
            "python",
            "ProteinMPNN/protein_mpnn_run.py",
            "--pdb_path",
            str(p),
            "--pdb_path_chains",
            "B",
            "--out_folder",
            str(out_folder),
            "--num_seq_per_target",
            "200",
            "--sampling_temp",
            "0.25",
            "--seed",
            "42",
            "--batch_size",
            "1",
            "--suppress_print",
            "1",
        ]

        subprocess.run(cmd, check=True)


def gerar_af2_inputs(mpnn_seq_dir: Path, af2_input_dir: Path) -> int:
    top_n_por_backbone = 10
    score_maximo = 1.1

    af2_input_dir.mkdir(parents=True, exist_ok=True)
    total_geradas = 0

    print("Filtrando e formatando complexos para o AlphaFold Multimer...")

    for seq_design_folder in sorted(mpnn_seq_dir.iterdir()):
        if not seq_design_folder.is_dir():
            continue

        design_name = seq_design_folder.name
        out_subfolder = af2_input_dir / design_name
        out_subfolder.mkdir(parents=True, exist_ok=True)

        for fasta_file in sorted((seq_design_folder / "seqs").glob("*.fa")):
            base_name = fasta_file.stem

            with open(fasta_file, "r") as f:
                linhas = f.readlines()

            sequencias_avaliadas = []

            for i in range(2, len(linhas), 2):
                header = linhas[i].strip()
                seq_linha = linhas[i + 1].strip()

                try:
                    score = float(__import__("re").search(r"score=([\d\.]+)", header).group(1))
                    global_score = float(__import__("re").search(r"global_score=([\d\.]+)", header).group(1))
                except AttributeError:
                    continue

                binder_seq = seq_linha.split("/")[0]
                sequencias_avaliadas.append(
                    {
                        "binder_seq": binder_seq,
                        "score": score,
                        "global_score": global_score,
                    }
                )

            sequencias_avaliadas.sort(key=lambda x: x["global_score"])
            melhores_seqs = [seq for seq in sequencias_avaliadas if seq["score"] <= score_maximo][:top_n_por_backbone]

            contador_seq = 1
            for seq_data in melhores_seqs:
                seq_complexo = f"{fragmento_d40g}:{seq_data['binder_seq']}"
                score_formatado = f"{seq_data['score']:.3f}"
                nome_arquivo = out_subfolder / f"{base_name}_top{contador_seq}_score{score_formatado}.fasta"

                with open(nome_arquivo, "w") as out_f:
                    out_f.write(
                        f">{base_name}_top{contador_seq} | score={seq_data['score']} | global_score={seq_data['global_score']}\n{seq_complexo}\n"
                    )

                contador_seq += 1
                total_geradas += 1

    print(f"✓ Pronto! {total_geradas} complexos organizados para validacao do fragmento.")
    return total_geradas


def rodar_colabfold(af2_input_dir: Path, af2_output_dir: Path, template_dir: Path, num_models: str = "2") -> None:
    af2_output_dir.mkdir(parents=True, exist_ok=True)

    for design_path in sorted(af2_input_dir.iterdir()):
        if not design_path.is_dir():
            continue

        design_name = design_path.name
        print(f"Validando sequencias do design: {design_name}")

        design_output_dir = af2_output_dir / design_name
        design_output_dir.mkdir(parents=True, exist_ok=True)

        cmd = [
            "colabfold_batch",
            str(design_path),
            str(design_output_dir),
            "--model-type",
            "alphafold2_multimer_v3",
            "--num-recycle",
            "3",
            "--num-models",
            num_models,
            "--custom-template-path",
            str(template_dir),
            "--pair-mode",
            "unpaired_paired",
            "--stop-at-score",
            "90",
        ]

        subprocess.run(cmd, check=True)


def limpar_gpu() -> None:
    gc.collect()
    if torch is not None and torch.cuda.is_available():
        torch.cuda.empty_cache()


class CropTarget(Select):
    def accept_residue(self, residue):
        chain = residue.get_parent().id
        return 1 if chain in ["A", "B"] else 0


if NUM_RODADAS_REFINAMENTO <= 0:
    print("Nenhuma rodada de refinamento foi solicitada.")
else:
    if not SEED_AF2_DIR.exists():
        raise FileNotFoundError(f"Diretorio inicial nao encontrado: {SEED_AF2_DIR}")

    if "melhor_estrutura_inicial" in globals():
        seed_design_dir = resolver_pasta_colabfold(str(melhor_estrutura_inicial), SEED_AF2_DIR)
    else:
        seed_df = carregar_ranking_af2(SEED_AF2_DIR, tamanho_fragmento=31)
        seed_design_dir = resolver_pasta_colabfold(seed_df.iloc[0]["Candidato"], SEED_AF2_DIR)

    current_template_pdb = localizar_pdb_rank_001(seed_design_dir)
    round_summary = []
    previous_best_binder_iptm = None

    print(f"Iniciando refinamento iterativo com {NUM_RODADAS_REFINAMENTO} rodada(s)...")
    print(f"Template inicial: {current_template_pdb}")

    for round_idx in range(1, NUM_RODADAS_REFINAMENTO + 1):
        round_dir = REFINEMENT_ROOT / f"round_{round_idx:02d}"
        preparar_diretorio_limpo(round_dir)

        crop_dir = round_dir / "cropped"
        design_dir = round_dir / "rfd3_designs"
        pdb_dir = round_dir / "rfd3_pdb"
        filtered_pdb_dir = round_dir / "rfd3_pdb_filtered"
        mpnn_output_base = round_dir / "mpnn_sequences"
        af2_input_dir = round_dir / "af2_inputs_multimer"
        af2_output_dir = round_dir / "af2_predictions_multimer"

        for path in [crop_dir, design_dir, pdb_dir, filtered_pdb_dir, mpnn_output_base, af2_input_dir, af2_output_dir]:
            path.mkdir(parents=True, exist_ok=True)

        print(f"\n=== Rodada {round_idx}/{NUM_RODADAS_REFINAMENTO} ===")
        print(f"Usando como template: {current_template_pdb}")

        parser = PDBParser(QUIET=True)
        io = PDBIO()
        structure = parser.get_structure(f"round_{round_idx}", str(current_template_pdb))
        cropped_pdb_path = crop_dir / f"template_round_{round_idx:02d}.pdb"
        io.set_structure(structure)
        io.save(str(cropped_pdb_path), CropTarget())

        try:
            binder_len = len(list(structure[0]["B"].get_residues()))
        except Exception:
            raise ValueError(f"Nao foi possivel identificar a cadeia B em {current_template_pdb}")

        binder_cadeia = f"{binder_len}-{binder_len}"
        partial_t_rodada = max(PARTIAL_T_MINIMO, PARTIAL_T_INICIAL * (PARTIAL_T_DECAY ** (round_idx - 1)))
        round_config = {
            f"anexina_binder_step2_round_{round_idx:02d}": {
                "dialect": 2,
                "input": str(cropped_pdb_path),
                "contig": f"{alvo_contexto},/0,{binder_cadeia}",
                "partial_t": partial_t_rodada,
                "select_fixed_atoms": select_fixed_atoms,
                "infer_ori_strategy": "hotspots",
                "select_hotspots": select_hotspots,
                "cif_parser_args": {
                    "add_missing_atoms": True,
                },
                "is_non_loopy": True,
            }
        }

        round_json_path = round_dir / "rfd3_input_step2.json"
        with open(round_json_path, "w") as f:
            json.dump(round_config, f, indent=4)

        subprocess.run(
            [
                "bash",
                "-lc",
                f"PYTORCH_ALLOC_CONF=expandable_segments:True rfd3 design out_dir={design_dir} inputs={round_json_path} ckpt_path=/kaggle/working/models/rfd3/rfd3_latest.ckpt diffusion_batch_size=1",
            ],
            check=True,
        )

        converter_cifs_para_pdb(design_dir, pdb_dir)
        filtrar_backbones(design_dir, pdb_dir, filtered_pdb_dir)
        gerar_mpnn(filtered_pdb_dir, mpnn_output_base)
        total_geradas = gerar_af2_inputs(mpnn_output_base, af2_input_dir)

        if total_geradas == 0:
            raise ValueError(f"Nenhum complexo foi gerado na rodada {round_idx}.")

        rodar_colabfold(af2_input_dir, af2_output_dir, filtered_pdb_dir, num_models="2")

        round_df = carregar_ranking_af2(af2_output_dir, tamanho_fragmento=len(fragmento_d40g))
        top_round_df = round_df.head(TOP_K_RESULTADOS_POR_RODADA).copy()
        top_round_df.to_csv(round_dir / "top3_af2.csv", index=False)

        top_round_rows = []
        top_round_pdb_dir = round_dir / "top3_pdbs"
        top_round_pdb_dir.mkdir(parents=True, exist_ok=True)

        for rank_pos, (_, candidate_row) in enumerate(top_round_df.iterrows(), start=1):
            candidate_name = candidate_row["Candidato"]
            candidate_design_dir = resolver_pasta_colabfold(candidate_name, af2_output_dir)
            candidate_pdb = localizar_pdb_rank_001(candidate_design_dir)
            copied_candidate_pdb = top_round_pdb_dir / f"rank_{rank_pos:02d}_{candidate_name}.pdb"
            shutil.copy2(candidate_pdb, copied_candidate_pdb)
            top_round_rows.append(
                {
                    "Rodada": round_idx,
                    "Rank": rank_pos,
                    "Candidato": candidate_name,
                    "ipTM (Afinidade)": candidate_row["ipTM (Afinidade)"],
                    "pLDDT do Binder": candidate_row["pLDDT do Binder"],
                    "pLDDT da Proteina": candidate_row["pLDDT da Proteina"],
                    "pTM Global": candidate_row["pTM Global"],
                    "Template": str(candidate_pdb),
                }
            )

        best_row = top_round_df.iloc[0]
        best_name = best_row["Candidato"]
        best_design_dir = resolver_pasta_colabfold(best_name, af2_output_dir)
        best_pdb = localizar_pdb_rank_001(best_design_dir)

        round_df.to_csv(round_dir / "ranking_af2.csv", index=False)
        shutil.copy2(best_pdb, round_dir / "best_structure_round.pdb")
        round_summary.extend(top_round_rows)

        print(f"Melhor candidato da rodada {round_idx}: {best_name}")
        print(f"Template escolhido para a proxima rodada: {best_pdb}")
        
        best_binder_iptm = float(best_row["ipTM (Afinidade)"])
        #if previous_best_binder_iptm is not None and best_binder_iptm < previous_best_binder_iptm:
            #print(f"Parando: ipTM do binder caiu de {previous_best_binder_iptm:.1f} para {best_binder_iptm:.1f}.")
            #print(f"Parando: ipTM do binder caiu de {previous_best_binder_iptm:.1f} para {best_binder_iptm:.1f}.")
            #current_template_pdb = best_pdb
            #break
        
        previous_best_binder_iptm = best_binder_iptm
        current_template_pdb = best_pdb
        limpar_gpu()

    df_rodadas_refinamento = pd.DataFrame(round_summary)
    df_rodadas_refinamento = df_rodadas_refinamento.sort_values(by=["Rodada", "Rank"])
    melhor_estrutura_final = current_template_pdb

    df_rodadas_refinamento.to_csv(REFINEMENT_ROOT / "resumo_rodadas_refinamento.csv", index=False)
    shutil.copy2(melhor_estrutura_final, REFINEMENT_ROOT / "melhor_estrutura_final.pdb")

    print("\nResumo das rodadas de refinamento:")
    display(df_rodadas_refinamento)
    print(f"\nMelhor estrutura final salva em: {melhor_estrutura_final}")

Iniciando refinamento iterativo com 6 rodada(s)...
Template inicial: /kaggle/working/outputs/af2_predictions_multimer/rfd3_input_anexina_binder_design_0_model_0/rfd3_input_anexina_binder_design_0_model_0_top10_score0.983_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

=== Rodada 1/6 ===
Usando como template: /kaggle/working/outputs/af2_predictions_multimer/rfd3_input_anexina_binder_design_0_model_0/rfd3_input_anexina_binder_design_0_model_0_top10_score0.983_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

/usr/local/lib/python3.12/dist-packages/hydra/_internal/config_loader_impl.py:216: UserWarning: provider=hydra.searchpath in main, path=configs is not available.
  warnings.warn(
Environment variable CCD_MIRROR_PATH not set. Will not be able to use function requiring this variable. To set it you may:
  (1) add the line 'export VAR_NAME=path/to/variable' to your .bashrc or .zshrc file
  (2) set it in your current shell with 'export VAR_NAME=path/to/variable'
  (3) write it to a .env file in the root of the atomworks.io repository
Environment variable PDB_MIRROR_PATH not set. Will not be able to use function requiring this variable. To set it you may:
  (1) add the line 'export VAR_NAME=path/to/variable' to your .bashrc or .zshrc file
  (2) set it in your current shell with 'export VAR_NAME=path/to/variable'
  (3) write it to a .env file in the root of the atomworks.io repository
00:09:32 DEBUG transforms: Debug mode is on
00:09:34 INFO rfd3.engine: [rank: 0] Outputs will be written to /kaggle/working/outputs/level2/refinement_rounds/round_01/rfd3_designs.
00:09:34 INFO rfd3.engine: [rank: 0] Found 0 existing example IDs in the output directory (0 total).
Using bfloat16 Automatic Mixed Precision (AMP)
00:09:44 WARNING atomworks.io: We can't fix formal charges without building from templates, as we need to know the true number of hydrogens bonded to a given atom, not the inferred number. This may lead to occasional inaccuracies after adding inter-residue bonds. To avoid this and fix formal charges, set `add_missing_atoms = True`.
00:09:45 WARNING atomworks.io: The `extra_fields` argument will be ignored if there is no CIF file input.
00:09:53 INFO rfd3.engine: [rank: 0] Finished inference batch in 8.24 seconds.
00:09:53 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_step2_anexina_binder_step2_round_01_0_model_0 written to /kaggle/working/outputs/level2/refinement_rounds/round_01/rfd3_designs/rfd3_input_step2_anexina_binder_step2_round_01_0_model_0.

✓ Convertido com sucesso: rfd3_input_step2_anexina_binder_step2_round_01_0_model_0.pdb
Iniciando a filtragem rigorosa de backbones...
Filtragem concluida!
✓ Total avaliados: 1
✓ Total no filtro estrito (fracao >= 0.30 e clashes <= 0): 1
🏆 Aprovados e enviados para o MPNN (Top 10): 1
Desenhando sequencias para o backbone: rfd3_input_step2_anexina_binder_step2_round_01_0_model_0
Filtrando e formatando complexos para o AlphaFold Multimer...
✓ Pronto! 10 complexos organizados para validacao do fragmento.
Validando sequencias do design: rfd3_input_step2_anexina_binder_step2_round_01_0_model_0

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-16 00:11:21,314 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-16 00:11:22,084 Running on GPU
2026-08-16 00:11:22,346 Found 5 citations for tools or databases
2026-08-16 00:11:22,391 Query 1/10: rfd3_input_step2_anexina_binder_step2_round_01_0_model_0_top10_score0.778 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:15 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:11:23,072 Sleeping for 8s. Reason: PENDING
2026-08-16 00:11:31,391 Sleeping for 6s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-16 00:11:38,378 Sleeping for 6s. Reason: PENDING
2026-08-16 00:12:30,696 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.2 pTM=0.737 ipTM=0.264
2026-08-16 00:13:06,365 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.4 pTM=0.724 ipTM=0.224 tol=0.906
2026-08-16 00:13:13,191 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.2 pTM=0.745 ipTM=0.285 tol=0.929
2026-08-16 00:13:20,089 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=78.5 pTM=0.734 ipTM=0.268 tol=0.496
2026-08-16 00:13:20,090 alphafold2_multimer_v3_model_1_seed_000 took 87.4s (3 recycles)
2026-08-16 00:13:27,079 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=77.5 pTM=0.706 ipTM=0.208
2026-08-16 00:13:34,077 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=77.9 pTM=0.706 ipTM=0.221 tol=1.41
2026-08-16 00:13:41,099 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78 pTM=0.713 ipTM=0.267 tol=0.323
2026-08-16 00:13:41,099 alphafold2_multimer_v3_model_2_seed_000 took 21.0s (2 recycles)
2026-08-16 00:13:41,109 reranking models by 'multimer' metric
2026-08-16 00:13:41,109 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=78.5 pTM=0.734 ipTM=0.268 ipSAE=0.0189 pDockQ2=0.0405
2026-08-16 00:13:41,109 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78 pTM=0.713 ipTM=0.267 ipSAE=0.0231 pDockQ2=0.0391
2026-08-16 00:13:41,788 Query 2/10: rfd3_input_step2_anexina_binder_step2_round_01_0_model_0_top1_score0.761 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:13:42,108 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-16 00:13:51,073 Sleeping for 6s. Reason: PENDING
2026-08-16 00:14:05,238 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.4 pTM=0.71 ipTM=0.248
2026-08-16 00:14:12,237 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.1 pTM=0.719 ipTM=0.282 tol=1.12
2026-08-16 00:14:19,295 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.4 pTM=0.738 ipTM=0.346 tol=0.432
2026-08-16 00:14:19,295 alphafold2_multimer_v3_model_1_seed_000 took 21.1s (2 recycles)
2026-08-16 00:14:26,439 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=76.7 pTM=0.692 ipTM=0.248
2026-08-16 00:14:33,634 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=78.8 pTM=0.725 ipTM=0.349 tol=1.92
2026-08-16 00:14:40,845 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78.8 pTM=0.723 ipTM=0.344 tol=0.549
2026-08-16 00:14:48,048 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=78.9 pTM=0.722 ipTM=0.33 tol=0.188
2026-08-16 00:14:48,048 alphafold2_multimer_v3_model_2_seed_000 took 28.7s (3 recycles)
2026-08-16 00:14:48,058 reranking models by 'multimer' metric
2026-08-16 00:14:48,058 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.4 pTM=0.738 ipTM=0.346 ipSAE=0.0811 pDockQ2=0.0636
2026-08-16 00:14:48,058 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.9 pTM=0.722 ipTM=0.33 ipSAE=0.0483 pDockQ2=0.073
2026-08-16 00:14:48,563 Query 3/10: rfd3_input_step2_anexina_binder_step2_round_01_0_model_0_top2_score0.752 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:14:48,913 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-16 00:14:58,931 Sleeping for 8s. Reason: PENDING
2026-08-16 00:15:15,128 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=76.4 pTM=0.72 ipTM=0.205
2026-08-16 00:15:22,175 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=76.2 pTM=0.717 ipTM=0.202 tol=2.08
2026-08-16 00:15:29,375 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=76.8 pTM=0.729 ipTM=0.235 tol=0.559
2026-08-16 00:15:36,675 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=77 pTM=0.731 ipTM=0.259 tol=0.691
2026-08-16 00:15:36,675 alphafold2_multimer_v3_model_1_seed_000 took 28.7s (3 recycles)
2026-08-16 00:15:44,079 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=76.5 pTM=0.712 ipTM=0.218
2026-08-16 00:15:51,389 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=77.7 pTM=0.722 ipTM=0.272 tol=1.62
2026-08-16 00:15:58,550 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=77.8 pTM=0.724 ipTM=0.276 tol=0.214
2026-08-16 00:15:58,551 alphafold2_multimer_v3_model_2_seed_000 took 21.9s (2 recycles)
2026-08-16 00:15:58,561 reranking models by 'multimer' metric
2026-08-16 00:15:58,561 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=77.8 pTM=0.724 ipTM=0.276 ipSAE=0.0229 pDockQ2=0.0412
2026-08-16 00:15:58,561 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=77 pTM=0.731 ipTM=0.259 ipSAE=0.0164 pDockQ2=0.0283
2026-08-16 00:15:59,077 Query 4/10: rfd3_input_step2_anexina_binder_step2_round_01_0_model_0_top3_score0.761 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:15:59,459 Sleeping for 6s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]

2026-08-16 00:16:06,473 Sleeping for 10s. Reason: PENDING
2026-08-16 00:16:24,631 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.8 pTM=0.745 ipTM=0.342
2026-08-16 00:16:31,632 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.5 pTM=0.731 ipTM=0.308 tol=1.03
2026-08-16 00:16:38,735 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.3 pTM=0.754 ipTM=0.376 tol=0.835
2026-08-16 00:16:45,976 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.8 pTM=0.742 ipTM=0.355 tol=0.388
2026-08-16 00:16:45,977 alphafold2_multimer_v3_model_1_seed_000 took 28.4s (3 recycles)
2026-08-16 00:16:53,333 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=75.1 pTM=0.695 ipTM=0.224
2026-08-16 00:17:00,696 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=77.8 pTM=0.724 ipTM=0.304 tol=2.84
2026-08-16 00:17:07,934 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=77.8 pTM=0.721 ipTM=0.284 tol=0.888
2026-08-16 00:17:15,066 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=77.8 pTM=0.723 ipTM=0.301 tol=0.706
2026-08-16 00:17:15,066 alphafold2_multimer_v3_model_2_seed_000 took 29.1s (3 recycles)
2026-08-16 00:17:15,076 reranking models by 'multimer' metric
2026-08-16 00:17:15,076 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.8 pTM=0.742 ipTM=0.355 ipSAE=0.106 pDockQ2=0.142
2026-08-16 00:17:15,077 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=77.8 pTM=0.723 ipTM=0.301 ipSAE=0.0347 pDockQ2=0.0554
2026-08-16 00:17:15,583 Query 5/10: rfd3_input_step2_anexina_binder_step2_round_01_0_model_0_top4_score0.756 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:14 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:17:15,923 Sleeping for 6s. Reason: PENDING
2026-08-16 00:17:22,244 Sleeping for 7s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-16 00:17:30,245 Sleeping for 9s. Reason: PENDING
2026-08-16 00:17:47,340 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=76.8 pTM=0.709 ipTM=0.215
2026-08-16 00:17:54,357 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=77.3 pTM=0.717 ipTM=0.234 tol=1.45
2026-08-16 00:18:01,496 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=78.5 pTM=0.732 ipTM=0.292 tol=0.45
2026-08-16 00:18:01,497 alphafold2_multimer_v3_model_1_seed_000 took 21.2s (2 recycles)
2026-08-16 00:18:08,769 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=76.8 pTM=0.699 ipTM=0.235
2026-08-16 00:18:16,131 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=78.5 pTM=0.725 ipTM=0.312 tol=1.35
2026-08-16 00:18:23,443 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78.1 pTM=0.72 ipTM=0.295 tol=0.619
2026-08-16 00:18:30,641 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=78.2 pTM=0.72 ipTM=0.291 tol=0.356
2026-08-16 00:18:30,641 alphafold2_multimer_v3_model_2_seed_000 took 29.1s (3 recycles)
2026-08-16 00:18:30,651 reranking models by 'multimer' metric
2026-08-16 00:18:30,652 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=78.5 pTM=0.732 ipTM=0.292 ipSAE=0.0414 pDockQ2=0.0462
2026-08-16 00:18:30,652 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.2 pTM=0.72 ipTM=0.291 ipSAE=0.0285 pDockQ2=0.0557
2026-08-16 00:18:31,183 Query 6/10: rfd3_input_step2_anexina_binder_step2_round_01_0_model_0_top5_score0.760 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:18:31,500 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-16 00:18:41,506 Sleeping for 7s. Reason: PENDING
2026-08-16 00:18:56,704 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79.3 pTM=0.751 ipTM=0.318
2026-08-16 00:19:03,742 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.2 pTM=0.759 ipTM=0.325 tol=0.687
2026-08-16 00:19:10,879 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.2 pTM=0.762 ipTM=0.331 tol=0.212
2026-08-16 00:19:10,880 alphafold2_multimer_v3_model_1_seed_000 took 21.3s (2 recycles)
2026-08-16 00:19:18,154 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=78 pTM=0.726 ipTM=0.278
2026-08-16 00:19:25,508 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=79.8 pTM=0.751 ipTM=0.34 tol=0.803
2026-08-16 00:19:32,848 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=79.7 pTM=0.751 ipTM=0.338 tol=0.242
2026-08-16 00:19:32,849 alphafold2_multimer_v3_model_2_seed_000 took 22.0s (2 recycles)
2026-08-16 00:19:32,859 reranking models by 'multimer' metric
2026-08-16 00:19:32,859 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=79.7 pTM=0.751 ipTM=0.338 ipSAE=0.0478 pDockQ2=0.0405
2026-08-16 00:19:32,859 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.2 pTM=0.762 ipTM=0.331 ipSAE=0.0351 pDockQ2=0.0417
2026-08-16 00:19:33,358 Query 7/10: rfd3_input_step2_anexina_binder_step2_round_01_0_model_0_top6_score0.774 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:19:33,700 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-16 00:19:43,689 Sleeping for 10s. Reason: PENDING
2026-08-16 00:20:01,803 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=76.7 pTM=0.725 ipTM=0.26
2026-08-16 00:20:08,866 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.4 pTM=0.736 ipTM=0.291 tol=1.2
2026-08-16 00:20:16,058 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=77.7 pTM=0.733 ipTM=0.269 tol=0.562
2026-08-16 00:20:23,363 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=77.2 pTM=0.729 ipTM=0.267 tol=0.325
2026-08-16 00:20:23,364 alphafold2_multimer_v3_model_1_seed_000 took 28.6s (3 recycles)
2026-08-16 00:20:30,754 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=76 pTM=0.711 ipTM=0.272
2026-08-16 00:20:38,064 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=77.6 pTM=0.724 ipTM=0.279 tol=1.27
2026-08-16 00:20:45,236 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=77.8 pTM=0.73 ipTM=0.311 tol=0.592
2026-08-16 00:20:52,304 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=77.9 pTM=0.727 ipTM=0.306 tol=0.223
2026-08-16 00:20:52,304 alphafold2_multimer_v3_model_2_seed_000 took 28.9s (3 recycles)
2026-08-16 00:20:52,314 reranking models by 'multimer' metric
2026-08-16 00:20:52,314 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=77.9 pTM=0.727 ipTM=0.306 ipSAE=0.0423 pDockQ2=0.0594
2026-08-16 00:20:52,314 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=77.2 pTM=0.729 ipTM=0.267 ipSAE=0.0281 pDockQ2=0.0324
2026-08-16 00:20:52,822 Query 8/10: rfd3_input_step2_anexina_binder_step2_round_01_0_model_0_top7_score0.777 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:12 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:20:53,163 Sleeping for 5s. Reason: PENDING
2026-08-16 00:20:58,490 Sleeping for 6s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-16 00:21:05,486 Sleeping for 8s. Reason: PENDING
2026-08-16 00:21:21,613 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=76.5 pTM=0.718 ipTM=0.228
2026-08-16 00:21:28,618 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=76.9 pTM=0.725 ipTM=0.225 tol=1.74
2026-08-16 00:21:35,725 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=77.2 pTM=0.733 ipTM=0.239 tol=0.306
2026-08-16 00:21:35,726 alphafold2_multimer_v3_model_1_seed_000 took 21.2s (2 recycles)
2026-08-16 00:21:42,983 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=76.8 pTM=0.71 ipTM=0.227
2026-08-16 00:21:50,353 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=78 pTM=0.724 ipTM=0.261 tol=1.89
2026-08-16 00:21:57,705 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78.2 pTM=0.728 ipTM=0.274 tol=0.375
2026-08-16 00:21:57,706 alphafold2_multimer_v3_model_2_seed_000 took 22.0s (2 recycles)
2026-08-16 00:21:57,715 reranking models by 'multimer' metric
2026-08-16 00:21:57,716 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.2 pTM=0.728 ipTM=0.274 ipSAE=0.0185 pDockQ2=0.0538
2026-08-16 00:21:57,716 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=77.2 pTM=0.733 ipTM=0.239 ipSAE=0.0145 pDockQ2=0.0309
2026-08-16 00:21:58,239 Query 9/10: rfd3_input_step2_anexina_binder_step2_round_01_0_model_0_top8_score0.790 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:21:58,574 Sleeping for 5s. Reason: PENDING
2026-08-16 00:22:03,909 Sleeping for 5s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-16 00:22:09,945 Sleeping for 7s. Reason: PENDING
2026-08-16 00:22:25,153 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.7 pTM=0.727 ipTM=0.238
2026-08-16 00:22:32,233 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=77.2 pTM=0.727 ipTM=0.251 tol=1.8
2026-08-16 00:22:39,444 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=78.2 pTM=0.736 ipTM=0.288 tol=0.548
2026-08-16 00:22:46,775 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=77.5 pTM=0.729 ipTM=0.272 tol=0.443
2026-08-16 00:22:46,776 alphafold2_multimer_v3_model_1_seed_000 took 28.8s (3 recycles)
2026-08-16 00:22:54,167 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=77.9 pTM=0.727 ipTM=0.26
2026-08-16 00:23:01,447 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=78.3 pTM=0.719 ipTM=0.257 tol=1.15
2026-08-16 00:23:08,598 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78.5 pTM=0.724 ipTM=0.278 tol=0.4
2026-08-16 00:23:08,598 alphafold2_multimer_v3_model_2_seed_000 took 21.8s (2 recycles)
2026-08-16 00:23:08,609 reranking models by 'multimer' metric
2026-08-16 00:23:08,609 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.5 pTM=0.724 ipTM=0.278 ipSAE=0.0256 pDockQ2=0.0626
2026-08-16 00:23:08,609 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=77.5 pTM=0.729 ipTM=0.272 ipSAE=0.0154 pDockQ2=0.0333
2026-08-16 00:23:09,129 Query 10/10: rfd3_input_step2_anexina_binder_step2_round_01_0_model_0_top9_score0.779 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:23:09,471 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-16 00:23:19,480 Sleeping for 5s. Reason: PENDING
2026-08-16 00:23:32,868 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=76.2 pTM=0.722 ipTM=0.264
2026-08-16 00:23:39,873 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=76.3 pTM=0.709 ipTM=0.236 tol=1.38
2026-08-16 00:23:46,956 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=78.2 pTM=0.727 ipTM=0.289 tol=1.39
2026-08-16 00:23:54,162 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=78.3 pTM=0.729 ipTM=0.307 tol=0.483
2026-08-16 00:23:54,162 alphafold2_multimer_v3_model_1_seed_000 took 28.4s (3 recycles)
2026-08-16 00:24:01,499 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=73.9 pTM=0.685 ipTM=0.238
2026-08-16 00:24:08,854 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=75.1 pTM=0.692 ipTM=0.234 tol=1.11
2026-08-16 00:24:16,111 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=76.1 pTM=0.701 ipTM=0.265 tol=1.16
2026-08-16 00:24:23,244 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=76.4 pTM=0.7 ipTM=0.278 tol=0.578
2026-08-16 00:24:23,245 alphafold2_multimer_v3_model_2_seed_000 took 29.1s (3 recycles)
2026-08-16 00:24:23,255 reranking models by 'multimer' metric
2026-08-16 00:24:23,255 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=78.3 pTM=0.729 ipTM=0.307 ipSAE=0.0449 pDockQ2=0.0432
2026-08-16 00:24:23,255 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=76.4 pTM=0.7 ipTM=0.278 ipSAE=0.0337 pDockQ2=0.0564
2026-08-16 00:24:23,772 Done
Melhor candidato da rodada 1: rfd3_input_step2_anexina_binder_step2_round_01_0_model_0_top3_score0.761
Template escolhido para a proxima rodada: /kaggle/working/outputs/level2/refinement_rounds/round_01/af2_predictions_multimer/rfd3_input_step2_anexina_binder_step2_round_01_0_model_0/rfd3_input_step2_anexina_binder_step2_round_01_0_model_0_top10_score0.778_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

=== Rodada 2/6 ===
Usando como template: /kaggle/working/outputs/level2/refinement_rounds/round_01/af2_predictions_multimer/rfd3_input_step2_anexina_binder_step2_round_01_0_model_0/rfd3_input_step2_anexina_binder_step2_round_01_0_model_0_top10_score0.778_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

/usr/local/lib/python3.12/dist-packages/hydra/_internal/config_loader_impl.py:216: UserWarning: provider=hydra.searchpath in main, path=configs is not available.
  warnings.warn(
Environment variable CCD_MIRROR_PATH not set. Will not be able to use function requiring this variable. To set it you may:
  (1) add the line 'export VAR_NAME=path/to/variable' to your .bashrc or .zshrc file
  (2) set it in your current shell with 'export VAR_NAME=path/to/variable'
  (3) write it to a .env file in the root of the atomworks.io repository
Environment variable PDB_MIRROR_PATH not set. Will not be able to use function requiring this variable. To set it you may:
  (1) add the line 'export VAR_NAME=path/to/variable' to your .bashrc or .zshrc file
  (2) set it in your current shell with 'export VAR_NAME=path/to/variable'
  (3) write it to a .env file in the root of the atomworks.io repository
00:24:34 DEBUG transforms: Debug mode is on
00:24:36 INFO rfd3.engine: [rank: 0] Outputs will be written to /kaggle/working/outputs/level2/refinement_rounds/round_02/rfd3_designs.
00:24:36 INFO rfd3.engine: [rank: 0] Found 0 existing example IDs in the output directory (0 total).
Using bfloat16 Automatic Mixed Precision (AMP)
00:24:45 WARNING atomworks.io: We can't fix formal charges without building from templates, as we need to know the true number of hydrogens bonded to a given atom, not the inferred number. This may lead to occasional inaccuracies after adding inter-residue bonds. To avoid this and fix formal charges, set `add_missing_atoms = True`.
00:24:46 WARNING atomworks.io: The `extra_fields` argument will be ignored if there is no CIF file input.
00:24:54 INFO rfd3.engine: [rank: 0] Finished inference batch in 8.48 seconds.
00:24:54 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_step2_anexina_binder_step2_round_02_0_model_0 written to /kaggle/working/outputs/level2/refinement_rounds/round_02/rfd3_designs/rfd3_input_step2_anexina_binder_step2_round_02_0_model_0.

✓ Convertido com sucesso: rfd3_input_step2_anexina_binder_step2_round_02_0_model_0.pdb
Iniciando a filtragem rigorosa de backbones...
Filtragem concluida!
✓ Total avaliados: 1
✓ Total no filtro estrito (fracao >= 0.30 e clashes <= 0): 1
🏆 Aprovados e enviados para o MPNN (Top 10): 1
Desenhando sequencias para o backbone: rfd3_input_step2_anexina_binder_step2_round_02_0_model_0
Filtrando e formatando complexos para o AlphaFold Multimer...
✓ Pronto! 10 complexos organizados para validacao do fragmento.
Validando sequencias do design: rfd3_input_step2_anexina_binder_step2_round_02_0_model_0

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-16 00:26:38,777 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-16 00:26:39,476 Running on GPU
2026-08-16 00:26:39,736 Found 5 citations for tools or databases
2026-08-16 00:26:39,796 Query 1/10: rfd3_input_step2_anexina_binder_step2_round_02_0_model_0_top10_score0.858 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:26:40,482 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-16 00:26:51,504 Sleeping for 8s. Reason: PENDING
2026-08-16 00:27:46,056 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.7 pTM=0.769 ipTM=0.359
2026-08-16 00:28:22,108 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.5 pTM=0.799 ipTM=0.468 tol=2.21
2026-08-16 00:28:29,076 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.8 pTM=0.801 ipTM=0.477 tol=0.941
2026-08-16 00:28:36,104 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=80 pTM=0.783 ipTM=0.404 tol=0.609
2026-08-16 00:28:36,104 alphafold2_multimer_v3_model_1_seed_000 took 88.3s (3 recycles)
2026-08-16 00:28:43,186 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=81.6 pTM=0.774 ipTM=0.427
2026-08-16 00:28:50,361 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=86.2 pTM=0.815 ipTM=0.585 tol=0.778
2026-08-16 00:28:57,637 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=86.9 pTM=0.822 ipTM=0.621 tol=0.233
2026-08-16 00:28:57,638 alphafold2_multimer_v3_model_2_seed_000 took 21.5s (2 recycles)
2026-08-16 00:28:57,648 reranking models by 'multimer' metric
2026-08-16 00:28:57,648 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=86.9 pTM=0.822 ipTM=0.621 ipSAE=0.432 pDockQ2=0.337
2026-08-16 00:28:57,648 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80 pTM=0.783 ipTM=0.404 ipSAE=0.126 pDockQ2=0.151
2026-08-16 00:28:58,158 Query 2/10: rfd3_input_step2_anexina_binder_step2_round_02_0_model_0_top1_score0.778 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:14 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:28:58,482 Sleeping for 6s. Reason: PENDING
2026-08-16 00:29:04,798 Sleeping for 7s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-16 00:29:12,817 Sleeping for 10s. Reason: PENDING
2026-08-16 00:29:31,083 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.5 pTM=0.75 ipTM=0.299
2026-08-16 00:29:38,269 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.7 pTM=0.771 ipTM=0.37 tol=1.61
2026-08-16 00:29:45,517 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=82.1 pTM=0.779 ipTM=0.394 tol=0.786
2026-08-16 00:29:52,783 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=82 pTM=0.779 ipTM=0.395 tol=0.427
2026-08-16 00:29:52,783 alphafold2_multimer_v3_model_1_seed_000 took 28.9s (3 recycles)
2026-08-16 00:30:00,098 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=77.8 pTM=0.745 ipTM=0.327
2026-08-16 00:30:07,413 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=76.1 pTM=0.711 ipTM=0.271 tol=2.45
2026-08-16 00:30:14,692 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=85.7 pTM=0.803 ipTM=0.601 tol=5.14
2026-08-16 00:30:21,903 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=86.5 pTM=0.805 ipTM=0.637 tol=0.36
2026-08-16 00:30:21,903 alphafold2_multimer_v3_model_2_seed_000 took 29.1s (3 recycles)
2026-08-16 00:30:21,913 reranking models by 'multimer' metric
2026-08-16 00:30:21,914 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=86.5 pTM=0.805 ipTM=0.637 ipSAE=0.397 pDockQ2=0.425
2026-08-16 00:30:21,914 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82 pTM=0.779 ipTM=0.395 ipSAE=0.124 pDockQ2=0.0789
2026-08-16 00:30:22,419 Query 3/10: rfd3_input_step2_anexina_binder_step2_round_02_0_model_0_top2_score0.800 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:30:22,770 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-16 00:30:33,802 Sleeping for 7s. Reason: PENDING
2026-08-16 00:30:49,034 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79.5 pTM=0.77 ipTM=0.358
2026-08-16 00:30:56,178 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79.2 pTM=0.764 ipTM=0.328 tol=1.29
2026-08-16 00:31:03,466 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.4 pTM=0.762 ipTM=0.319 tol=0.791
2026-08-16 00:31:10,890 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=80.1 pTM=0.765 ipTM=0.33 tol=0.539
2026-08-16 00:31:10,890 alphafold2_multimer_v3_model_1_seed_000 took 29.0s (3 recycles)
2026-08-16 00:31:18,433 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=79.8 pTM=0.767 ipTM=0.359
2026-08-16 00:31:25,878 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=79.4 pTM=0.754 ipTM=0.32 tol=1.2
2026-08-16 00:31:33,165 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=79.8 pTM=0.76 ipTM=0.343 tol=0.242
2026-08-16 00:31:33,166 alphafold2_multimer_v3_model_2_seed_000 took 22.3s (2 recycles)
2026-08-16 00:31:33,176 reranking models by 'multimer' metric
2026-08-16 00:31:33,176 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=79.8 pTM=0.76 ipTM=0.343 ipSAE=0.0724 pDockQ2=0.0614
2026-08-16 00:31:33,176 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.1 pTM=0.765 ipTM=0.33 ipSAE=0.0737 pDockQ2=0.0908
2026-08-16 00:31:33,696 Query 4/10: rfd3_input_step2_anexina_binder_step2_round_02_0_model_0_top3_score0.833 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:31:34,032 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-16 00:31:42,022 Sleeping for 5s. Reason: PENDING
2026-08-16 00:31:55,252 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.8 pTM=0.759 ipTM=0.326
2026-08-16 00:32:02,346 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79.8 pTM=0.763 ipTM=0.33 tol=0.785
2026-08-16 00:32:09,599 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.6 pTM=0.787 ipTM=0.415 tol=0.389
2026-08-16 00:32:09,600 alphafold2_multimer_v3_model_1_seed_000 took 21.5s (2 recycles)
2026-08-16 00:32:16,984 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=81 pTM=0.777 ipTM=0.421
2026-08-16 00:32:24,456 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=80.1 pTM=0.763 ipTM=0.387 tol=0.663
2026-08-16 00:32:31,945 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78 pTM=0.748 ipTM=0.35 tol=0.347
2026-08-16 00:32:31,945 alphafold2_multimer_v3_model_2_seed_000 took 22.3s (2 recycles)
2026-08-16 00:32:31,956 reranking models by 'multimer' metric
2026-08-16 00:32:31,956 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=81.6 pTM=0.787 ipTM=0.415 ipSAE=0.136 pDockQ2=0.102
2026-08-16 00:32:31,956 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78 pTM=0.748 ipTM=0.35 ipSAE=0.0777 pDockQ2=0.0614
2026-08-16 00:32:32,462 Query 5/10: rfd3_input_step2_anexina_binder_step2_round_02_0_model_0_top4_score0.815 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:15 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:32:32,817 Sleeping for 6s. Reason: PENDING
2026-08-16 00:32:39,147 Sleeping for 8s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-16 00:32:48,155 Sleeping for 9s. Reason: PENDING
2026-08-16 00:33:05,453 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=81.9 pTM=0.795 ipTM=0.472
2026-08-16 00:33:12,652 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.1 pTM=0.822 ipTM=0.561 tol=0.879
2026-08-16 00:33:19,987 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.9 pTM=0.829 ipTM=0.658 tol=0.395
2026-08-16 00:33:19,987 alphafold2_multimer_v3_model_1_seed_000 took 21.7s (2 recycles)
2026-08-16 00:33:27,470 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=75.9 pTM=0.727 ipTM=0.266
2026-08-16 00:33:34,973 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=79.4 pTM=0.756 ipTM=0.371 tol=0.697
2026-08-16 00:33:42,330 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=79.2 pTM=0.756 ipTM=0.375 tol=0.164
2026-08-16 00:33:42,331 alphafold2_multimer_v3_model_2_seed_000 took 22.3s (2 recycles)
2026-08-16 00:33:42,340 reranking models by 'multimer' metric
2026-08-16 00:33:42,340 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.9 pTM=0.829 ipTM=0.658 ipSAE=0.448 pDockQ2=0.252
2026-08-16 00:33:42,340 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=79.2 pTM=0.756 ipTM=0.375 ipSAE=0.0835 pDockQ2=0.0625
2026-08-16 00:33:42,846 Query 6/10: rfd3_input_step2_anexina_binder_step2_round_02_0_model_0_top5_score0.830 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:33:43,153 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-16 00:33:52,056 Sleeping for 10s. Reason: PENDING
2026-08-16 00:34:10,184 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=80.9 pTM=0.782 ipTM=0.414
2026-08-16 00:34:17,302 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.6 pTM=0.794 ipTM=0.473 tol=1.29
2026-08-16 00:34:24,565 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.2 pTM=0.778 ipTM=0.394 tol=1.69
2026-08-16 00:34:31,966 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.9 pTM=0.766 ipTM=0.349 tol=0.432
2026-08-16 00:34:31,967 alphafold2_multimer_v3_model_1_seed_000 took 28.9s (3 recycles)
2026-08-16 00:34:39,486 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=79.4 pTM=0.762 ipTM=0.369
2026-08-16 00:34:46,954 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=78.8 pTM=0.727 ipTM=0.281 tol=1.1
2026-08-16 00:34:54,268 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=79.4 pTM=0.747 ipTM=0.357 tol=0.768
2026-08-16 00:35:01,479 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=78.4 pTM=0.727 ipTM=0.286 tol=0.979
2026-08-16 00:35:01,479 alphafold2_multimer_v3_model_2_seed_000 took 29.5s (3 recycles)
2026-08-16 00:35:01,489 reranking models by 'multimer' metric
2026-08-16 00:35:01,489 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.9 pTM=0.766 ipTM=0.349 ipSAE=0.112 pDockQ2=0.1
2026-08-16 00:35:01,489 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.4 pTM=0.727 ipTM=0.286 ipSAE=0.0448 pDockQ2=0.0499
2026-08-16 00:35:01,996 Query 7/10: rfd3_input_step2_anexina_binder_step2_round_02_0_model_0_top6_score0.840 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:19 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:35:02,294 Sleeping for 9s. Reason: PENDING
2026-08-16 00:35:11,579 Sleeping for 9s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-16 00:35:21,487 Sleeping for 7s. Reason: PENDING
2026-08-16 00:35:36,715 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.6 pTM=0.747 ipTM=0.279
2026-08-16 00:35:43,834 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=75.1 pTM=0.731 ipTM=0.202 tol=5.64
2026-08-16 00:35:51,073 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.4 pTM=0.79 ipTM=0.416 tol=1.37
2026-08-16 00:35:58,433 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=83.6 pTM=0.804 ipTM=0.476 tol=0.7
2026-08-16 00:35:58,433 alphafold2_multimer_v3_model_1_seed_000 took 28.8s (3 recycles)
2026-08-16 00:36:05,933 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=77.4 pTM=0.749 ipTM=0.297
2026-08-16 00:36:13,433 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=85.5 pTM=0.819 ipTM=0.657 tol=2.26
2026-08-16 00:36:20,766 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=83.4 pTM=0.792 ipTM=0.532 tol=0.871
2026-08-16 00:36:28,007 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=83.2 pTM=0.792 ipTM=0.499 tol=0.382
2026-08-16 00:36:28,008 alphafold2_multimer_v3_model_2_seed_000 took 29.6s (3 recycles)
2026-08-16 00:36:28,018 reranking models by 'multimer' metric
2026-08-16 00:36:28,018 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=83.2 pTM=0.792 ipTM=0.499 ipSAE=0.268 pDockQ2=0.187
2026-08-16 00:36:28,018 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.6 pTM=0.804 ipTM=0.476 ipSAE=0.201 pDockQ2=0.151
2026-08-16 00:36:28,526 Query 8/10: rfd3_input_step2_anexina_binder_step2_round_02_0_model_0_top7_score0.855 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:36:28,873 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-16 00:36:39,897 Sleeping for 10s. Reason: PENDING
2026-08-16 00:36:58,135 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=75.4 pTM=0.726 ipTM=0.206
2026-08-16 00:37:05,247 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.5 pTM=0.828 ipTM=0.631 tol=6.17
2026-08-16 00:37:12,486 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=82.2 pTM=0.792 ipTM=0.452 tol=0.667
2026-08-16 00:37:19,855 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85.1 pTM=0.822 ipTM=0.597 tol=0.458
2026-08-16 00:37:19,855 alphafold2_multimer_v3_model_1_seed_000 took 28.9s (3 recycles)
2026-08-16 00:37:27,372 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=75.6 pTM=0.726 ipTM=0.228
2026-08-16 00:37:34,840 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=77.4 pTM=0.733 ipTM=0.253 tol=0.796
2026-08-16 00:37:42,178 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=79 pTM=0.762 ipTM=0.359 tol=0.542
2026-08-16 00:37:49,397 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=78.8 pTM=0.746 ipTM=0.302 tol=0.787
2026-08-16 00:37:49,398 alphafold2_multimer_v3_model_2_seed_000 took 29.5s (3 recycles)
2026-08-16 00:37:49,408 reranking models by 'multimer' metric
2026-08-16 00:37:49,408 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.1 pTM=0.822 ipTM=0.597 ipSAE=0.391 pDockQ2=0.238
2026-08-16 00:37:49,408 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.8 pTM=0.746 ipTM=0.302 ipSAE=0.0677 pDockQ2=0.0697
2026-08-16 00:37:50,140 Query 9/10: rfd3_input_step2_anexina_binder_step2_round_02_0_model_0_top8_score0.846 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:37:50,482 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]

2026-08-16 00:38:01,514 Sleeping for 10s. Reason: PENDING
2026-08-16 00:38:20,056 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=75.6 pTM=0.737 ipTM=0.23
2026-08-16 00:38:27,164 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=76.8 pTM=0.74 ipTM=0.236 tol=2.57
2026-08-16 00:38:34,400 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=77.9 pTM=0.755 ipTM=0.281 tol=1.3
2026-08-16 00:38:41,791 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=77.1 pTM=0.745 ipTM=0.247 tol=0.957
2026-08-16 00:38:41,792 alphafold2_multimer_v3_model_1_seed_000 took 28.9s (3 recycles)
2026-08-16 00:38:49,309 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=76.2 pTM=0.729 ipTM=0.229
2026-08-16 00:38:56,763 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=80.2 pTM=0.754 ipTM=0.347 tol=1.13
2026-08-16 00:39:04,082 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=80 pTM=0.755 ipTM=0.342 tol=0.913
2026-08-16 00:39:11,288 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=78.9 pTM=0.741 ipTM=0.302 tol=0.507
2026-08-16 00:39:11,289 alphafold2_multimer_v3_model_2_seed_000 took 29.5s (3 recycles)
2026-08-16 00:39:11,299 reranking models by 'multimer' metric
2026-08-16 00:39:11,299 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.9 pTM=0.741 ipTM=0.302 ipSAE=0.0501 pDockQ2=0.045
2026-08-16 00:39:11,299 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=77.1 pTM=0.745 ipTM=0.247 ipSAE=0.015 pDockQ2=0.041
2026-08-16 00:39:11,800 Query 10/10: rfd3_input_step2_anexina_binder_step2_round_02_0_model_0_top9_score0.863 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:17 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:39:12,130 Sleeping for 7s. Reason: PENDING
2026-08-16 00:39:19,458 Sleeping for 9s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-16 00:39:29,429 Sleeping for 8s. Reason: PENDING
2026-08-16 00:39:45,580 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79.6 pTM=0.767 ipTM=0.352
2026-08-16 00:39:52,691 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.2 pTM=0.771 ipTM=0.359 tol=0.655
2026-08-16 00:39:59,942 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.4 pTM=0.766 ipTM=0.333 tol=0.278
2026-08-16 00:39:59,942 alphafold2_multimer_v3_model_1_seed_000 took 21.5s (2 recycles)
2026-08-16 00:40:07,323 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=78.6 pTM=0.748 ipTM=0.304
2026-08-16 00:40:14,801 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=78.2 pTM=0.744 ipTM=0.304 tol=0.35
2026-08-16 00:40:14,802 alphafold2_multimer_v3_model_2_seed_000 took 14.8s (1 recycles)
2026-08-16 00:40:14,811 reranking models by 'multimer' metric
2026-08-16 00:40:14,812 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.4 pTM=0.766 ipTM=0.333 ipSAE=0.0753 pDockQ2=0.0496
2026-08-16 00:40:14,812 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.2 pTM=0.744 ipTM=0.304 ipSAE=0.0618 pDockQ2=0.0449
2026-08-16 00:40:15,315 Done
Melhor candidato da rodada 2: rfd3_input_step2_anexina_binder_step2_round_02_0_model_0_top4_score0.815
Template escolhido para a proxima rodada: /kaggle/working/outputs/level2/refinement_rounds/round_02/af2_predictions_multimer/rfd3_input_step2_anexina_binder_step2_round_02_0_model_0/rfd3_input_step2_anexina_binder_step2_round_02_0_model_0_top10_score0.858_unrelaxed_rank_001_alphafold2_multimer_v3_model_2_seed_000.pdb

=== Rodada 3/6 ===
Usando como template: /kaggle/working/outputs/level2/refinement_rounds/round_02/af2_predictions_multimer/rfd3_input_step2_anexina_binder_step2_round_02_0_model_0/rfd3_input_step2_anexina_binder_step2_round_02_0_model_0_top10_score0.858_unrelaxed_rank_001_alphafold2_multimer_v3_model_2_seed_000.pdb

/usr/local/lib/python3.12/dist-packages/hydra/_internal/config_loader_impl.py:216: UserWarning: provider=hydra.searchpath in main, path=configs is not available.
  warnings.warn(
Environment variable CCD_MIRROR_PATH not set. Will not be able to use function requiring this variable. To set it you may:
  (1) add the line 'export VAR_NAME=path/to/variable' to your .bashrc or .zshrc file
  (2) set it in your current shell with 'export VAR_NAME=path/to/variable'
  (3) write it to a .env file in the root of the atomworks.io repository
Environment variable PDB_MIRROR_PATH not set. Will not be able to use function requiring this variable. To set it you may:
  (1) add the line 'export VAR_NAME=path/to/variable' to your .bashrc or .zshrc file
  (2) set it in your current shell with 'export VAR_NAME=path/to/variable'
  (3) write it to a .env file in the root of the atomworks.io repository
00:40:25 DEBUG transforms: Debug mode is on
00:40:27 INFO rfd3.engine: [rank: 0] Outputs will be written to /kaggle/working/outputs/level2/refinement_rounds/round_03/rfd3_designs.
00:40:27 INFO rfd3.engine: [rank: 0] Found 0 existing example IDs in the output directory (0 total).
Using bfloat16 Automatic Mixed Precision (AMP)
00:40:37 WARNING atomworks.io: We can't fix formal charges without building from templates, as we need to know the true number of hydrogens bonded to a given atom, not the inferred number. This may lead to occasional inaccuracies after adding inter-residue bonds. To avoid this and fix formal charges, set `add_missing_atoms = True`.
00:40:37 WARNING atomworks.io: The `extra_fields` argument will be ignored if there is no CIF file input.
00:40:45 INFO rfd3.engine: [rank: 0] Finished inference batch in 7.97 seconds.
00:40:45 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_step2_anexina_binder_step2_round_03_0_model_0 written to /kaggle/working/outputs/level2/refinement_rounds/round_03/rfd3_designs/rfd3_input_step2_anexina_binder_step2_round_03_0_model_0.

✓ Convertido com sucesso: rfd3_input_step2_anexina_binder_step2_round_03_0_model_0.pdb
Iniciando a filtragem rigorosa de backbones...
Filtragem concluida!
✓ Total avaliados: 1
✓ Total no filtro estrito (fracao >= 0.30 e clashes <= 0): 1
🏆 Aprovados e enviados para o MPNN (Top 10): 1
Desenhando sequencias para o backbone: rfd3_input_step2_anexina_binder_step2_round_03_0_model_0
Filtrando e formatando complexos para o AlphaFold Multimer...
✓ Pronto! 10 complexos organizados para validacao do fragmento.
Validando sequencias do design: rfd3_input_step2_anexina_binder_step2_round_03_0_model_0

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-16 00:42:29,522 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-16 00:42:30,178 Running on GPU
2026-08-16 00:42:30,439 Found 5 citations for tools or databases
2026-08-16 00:42:30,500 Query 1/10: rfd3_input_step2_anexina_binder_step2_round_03_0_model_0_top10_score0.751 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:19 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:42:31,208 Sleeping for 8s. Reason: PENDING
2026-08-16 00:42:39,524 Sleeping for 10s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:42:50,518 Sleeping for 7s. Reason: PENDING
2026-08-16 00:43:44,002 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=83.1 pTM=0.793 ipTM=0.462
2026-08-16 00:44:20,137 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.4 pTM=0.795 ipTM=0.457 tol=0.984
2026-08-16 00:44:27,123 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=78.6 pTM=0.755 ipTM=0.313 tol=2.01
2026-08-16 00:44:34,166 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=77.1 pTM=0.744 ipTM=0.278 tol=0.796
2026-08-16 00:44:34,166 alphafold2_multimer_v3_model_1_seed_000 took 88.4s (3 recycles)
2026-08-16 00:44:41,222 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=80.2 pTM=0.764 ipTM=0.401
2026-08-16 00:44:48,309 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=80.2 pTM=0.759 ipTM=0.364 tol=0.975
2026-08-16 00:44:55,458 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=77.6 pTM=0.74 ipTM=0.307 tol=0.523
2026-08-16 00:45:02,693 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=78.2 pTM=0.742 ipTM=0.316 tol=0.337
2026-08-16 00:45:02,694 alphafold2_multimer_v3_model_2_seed_000 took 28.5s (3 recycles)
2026-08-16 00:45:02,705 reranking models by 'multimer' metric
2026-08-16 00:45:02,705 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.2 pTM=0.742 ipTM=0.316 ipSAE=0.0628 pDockQ2=0.0396
2026-08-16 00:45:02,705 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=77.1 pTM=0.744 ipTM=0.278 ipSAE=0.0456 pDockQ2=0.0283
2026-08-16 00:45:03,220 Query 2/10: rfd3_input_step2_anexina_binder_step2_round_03_0_model_0_top1_score0.729 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:11 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:45:03,561 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-16 00:45:14,573 Sleeping for 5s. Reason: PENDING
2026-08-16 00:45:27,848 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=85.3 pTM=0.823 ipTM=0.545
2026-08-16 00:45:35,038 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=87.8 pTM=0.844 ipTM=0.605 tol=0.763
2026-08-16 00:45:42,355 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=88.9 pTM=0.855 ipTM=0.657 tol=0.263
2026-08-16 00:45:42,355 alphafold2_multimer_v3_model_1_seed_000 took 21.7s (2 recycles)
2026-08-16 00:45:49,753 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=84.7 pTM=0.815 ipTM=0.526
2026-08-16 00:45:57,074 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=88 pTM=0.841 ipTM=0.616 tol=0.895
2026-08-16 00:46:04,339 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=88.8 pTM=0.849 ipTM=0.669 tol=0.153
2026-08-16 00:46:04,339 alphafold2_multimer_v3_model_2_seed_000 took 22.0s (2 recycles)
2026-08-16 00:46:04,350 reranking models by 'multimer' metric
2026-08-16 00:46:04,350 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=88.8 pTM=0.849 ipTM=0.669 ipSAE=0.486 pDockQ2=0.339
2026-08-16 00:46:04,350 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=88.9 pTM=0.855 ipTM=0.657 ipSAE=0.482 pDockQ2=0.34
2026-08-16 00:46:04,853 Query 3/10: rfd3_input_step2_anexina_binder_step2_round_03_0_model_0_top2_score0.716 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:46:05,182 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-16 00:46:14,152 Sleeping for 5s. Reason: PENDING
2026-08-16 00:46:27,409 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.5 pTM=0.748 ipTM=0.276
2026-08-16 00:46:34,542 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.6 pTM=0.751 ipTM=0.276 tol=1.49
2026-08-16 00:46:41,815 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.8 pTM=0.78 ipTM=0.397 tol=2.2
2026-08-16 00:46:49,232 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=83.1 pTM=0.794 ipTM=0.474 tol=1.75
2026-08-16 00:46:49,232 alphafold2_multimer_v3_model_1_seed_000 took 29.0s (3 recycles)
2026-08-16 00:46:56,736 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=75.4 pTM=0.715 ipTM=0.219
2026-08-16 00:47:04,150 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=83.9 pTM=0.795 ipTM=0.488 tol=0.776
2026-08-16 00:47:11,429 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=85.4 pTM=0.807 ipTM=0.55 tol=0.216
2026-08-16 00:47:11,429 alphafold2_multimer_v3_model_2_seed_000 took 22.2s (2 recycles)
2026-08-16 00:47:11,439 reranking models by 'multimer' metric
2026-08-16 00:47:11,439 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=85.4 pTM=0.807 ipTM=0.55 ipSAE=0.273 pDockQ2=0.22
2026-08-16 00:47:11,439 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.1 pTM=0.794 ipTM=0.474 ipSAE=0.214 pDockQ2=0.166
2026-08-16 00:47:11,939 Query 4/10: rfd3_input_step2_anexina_binder_step2_round_03_0_model_0_top3_score0.727 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:13 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:47:12,273 Sleeping for 5s. Reason: PENDING
2026-08-16 00:47:17,586 Sleeping for 7s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-16 00:47:25,592 Sleeping for 8s. Reason: PENDING
2026-08-16 00:47:41,842 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.6 pTM=0.758 ipTM=0.341
2026-08-16 00:47:48,946 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=82.1 pTM=0.79 ipTM=0.431 tol=1.15
2026-08-16 00:47:56,188 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.4 pTM=0.779 ipTM=0.391 tol=0.345
2026-08-16 00:47:56,189 alphafold2_multimer_v3_model_1_seed_000 took 21.5s (2 recycles)
2026-08-16 00:48:03,561 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=73.6 pTM=0.709 ipTM=0.221
2026-08-16 00:48:11,069 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=75.1 pTM=0.718 ipTM=0.228 tol=1.53
2026-08-16 00:48:18,536 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=75.6 pTM=0.719 ipTM=0.236 tol=0.613
2026-08-16 00:48:25,836 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=76.6 pTM=0.725 ipTM=0.254 tol=0.851
2026-08-16 00:48:25,836 alphafold2_multimer_v3_model_2_seed_000 took 29.6s (3 recycles)
2026-08-16 00:48:25,846 reranking models by 'multimer' metric
2026-08-16 00:48:25,846 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=81.4 pTM=0.779 ipTM=0.391 ipSAE=0.123 pDockQ2=0.0692
2026-08-16 00:48:25,847 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=76.6 pTM=0.725 ipTM=0.254 ipSAE=0.0244 pDockQ2=0.0282
2026-08-16 00:48:26,361 Query 5/10: rfd3_input_step2_anexina_binder_step2_round_03_0_model_0_top4_score0.731 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:48:26,664 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-16 00:48:36,551 Sleeping for 7s. Reason: PENDING
2026-08-16 00:48:52,475 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=75.2 pTM=0.733 ipTM=0.239
2026-08-16 00:48:59,573 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.1 pTM=0.79 ipTM=0.415 tol=1.42
2026-08-16 00:49:06,803 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.8 pTM=0.811 ipTM=0.504 tol=2.45
2026-08-16 00:49:14,168 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85 pTM=0.816 ipTM=0.527 tol=0.589
2026-08-16 00:49:14,168 alphafold2_multimer_v3_model_1_seed_000 took 28.8s (3 recycles)
2026-08-16 00:49:21,674 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=75.6 pTM=0.739 ipTM=0.303
2026-08-16 00:49:29,153 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=79.2 pTM=0.76 ipTM=0.344 tol=1.33
2026-08-16 00:49:36,462 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78.7 pTM=0.75 ipTM=0.332 tol=1.26
2026-08-16 00:49:43,668 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=79.8 pTM=0.76 ipTM=0.359 tol=0.499
2026-08-16 00:49:43,668 alphafold2_multimer_v3_model_2_seed_000 took 29.5s (3 recycles)
2026-08-16 00:49:43,678 reranking models by 'multimer' metric
2026-08-16 00:49:43,678 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85 pTM=0.816 ipTM=0.527 ipSAE=0.275 pDockQ2=0.24
2026-08-16 00:49:43,678 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=79.8 pTM=0.76 ipTM=0.359 ipSAE=0.104 pDockQ2=0.066
2026-08-16 00:49:44,183 Query 6/10: rfd3_input_step2_anexina_binder_step2_round_03_0_model_0_top5_score0.732 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:18 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:49:44,492 Sleeping for 8s. Reason: PENDING
2026-08-16 00:49:52,816 Sleeping for 9s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-16 00:50:02,762 Sleeping for 6s. Reason: PENDING
2026-08-16 00:50:16,909 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79.6 pTM=0.761 ipTM=0.319
2026-08-16 00:50:23,979 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=84.9 pTM=0.807 ipTM=0.482 tol=0.445
2026-08-16 00:50:23,980 alphafold2_multimer_v3_model_1_seed_000 took 14.2s (1 recycles)
2026-08-16 00:50:31,196 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=80.3 pTM=0.779 ipTM=0.411
2026-08-16 00:50:38,543 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=82 pTM=0.789 ipTM=0.436 tol=0.81
2026-08-16 00:50:46,014 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=81.4 pTM=0.787 ipTM=0.446 tol=0.375
2026-08-16 00:50:46,015 alphafold2_multimer_v3_model_2_seed_000 took 22.0s (2 recycles)
2026-08-16 00:50:46,025 reranking models by 'multimer' metric
2026-08-16 00:50:46,025 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84.9 pTM=0.807 ipTM=0.482 ipSAE=0.187 pDockQ2=0.111
2026-08-16 00:50:46,025 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=81.4 pTM=0.787 ipTM=0.446 ipSAE=0.136 pDockQ2=0.0961
2026-08-16 00:50:46,528 Query 7/10: rfd3_input_step2_anexina_binder_step2_round_03_0_model_0_top6_score0.736 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:14 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:50:46,821 Sleeping for 6s. Reason: PENDING
2026-08-16 00:50:53,110 Sleeping for 7s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-16 00:51:00,984 Sleeping for 9s. Reason: PENDING
2026-08-16 00:51:18,194 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=76.1 pTM=0.73 ipTM=0.287
2026-08-16 00:51:25,431 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79.4 pTM=0.759 ipTM=0.373 tol=1.71
2026-08-16 00:51:32,783 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79 pTM=0.751 ipTM=0.336 tol=0.698
2026-08-16 00:51:40,270 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=80.5 pTM=0.767 ipTM=0.381 tol=0.448
2026-08-16 00:51:40,270 alphafold2_multimer_v3_model_1_seed_000 took 29.3s (3 recycles)
2026-08-16 00:51:47,747 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=74.1 pTM=0.697 ipTM=0.282
2026-08-16 00:51:55,045 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=76.8 pTM=0.726 ipTM=0.322 tol=0.871
2026-08-16 00:52:02,248 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=77.4 pTM=0.731 ipTM=0.343 tol=0.656
2026-08-16 00:52:09,378 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=77.9 pTM=0.737 ipTM=0.355 tol=0.342
2026-08-16 00:52:09,379 alphafold2_multimer_v3_model_2_seed_000 took 29.1s (3 recycles)
2026-08-16 00:52:09,388 reranking models by 'multimer' metric
2026-08-16 00:52:09,389 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.5 pTM=0.767 ipTM=0.381 ipSAE=0.124 pDockQ2=0.055
2026-08-16 00:52:09,389 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=77.9 pTM=0.737 ipTM=0.355 ipSAE=0.0999 pDockQ2=0.0474
2026-08-16 00:52:10,113 Query 8/10: rfd3_input_step2_anexina_binder_step2_round_03_0_model_0_top7_score0.740 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:52:10,410 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-16 00:52:21,284 Sleeping for 10s. Reason: PENDING
2026-08-16 00:52:39,435 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=80.2 pTM=0.778 ipTM=0.388
2026-08-16 00:52:46,525 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.6 pTM=0.775 ipTM=0.357 tol=0.64
2026-08-16 00:52:53,693 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.6 pTM=0.787 ipTM=0.404 tol=0.678
2026-08-16 00:53:01,021 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=80.6 pTM=0.773 ipTM=0.35 tol=0.394
2026-08-16 00:53:01,022 alphafold2_multimer_v3_model_1_seed_000 took 28.7s (3 recycles)
2026-08-16 00:53:08,497 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=74.5 pTM=0.721 ipTM=0.222
2026-08-16 00:53:15,969 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=76.8 pTM=0.741 ipTM=0.254 tol=1.03
2026-08-16 00:53:23,330 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=76.8 pTM=0.734 ipTM=0.255 tol=1.14
2026-08-16 00:53:30,569 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=77.8 pTM=0.745 ipTM=0.28 tol=0.438
2026-08-16 00:53:30,569 alphafold2_multimer_v3_model_2_seed_000 took 29.5s (3 recycles)
2026-08-16 00:53:30,580 reranking models by 'multimer' metric
2026-08-16 00:53:30,580 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.6 pTM=0.773 ipTM=0.35 ipSAE=0.113 pDockQ2=0.0522
2026-08-16 00:53:30,580 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=77.8 pTM=0.745 ipTM=0.28 ipSAE=0.0387 pDockQ2=0.0353
2026-08-16 00:53:31,094 Query 9/10: rfd3_input_step2_anexina_binder_step2_round_03_0_model_0_top8_score0.741 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:15 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:53:31,427 Sleeping for 6s. Reason: PENDING
2026-08-16 00:53:37,760 Sleeping for 8s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-16 00:53:46,744 Sleeping for 6s. Reason: PENDING
2026-08-16 00:54:00,968 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82.7 pTM=0.788 ipTM=0.428
2026-08-16 00:54:08,057 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.2 pTM=0.815 ipTM=0.516 tol=0.606
2026-08-16 00:54:15,294 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=87.2 pTM=0.833 ipTM=0.64 tol=0.372
2026-08-16 00:54:15,295 alphafold2_multimer_v3_model_1_seed_000 took 21.5s (2 recycles)
2026-08-16 00:54:22,672 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=81.2 pTM=0.77 ipTM=0.405
2026-08-16 00:54:30,145 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=83.6 pTM=0.796 ipTM=0.484 tol=0.602
2026-08-16 00:54:37,574 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=84 pTM=0.804 ipTM=0.51 tol=0.214
2026-08-16 00:54:37,574 alphafold2_multimer_v3_model_2_seed_000 took 22.3s (2 recycles)
2026-08-16 00:54:37,585 reranking models by 'multimer' metric
2026-08-16 00:54:37,585 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=87.2 pTM=0.833 ipTM=0.64 ipSAE=0.453 pDockQ2=0.248
2026-08-16 00:54:37,585 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=84 pTM=0.804 ipTM=0.51 ipSAE=0.187 pDockQ2=0.169
2026-08-16 00:54:38,098 Query 10/10: rfd3_input_step2_anexina_binder_step2_round_03_0_model_0_top9_score0.741 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:17 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:54:38,434 Sleeping for 7s. Reason: PENDING
2026-08-16 00:54:45,776 Sleeping for 9s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-16 00:54:55,768 Sleeping for 9s. Reason: PENDING
2026-08-16 00:55:12,999 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=75.2 pTM=0.742 ipTM=0.268
2026-08-16 00:55:20,165 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=77.2 pTM=0.736 ipTM=0.251 tol=3.89
2026-08-16 00:55:27,503 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=78 pTM=0.736 ipTM=0.275 tol=1.55
2026-08-16 00:55:34,967 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.4 pTM=0.752 ipTM=0.321 tol=0.949
2026-08-16 00:55:34,967 alphafold2_multimer_v3_model_1_seed_000 took 29.1s (3 recycles)
2026-08-16 00:55:42,477 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=74.8 pTM=0.721 ipTM=0.266
2026-08-16 00:55:49,837 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=78.1 pTM=0.74 ipTM=0.33 tol=2.72
2026-08-16 00:55:57,070 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=76.5 pTM=0.717 ipTM=0.268 tol=0.98
2026-08-16 00:56:04,228 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=77.6 pTM=0.73 ipTM=0.312 tol=0.899
2026-08-16 00:56:04,229 alphafold2_multimer_v3_model_2_seed_000 took 29.3s (3 recycles)
2026-08-16 00:56:04,239 reranking models by 'multimer' metric
2026-08-16 00:56:04,239 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.4 pTM=0.752 ipTM=0.321 ipSAE=0.0848 pDockQ2=0.0594
2026-08-16 00:56:04,239 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=77.6 pTM=0.73 ipTM=0.312 ipSAE=0.0769 pDockQ2=0.0667
2026-08-16 00:56:04,756 Done
Melhor candidato da rodada 3: rfd3_input_step2_anexina_binder_step2_round_03_0_model_0_top1_score0.729
Template escolhido para a proxima rodada: /kaggle/working/outputs/level2/refinement_rounds/round_03/af2_predictions_multimer/rfd3_input_step2_anexina_binder_step2_round_03_0_model_0/rfd3_input_step2_anexina_binder_step2_round_03_0_model_0_top10_score0.751_unrelaxed_rank_001_alphafold2_multimer_v3_model_2_seed_000.pdb

=== Rodada 4/6 ===
Usando como template: /kaggle/working/outputs/level2/refinement_rounds/round_03/af2_predictions_multimer/rfd3_input_step2_anexina_binder_step2_round_03_0_model_0/rfd3_input_step2_anexina_binder_step2_round_03_0_model_0_top10_score0.751_unrelaxed_rank_001_alphafold2_multimer_v3_model_2_seed_000.pdb

/usr/local/lib/python3.12/dist-packages/hydra/_internal/config_loader_impl.py:216: UserWarning: provider=hydra.searchpath in main, path=configs is not available.
  warnings.warn(
Environment variable CCD_MIRROR_PATH not set. Will not be able to use function requiring this variable. To set it you may:
  (1) add the line 'export VAR_NAME=path/to/variable' to your .bashrc or .zshrc file
  (2) set it in your current shell with 'export VAR_NAME=path/to/variable'
  (3) write it to a .env file in the root of the atomworks.io repository
Environment variable PDB_MIRROR_PATH not set. Will not be able to use function requiring this variable. To set it you may:
  (1) add the line 'export VAR_NAME=path/to/variable' to your .bashrc or .zshrc file
  (2) set it in your current shell with 'export VAR_NAME=path/to/variable'
  (3) write it to a .env file in the root of the atomworks.io repository
00:56:15 DEBUG transforms: Debug mode is on
00:56:17 INFO rfd3.engine: [rank: 0] Outputs will be written to /kaggle/working/outputs/level2/refinement_rounds/round_04/rfd3_designs.
00:56:17 INFO rfd3.engine: [rank: 0] Found 0 existing example IDs in the output directory (0 total).
Using bfloat16 Automatic Mixed Precision (AMP)
00:56:26 WARNING atomworks.io: We can't fix formal charges without building from templates, as we need to know the true number of hydrogens bonded to a given atom, not the inferred number. This may lead to occasional inaccuracies after adding inter-residue bonds. To avoid this and fix formal charges, set `add_missing_atoms = True`.
00:56:27 WARNING atomworks.io: The `extra_fields` argument will be ignored if there is no CIF file input.
00:56:34 INFO rfd3.engine: [rank: 0] Finished inference batch in 7.42 seconds.
00:56:35 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_step2_anexina_binder_step2_round_04_0_model_0 written to /kaggle/working/outputs/level2/refinement_rounds/round_04/rfd3_designs/rfd3_input_step2_anexina_binder_step2_round_04_0_model_0.

✓ Convertido com sucesso: rfd3_input_step2_anexina_binder_step2_round_04_0_model_0.pdb
Iniciando a filtragem rigorosa de backbones...
Filtragem concluida!
✓ Total avaliados: 1
✓ Total no filtro estrito (fracao >= 0.30 e clashes <= 0): 1
🏆 Aprovados e enviados para o MPNN (Top 10): 1
Desenhando sequencias para o backbone: rfd3_input_step2_anexina_binder_step2_round_04_0_model_0
Filtrando e formatando complexos para o AlphaFold Multimer...
✓ Pronto! 10 complexos organizados para validacao do fragmento.
Validando sequencias do design: rfd3_input_step2_anexina_binder_step2_round_04_0_model_0

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-16 00:58:23,355 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-16 00:58:24,014 Running on GPU
2026-08-16 00:58:24,276 Found 5 citations for tools or databases
2026-08-16 00:58:24,336 Query 1/10: rfd3_input_step2_anexina_binder_step2_round_04_0_model_0_top10_score0.891 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 00:58:25,023 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-16 00:58:35,045 Sleeping for 9s. Reason: PENDING
2026-08-16 00:59:31,160 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=76.7 pTM=0.75 ipTM=0.261
2026-08-16 01:00:09,539 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.9 pTM=0.764 ipTM=0.303 tol=1.16
2026-08-16 01:00:16,487 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79 pTM=0.762 ipTM=0.292 tol=0.503
2026-08-16 01:00:23,490 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.7 pTM=0.767 ipTM=0.319 tol=0.466
2026-08-16 01:00:23,491 alphafold2_multimer_v3_model_1_seed_000 took 91.1s (3 recycles)
2026-08-16 01:00:30,555 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=77.8 pTM=0.757 ipTM=0.292
2026-08-16 01:00:37,653 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=79.3 pTM=0.762 ipTM=0.313 tol=1.76
2026-08-16 01:00:44,822 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78.4 pTM=0.752 ipTM=0.27 tol=0.585
2026-08-16 01:00:52,073 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=79.4 pTM=0.764 ipTM=0.323 tol=0.498
2026-08-16 01:00:52,073 alphafold2_multimer_v3_model_2_seed_000 took 28.6s (3 recycles)
2026-08-16 01:00:52,084 reranking models by 'multimer' metric
2026-08-16 01:00:52,084 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=79.4 pTM=0.764 ipTM=0.323 ipSAE=0.0588 pDockQ2=0.0601
2026-08-16 01:00:52,084 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.7 pTM=0.767 ipTM=0.319 ipSAE=0.0637 pDockQ2=0.0453
2026-08-16 01:00:52,628 Query 2/10: rfd3_input_step2_anexina_binder_step2_round_04_0_model_0_top1_score0.844 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:17 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:00:52,991 Sleeping for 6s. Reason: PENDING
2026-08-16 01:00:59,325 Sleeping for 10s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-16 01:01:10,314 Sleeping for 8s. Reason: PENDING
2026-08-16 01:01:26,748 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.6 pTM=0.765 ipTM=0.342
2026-08-16 01:01:34,065 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.4 pTM=0.772 ipTM=0.35 tol=1.47
2026-08-16 01:01:41,510 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.7 pTM=0.773 ipTM=0.35 tol=1.02
2026-08-16 01:01:49,009 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=80.7 pTM=0.776 ipTM=0.364 tol=0.398
2026-08-16 01:01:49,009 alphafold2_multimer_v3_model_1_seed_000 took 29.6s (3 recycles)
2026-08-16 01:01:56,405 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=78.2 pTM=0.766 ipTM=0.366
2026-08-16 01:02:03,656 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=79.5 pTM=0.755 ipTM=0.309 tol=0.928
2026-08-16 01:02:10,813 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=79.8 pTM=0.763 ipTM=0.341 tol=0.456
2026-08-16 01:02:10,813 alphafold2_multimer_v3_model_2_seed_000 took 21.8s (2 recycles)
2026-08-16 01:02:10,824 reranking models by 'multimer' metric
2026-08-16 01:02:10,824 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.7 pTM=0.776 ipTM=0.364 ipSAE=0.0783 pDockQ2=0.0641
2026-08-16 01:02:10,824 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=79.8 pTM=0.763 ipTM=0.341 ipSAE=0.0411 pDockQ2=0.062
2026-08-16 01:02:11,360 Query 3/10: rfd3_input_step2_anexina_binder_step2_round_04_0_model_0_top2_score0.848 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:13 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:02:11,672 Sleeping for 7s. Reason: PENDING
2026-08-16 01:02:18,961 Sleeping for 5s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-16 01:02:24,876 Sleeping for 10s. Reason: PENDING
2026-08-16 01:02:43,018 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.8 pTM=0.762 ipTM=0.319
2026-08-16 01:02:50,086 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79.1 pTM=0.756 ipTM=0.288 tol=0.755
2026-08-16 01:02:57,266 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.8 pTM=0.763 ipTM=0.31 tol=0.51
2026-08-16 01:03:04,607 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.7 pTM=0.762 ipTM=0.315 tol=1.04
2026-08-16 01:03:04,608 alphafold2_multimer_v3_model_1_seed_000 took 28.7s (3 recycles)
2026-08-16 01:03:12,086 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=77.8 pTM=0.746 ipTM=0.273
2026-08-16 01:03:19,545 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=78.6 pTM=0.751 ipTM=0.29 tol=0.542
2026-08-16 01:03:26,871 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=79.4 pTM=0.762 ipTM=0.341 tol=0.878
2026-08-16 01:03:34,089 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=78.9 pTM=0.753 ipTM=0.311 tol=0.85
2026-08-16 01:03:34,090 alphafold2_multimer_v3_model_2_seed_000 took 29.5s (3 recycles)
2026-08-16 01:03:34,100 reranking models by 'multimer' metric
2026-08-16 01:03:34,100 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.7 pTM=0.762 ipTM=0.315 ipSAE=0.0467 pDockQ2=0.0433
2026-08-16 01:03:34,100 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.9 pTM=0.753 ipTM=0.311 ipSAE=0.039 pDockQ2=0.0447
2026-08-16 01:03:34,624 Query 4/10: rfd3_input_step2_anexina_binder_step2_round_04_0_model_0_top3_score0.850 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:16 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:03:34,935 Sleeping for 8s. Reason: PENDING
2026-08-16 01:03:43,270 Sleeping for 7s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-16 01:03:51,261 Sleeping for 8s. Reason: PENDING
2026-08-16 01:04:07,464 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=76.2 pTM=0.736 ipTM=0.234
2026-08-16 01:04:14,533 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=77.8 pTM=0.746 ipTM=0.253 tol=0.779
2026-08-16 01:04:21,745 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=78.2 pTM=0.751 ipTM=0.268 tol=0.529
2026-08-16 01:04:29,108 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=78.3 pTM=0.751 ipTM=0.273 tol=0.701
2026-08-16 01:04:29,108 alphafold2_multimer_v3_model_1_seed_000 took 28.8s (3 recycles)
2026-08-16 01:04:36,593 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=76.7 pTM=0.739 ipTM=0.268
2026-08-16 01:04:44,001 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=78.4 pTM=0.75 ipTM=0.301 tol=0.857
2026-08-16 01:04:51,305 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78 pTM=0.745 ipTM=0.278 tol=0.584
2026-08-16 01:04:58,502 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=79.2 pTM=0.759 ipTM=0.336 tol=0.615
2026-08-16 01:04:58,503 alphafold2_multimer_v3_model_2_seed_000 took 29.4s (3 recycles)
2026-08-16 01:04:58,512 reranking models by 'multimer' metric
2026-08-16 01:04:58,512 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=79.2 pTM=0.759 ipTM=0.336 ipSAE=0.0596 pDockQ2=0.0793
2026-08-16 01:04:58,513 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=78.3 pTM=0.751 ipTM=0.273 ipSAE=0.0256 pDockQ2=0.0431
2026-08-16 01:04:59,051 Query 5/10: rfd3_input_step2_anexina_binder_step2_round_04_0_model_0_top4_score0.853 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:04:59,413 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-16 01:05:09,400 Sleeping for 9s. Reason: PENDING
2026-08-16 01:05:26,653 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79.9 pTM=0.807 ipTM=0.546
2026-08-16 01:05:33,707 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=77.9 pTM=0.754 ipTM=0.298 tol=1.57
2026-08-16 01:05:40,883 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.5 pTM=0.779 ipTM=0.37 tol=1.05
2026-08-16 01:05:48,207 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.2 pTM=0.755 ipTM=0.299 tol=0.488
2026-08-16 01:05:48,207 alphafold2_multimer_v3_model_1_seed_000 took 28.7s (3 recycles)
2026-08-16 01:05:55,667 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=76.2 pTM=0.747 ipTM=0.296
2026-08-16 01:06:03,113 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=76.9 pTM=0.741 ipTM=0.26 tol=1.23
2026-08-16 01:06:10,430 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=77.2 pTM=0.743 ipTM=0.259 tol=1.69
2026-08-16 01:06:17,633 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=77.8 pTM=0.744 ipTM=0.278 tol=0.933
2026-08-16 01:06:17,634 alphafold2_multimer_v3_model_2_seed_000 took 29.4s (3 recycles)
2026-08-16 01:06:17,643 reranking models by 'multimer' metric
2026-08-16 01:06:17,643 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.2 pTM=0.755 ipTM=0.299 ipSAE=0.048 pDockQ2=0.0445
2026-08-16 01:06:17,644 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=77.8 pTM=0.744 ipTM=0.278 ipSAE=0.0299 pDockQ2=0.0522
2026-08-16 01:06:18,168 Query 6/10: rfd3_input_step2_anexina_binder_step2_round_04_0_model_0_top5_score0.870 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:18 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:06:18,500 Sleeping for 8s. Reason: PENDING
2026-08-16 01:06:26,823 Sleeping for 9s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-16 01:06:36,812 Sleeping for 8s. Reason: PENDING
2026-08-16 01:06:53,045 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.7 pTM=0.771 ipTM=0.343
2026-08-16 01:07:00,121 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80 pTM=0.778 ipTM=0.361 tol=1.92
2026-08-16 01:07:07,317 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.6 pTM=0.771 ipTM=0.345 tol=0.471
2026-08-16 01:07:07,317 alphafold2_multimer_v3_model_1_seed_000 took 21.4s (2 recycles)
2026-08-16 01:07:14,673 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=78.2 pTM=0.776 ipTM=0.372
2026-08-16 01:07:22,141 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=78.6 pTM=0.763 ipTM=0.328 tol=1.11
2026-08-16 01:07:29,624 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78.3 pTM=0.765 ipTM=0.335 tol=0.872
2026-08-16 01:07:36,950 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=78.6 pTM=0.764 ipTM=0.341 tol=0.548
2026-08-16 01:07:36,950 alphafold2_multimer_v3_model_2_seed_000 took 29.6s (3 recycles)
2026-08-16 01:07:36,960 reranking models by 'multimer' metric
2026-08-16 01:07:36,960 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.6 pTM=0.771 ipTM=0.345 ipSAE=0.0639 pDockQ2=0.0624
2026-08-16 01:07:36,960 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.6 pTM=0.764 ipTM=0.341 ipSAE=0.0764 pDockQ2=0.0633
2026-08-16 01:07:37,477 Query 7/10: rfd3_input_step2_anexina_binder_step2_round_04_0_model_0_top6_score0.867 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:19 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:07:37,812 Sleeping for 10s. Reason: PENDING
2026-08-16 01:07:48,145 Sleeping for 8s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-16 01:07:57,502 Sleeping for 9s. Reason: PENDING
2026-08-16 01:08:14,843 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=76.2 pTM=0.743 ipTM=0.265
2026-08-16 01:08:21,819 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.2 pTM=0.76 ipTM=0.303 tol=2.62
2026-08-16 01:08:28,841 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.7 pTM=0.782 ipTM=0.383 tol=1.8
2026-08-16 01:08:35,856 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.1 pTM=0.758 ipTM=0.299 tol=1.22
2026-08-16 01:08:35,856 alphafold2_multimer_v3_model_1_seed_000 took 28.0s (3 recycles)
2026-08-16 01:08:42,872 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=77.6 pTM=0.755 ipTM=0.316
2026-08-16 01:08:49,878 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=76.9 pTM=0.737 ipTM=0.244 tol=1.55
2026-08-16 01:08:56,857 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78.1 pTM=0.755 ipTM=0.311 tol=0.91
2026-08-16 01:09:03,819 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=78.1 pTM=0.747 ipTM=0.285 tol=1.42
2026-08-16 01:09:03,819 alphafold2_multimer_v3_model_2_seed_000 took 28.0s (3 recycles)
2026-08-16 01:09:03,830 reranking models by 'multimer' metric
2026-08-16 01:09:03,830 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.1 pTM=0.758 ipTM=0.299 ipSAE=0.0364 pDockQ2=0.0429
2026-08-16 01:09:03,830 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.1 pTM=0.747 ipTM=0.285 ipSAE=0.0303 pDockQ2=0.0424
2026-08-16 01:09:04,601 Query 8/10: rfd3_input_step2_anexina_binder_step2_round_04_0_model_0_top7_score0.879 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:14 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:09:04,949 Sleeping for 5s. Reason: PENDING
2026-08-16 01:09:10,291 Sleeping for 8s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:16 remaining: 00:00]

2026-08-16 01:09:19,303 Sleeping for 6s. Reason: PENDING
2026-08-16 01:09:25,644 Sleeping for 9s. Reason: RUNNING
2026-08-16 01:09:42,578 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79.8 pTM=0.766 ipTM=0.335
2026-08-16 01:09:49,314 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.8 pTM=0.81 ipTM=0.474 tol=0.974
2026-08-16 01:09:56,062 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.6 pTM=0.783 ipTM=0.378 tol=0.443
2026-08-16 01:09:56,062 alphafold2_multimer_v3_model_1_seed_000 took 20.3s (2 recycles)
2026-08-16 01:10:02,862 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=80.1 pTM=0.76 ipTM=0.33
2026-08-16 01:10:09,657 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=82.2 pTM=0.781 ipTM=0.404 tol=0.947
2026-08-16 01:10:16,462 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=81.1 pTM=0.768 ipTM=0.347 tol=0.204
2026-08-16 01:10:16,462 alphafold2_multimer_v3_model_2_seed_000 took 20.4s (2 recycles)
2026-08-16 01:10:16,473 reranking models by 'multimer' metric
2026-08-16 01:10:16,473 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=81.6 pTM=0.783 ipTM=0.378 ipSAE=0.0787 pDockQ2=0.0708
2026-08-16 01:10:16,473 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=81.1 pTM=0.768 ipTM=0.347 ipSAE=0.0601 pDockQ2=0.0567
2026-08-16 01:10:16,981 Query 9/10: rfd3_input_step2_anexina_binder_step2_round_04_0_model_0_top8_score0.866 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:18 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:10:17,316 Sleeping for 10s. Reason: PENDING
2026-08-16 01:10:27,652 Sleeping for 7s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-16 01:10:35,676 Sleeping for 9s. Reason: PENDING
2026-08-16 01:10:52,476 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=76 pTM=0.743 ipTM=0.25
2026-08-16 01:10:59,135 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=76.1 pTM=0.746 ipTM=0.245 tol=4.21
2026-08-16 01:11:05,822 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=76.9 pTM=0.75 ipTM=0.257 tol=2.27
2026-08-16 01:11:12,524 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=77.2 pTM=0.751 ipTM=0.258 tol=2.28
2026-08-16 01:11:12,524 alphafold2_multimer_v3_model_1_seed_000 took 26.8s (3 recycles)
2026-08-16 01:11:19,266 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=76.6 pTM=0.754 ipTM=0.29
2026-08-16 01:11:26,008 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=77.9 pTM=0.756 ipTM=0.297 tol=1.25
2026-08-16 01:11:32,768 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=77.5 pTM=0.75 ipTM=0.268 tol=0.893
2026-08-16 01:11:39,536 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=77.6 pTM=0.752 ipTM=0.282 tol=0.406
2026-08-16 01:11:39,536 alphafold2_multimer_v3_model_2_seed_000 took 27.0s (3 recycles)
2026-08-16 01:11:39,546 reranking models by 'multimer' metric
2026-08-16 01:11:39,546 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=77.6 pTM=0.752 ipTM=0.282 ipSAE=0.0238 pDockQ2=0.0437
2026-08-16 01:11:39,546 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=77.2 pTM=0.751 ipTM=0.258 ipSAE=0.0173 pDockQ2=0.0326
2026-08-16 01:11:40,087 Query 10/10: rfd3_input_step2_anexina_binder_step2_round_04_0_model_0_top9_score0.881 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:29 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:11:40,416 Sleeping for 7s. Reason: PENDING
2026-08-16 01:11:47,756 Sleeping for 5s. Reason: PENDING
2026-08-16 01:11:53,075 Sleeping for 8s. Reason: RUNNING
2026-08-16 01:12:01,406 Sleeping for 8s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-16 01:12:10,377 Sleeping for 6s. Reason: PENDING
2026-08-16 01:12:24,164 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=75.9 pTM=0.744 ipTM=0.258
2026-08-16 01:12:30,782 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=76.6 pTM=0.743 ipTM=0.245 tol=1.35
2026-08-16 01:12:37,421 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=77.8 pTM=0.751 ipTM=0.267 tol=1.05
2026-08-16 01:12:44,090 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=77.1 pTM=0.748 ipTM=0.262 tol=0.992
2026-08-16 01:12:44,090 alphafold2_multimer_v3_model_1_seed_000 took 26.6s (3 recycles)
2026-08-16 01:12:50,795 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=75.6 pTM=0.734 ipTM=0.244
2026-08-16 01:12:57,498 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=77 pTM=0.742 ipTM=0.264 tol=2.15
2026-08-16 01:13:04,212 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=77 pTM=0.737 ipTM=0.246 tol=0.994
2026-08-16 01:13:10,948 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=77.2 pTM=0.739 ipTM=0.26 tol=0.803
2026-08-16 01:13:10,948 alphafold2_multimer_v3_model_2_seed_000 took 26.8s (3 recycles)
2026-08-16 01:13:10,959 reranking models by 'multimer' metric
2026-08-16 01:13:10,959 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=77.1 pTM=0.748 ipTM=0.262 ipSAE=0.019 pDockQ2=0.0337
2026-08-16 01:13:10,960 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=77.2 pTM=0.739 ipTM=0.26 ipSAE=0.021 pDockQ2=0.0386
2026-08-16 01:13:11,484 Done
Melhor candidato da rodada 4: rfd3_input_step2_anexina_binder_step2_round_04_0_model_0_top7_score0.879
Template escolhido para a proxima rodada: /kaggle/working/outputs/level2/refinement_rounds/round_04/af2_predictions_multimer/rfd3_input_step2_anexina_binder_step2_round_04_0_model_0/rfd3_input_step2_anexina_binder_step2_round_04_0_model_0_top10_score0.891_unrelaxed_rank_001_alphafold2_multimer_v3_model_2_seed_000.pdb

=== Rodada 5/6 ===
Usando como template: /kaggle/working/outputs/level2/refinement_rounds/round_04/af2_predictions_multimer/rfd3_input_step2_anexina_binder_step2_round_04_0_model_0/rfd3_input_step2_anexina_binder_step2_round_04_0_model_0_top10_score0.891_unrelaxed_rank_001_alphafold2_multimer_v3_model_2_seed_000.pdb

/usr/local/lib/python3.12/dist-packages/hydra/_internal/config_loader_impl.py:216: UserWarning: provider=hydra.searchpath in main, path=configs is not available.
  warnings.warn(
Environment variable CCD_MIRROR_PATH not set. Will not be able to use function requiring this variable. To set it you may:
  (1) add the line 'export VAR_NAME=path/to/variable' to your .bashrc or .zshrc file
  (2) set it in your current shell with 'export VAR_NAME=path/to/variable'
  (3) write it to a .env file in the root of the atomworks.io repository
Environment variable PDB_MIRROR_PATH not set. Will not be able to use function requiring this variable. To set it you may:
  (1) add the line 'export VAR_NAME=path/to/variable' to your .bashrc or .zshrc file
  (2) set it in your current shell with 'export VAR_NAME=path/to/variable'
  (3) write it to a .env file in the root of the atomworks.io repository
01:13:22 DEBUG transforms: Debug mode is on
01:13:24 INFO rfd3.engine: [rank: 0] Outputs will be written to /kaggle/working/outputs/level2/refinement_rounds/round_05/rfd3_designs.
01:13:24 INFO rfd3.engine: [rank: 0] Found 0 existing example IDs in the output directory (0 total).
Using bfloat16 Automatic Mixed Precision (AMP)
01:13:33 WARNING atomworks.io: We can't fix formal charges without building from templates, as we need to know the true number of hydrogens bonded to a given atom, not the inferred number. This may lead to occasional inaccuracies after adding inter-residue bonds. To avoid this and fix formal charges, set `add_missing_atoms = True`.
01:13:34 WARNING atomworks.io: The `extra_fields` argument will be ignored if there is no CIF file input.
01:13:41 INFO rfd3.engine: [rank: 0] Finished inference batch in 6.76 seconds.
01:13:41 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_step2_anexina_binder_step2_round_05_0_model_0 written to /kaggle/working/outputs/level2/refinement_rounds/round_05/rfd3_designs/rfd3_input_step2_anexina_binder_step2_round_05_0_model_0.

✓ Convertido com sucesso: rfd3_input_step2_anexina_binder_step2_round_05_0_model_0.pdb
Iniciando a filtragem rigorosa de backbones...
Filtragem concluida!
✓ Total avaliados: 1
✓ Total no filtro estrito (fracao >= 0.30 e clashes <= 0): 1
🏆 Aprovados e enviados para o MPNN (Top 10): 1
Desenhando sequencias para o backbone: rfd3_input_step2_anexina_binder_step2_round_05_0_model_0
Filtrando e formatando complexos para o AlphaFold Multimer...
✓ Pronto! 10 complexos organizados para validacao do fragmento.
Validando sequencias do design: rfd3_input_step2_anexina_binder_step2_round_05_0_model_0

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-16 01:15:30,427 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-16 01:15:31,076 Running on GPU
2026-08-16 01:15:31,354 Found 5 citations for tools or databases
2026-08-16 01:15:31,416 Query 1/10: rfd3_input_step2_anexina_binder_step2_round_05_0_model_0_top10_score0.827 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:15 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:15:32,100 Sleeping for 6s. Reason: PENDING
2026-08-16 01:15:38,443 Sleeping for 8s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-16 01:15:47,340 Sleeping for 7s. Reason: PENDING
2026-08-16 01:16:41,975 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=74.9 pTM=0.737 ipTM=0.23
2026-08-16 01:17:19,649 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=76.6 pTM=0.746 ipTM=0.246 tol=1.78
2026-08-16 01:17:26,139 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=75.5 pTM=0.74 ipTM=0.221 tol=0.731
2026-08-16 01:17:32,679 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=76.4 pTM=0.745 ipTM=0.241 tol=0.791
2026-08-16 01:17:32,679 alphafold2_multimer_v3_model_1_seed_000 took 89.7s (3 recycles)
2026-08-16 01:17:39,304 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=76.3 pTM=0.744 ipTM=0.27
2026-08-16 01:17:45,945 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=74.9 pTM=0.738 ipTM=0.234 tol=1.7
2026-08-16 01:17:52,582 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=75 pTM=0.741 ipTM=0.234 tol=3.36
2026-08-16 01:17:59,221 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=74.8 pTM=0.741 ipTM=0.238 tol=0.534
2026-08-16 01:17:59,221 alphafold2_multimer_v3_model_2_seed_000 took 26.5s (3 recycles)
2026-08-16 01:17:59,242 reranking models by 'multimer' metric
2026-08-16 01:17:59,243 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=76.4 pTM=0.745 ipTM=0.241 ipSAE=0.0215 pDockQ2=0.0407
2026-08-16 01:17:59,243 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=74.8 pTM=0.741 ipTM=0.238 ipSAE=0.0149 pDockQ2=0.0387
2026-08-16 01:17:59,800 Query 2/10: rfd3_input_step2_anexina_binder_step2_round_05_0_model_0_top1_score0.713 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:16 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:18:00,124 Sleeping for 6s. Reason: PENDING
2026-08-16 01:18:06,438 Sleeping for 9s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-16 01:18:16,444 Sleeping for 6s. Reason: PENDING
2026-08-16 01:18:30,166 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=80.2 pTM=0.78 ipTM=0.399
2026-08-16 01:18:36,698 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.2 pTM=0.777 ipTM=0.369 tol=0.734
2026-08-16 01:18:43,268 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.5 pTM=0.77 ipTM=0.347 tol=0.431
2026-08-16 01:18:43,268 alphafold2_multimer_v3_model_1_seed_000 took 19.7s (2 recycles)
2026-08-16 01:18:49,903 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=77.6 pTM=0.755 ipTM=0.334
2026-08-16 01:18:56,539 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=78.7 pTM=0.764 ipTM=0.354 tol=0.625
2026-08-16 01:19:03,219 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78.6 pTM=0.762 ipTM=0.361 tol=0.159
2026-08-16 01:19:03,219 alphafold2_multimer_v3_model_2_seed_000 took 19.9s (2 recycles)
2026-08-16 01:19:03,229 reranking models by 'multimer' metric
2026-08-16 01:19:03,229 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.6 pTM=0.762 ipTM=0.361 ipSAE=0.107 pDockQ2=0.0619
2026-08-16 01:19:03,229 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.5 pTM=0.77 ipTM=0.347 ipSAE=0.101 pDockQ2=0.0677
2026-08-16 01:19:03,785 Query 3/10: rfd3_input_step2_anexina_binder_step2_round_05_0_model_0_top2_score0.799 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:17 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:19:04,108 Sleeping for 6s. Reason: PENDING
2026-08-16 01:19:10,440 Sleeping for 10s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-16 01:19:21,459 Sleeping for 8s. Reason: PENDING
2026-08-16 01:19:37,245 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.1 pTM=0.75 ipTM=0.275
2026-08-16 01:19:43,810 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=77.5 pTM=0.747 ipTM=0.246 tol=0.714
2026-08-16 01:19:50,410 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=76.9 pTM=0.75 ipTM=0.252 tol=0.489
2026-08-16 01:19:50,411 alphafold2_multimer_v3_model_1_seed_000 took 19.8s (2 recycles)
2026-08-16 01:19:57,057 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=75.1 pTM=0.737 ipTM=0.239
2026-08-16 01:20:03,715 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=76.1 pTM=0.742 ipTM=0.245 tol=1.18
2026-08-16 01:20:10,392 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=77.2 pTM=0.749 ipTM=0.271 tol=0.747
2026-08-16 01:20:17,095 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=77.4 pTM=0.746 ipTM=0.267 tol=0.677
2026-08-16 01:20:17,095 alphafold2_multimer_v3_model_2_seed_000 took 26.7s (3 recycles)
2026-08-16 01:20:17,105 reranking models by 'multimer' metric
2026-08-16 01:20:17,106 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=77.4 pTM=0.746 ipTM=0.267 ipSAE=0.0281 pDockQ2=0.037
2026-08-16 01:20:17,106 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=76.9 pTM=0.75 ipTM=0.252 ipSAE=0.0199 pDockQ2=0.036
2026-08-16 01:20:17,628 Query 4/10: rfd3_input_step2_anexina_binder_step2_round_05_0_model_0_top3_score0.780 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:20:17,943 Sleeping for 10s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-16 01:20:28,839 Sleeping for 8s. Reason: PENDING
2026-08-16 01:20:44,602 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=76 pTM=0.744 ipTM=0.258
2026-08-16 01:20:51,225 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=77.1 pTM=0.753 ipTM=0.276 tol=1.19
2026-08-16 01:20:57,878 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=76.8 pTM=0.745 ipTM=0.24 tol=0.484
2026-08-16 01:20:57,879 alphafold2_multimer_v3_model_1_seed_000 took 20.0s (2 recycles)
2026-08-16 01:21:04,573 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=77.1 pTM=0.766 ipTM=0.354
2026-08-16 01:21:11,276 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=76.4 pTM=0.74 ipTM=0.251 tol=1.33
2026-08-16 01:21:17,998 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=77.9 pTM=0.76 ipTM=0.329 tol=0.483
2026-08-16 01:21:17,998 alphafold2_multimer_v3_model_2_seed_000 took 20.1s (2 recycles)
2026-08-16 01:21:18,009 reranking models by 'multimer' metric
2026-08-16 01:21:18,009 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=77.9 pTM=0.76 ipTM=0.329 ipSAE=0.0606 pDockQ2=0.0628
2026-08-16 01:21:18,009 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=76.8 pTM=0.745 ipTM=0.24 ipSAE=0.018 pDockQ2=0.0347
2026-08-16 01:21:18,542 Query 5/10: rfd3_input_step2_anexina_binder_step2_round_05_0_model_0_top4_score0.798 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:17 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:21:18,850 Sleeping for 6s. Reason: PENDING
2026-08-16 01:21:25,144 Sleeping for 10s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-16 01:21:36,137 Sleeping for 6s. Reason: PENDING
2026-08-16 01:21:49,940 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82.8 pTM=0.801 ipTM=0.559
2026-08-16 01:21:56,567 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=82.8 pTM=0.807 ipTM=0.55 tol=0.829
2026-08-16 01:22:03,218 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.4 pTM=0.824 ipTM=0.599 tol=0.605
2026-08-16 01:22:09,887 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=85.9 pTM=0.832 ipTM=0.685 tol=0.241
2026-08-16 01:22:09,887 alphafold2_multimer_v3_model_1_seed_000 took 26.7s (3 recycles)
2026-08-16 01:22:16,595 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=82.8 pTM=0.802 ipTM=0.539
2026-08-16 01:22:23,307 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=80.9 pTM=0.784 ipTM=0.43 tol=0.574
2026-08-16 01:22:30,043 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=81.7 pTM=0.793 ipTM=0.466 tol=0.335
2026-08-16 01:22:30,043 alphafold2_multimer_v3_model_2_seed_000 took 20.1s (2 recycles)
2026-08-16 01:22:30,053 reranking models by 'multimer' metric
2026-08-16 01:22:30,053 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.9 pTM=0.832 ipTM=0.685 ipSAE=0.521 pDockQ2=0.261
2026-08-16 01:22:30,054 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=81.7 pTM=0.793 ipTM=0.466 ipSAE=0.206 pDockQ2=0.125
2026-08-16 01:22:30,608 Query 6/10: rfd3_input_step2_anexina_binder_step2_round_05_0_model_0_top5_score0.817 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:14 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:22:30,927 Sleeping for 8s. Reason: PENDING
2026-08-16 01:22:39,265 Sleeping for 5s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-16 01:22:45,267 Sleeping for 9s. Reason: PENDING
2026-08-16 01:23:02,095 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=80.8 pTM=0.792 ipTM=0.433
2026-08-16 01:23:08,726 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79.8 pTM=0.768 ipTM=0.333 tol=0.696
2026-08-16 01:23:15,388 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.5 pTM=0.768 ipTM=0.339 tol=0.327
2026-08-16 01:23:15,388 alphafold2_multimer_v3_model_1_seed_000 took 20.0s (2 recycles)
2026-08-16 01:23:22,089 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=80.4 pTM=0.788 ipTM=0.434
2026-08-16 01:23:28,784 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=77.9 pTM=0.755 ipTM=0.311 tol=1.08
2026-08-16 01:23:35,501 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=77.6 pTM=0.75 ipTM=0.304 tol=0.343
2026-08-16 01:23:35,502 alphafold2_multimer_v3_model_2_seed_000 took 20.1s (2 recycles)
2026-08-16 01:23:35,512 reranking models by 'multimer' metric
2026-08-16 01:23:35,512 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.5 pTM=0.768 ipTM=0.339 ipSAE=0.0834 pDockQ2=0.0712
2026-08-16 01:23:35,512 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=77.6 pTM=0.75 ipTM=0.304 ipSAE=0.0444 pDockQ2=0.0468
2026-08-16 01:23:36,040 Query 7/10: rfd3_input_step2_anexina_binder_step2_round_05_0_model_0_top6_score0.802 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:14 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:23:36,339 Sleeping for 6s. Reason: PENDING
2026-08-16 01:23:42,670 Sleeping for 7s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 01:18 remaining: 00:00]

2026-08-16 01:23:50,569 Sleeping for 6s. Reason: PENDING
2026-08-16 01:23:56,874 Sleeping for 10s. Reason: PENDING
2026-08-16 01:24:07,167 Sleeping for 7s. Reason: PENDING
2026-08-16 01:24:14,476 Sleeping for 7s. Reason: PENDING
2026-08-16 01:24:21,781 Sleeping for 9s. Reason: PENDING
2026-08-16 01:24:31,085 Sleeping for 7s. Reason: PENDING
2026-08-16 01:24:38,387 Sleeping for 5s. Reason: PENDING
2026-08-16 01:24:43,681 Sleeping for 8s. Reason: PENDING
2026-08-16 01:24:51,966 Sleeping for 10s. Reason: PENDING
2026-08-16 01:25:02,259 Sleeping for 6s. Reason: RUNNING
2026-08-16 01:25:15,925 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=76.4 pTM=0.747 ipTM=0.26
2026-08-16 01:25:22,416 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=77.7 pTM=0.75 ipTM=0.259 tol=0.825
2026-08-16 01:25:28,932 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=77.9 pTM=0.755 ipTM=0.278 tol=0.287
2026-08-16 01:25:28,932 alphafold2_multimer_v3_model_1_seed_000 took 19.6s (2 recycles)
2026-08-16 01:25:35,496 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=78 pTM=0.757 ipTM=0.312
2026-08-16 01:25:42,062 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=77.4 pTM=0.747 ipTM=0.281 tol=1.12
2026-08-16 01:25:48,663 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78.1 pTM=0.755 ipTM=0.314 tol=0.638
2026-08-16 01:25:55,285 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=78 pTM=0.752 ipTM=0.312 tol=0.438
2026-08-16 01:25:55,286 alphafold2_multimer_v3_model_2_seed_000 took 26.3s (3 recycles)
2026-08-16 01:25:55,297 reranking models by 'multimer' metric
2026-08-16 01:25:55,297 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78 pTM=0.752 ipTM=0.312 ipSAE=0.0493 pDockQ2=0.0484
2026-08-16 01:25:55,297 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=77.9 pTM=0.755 ipTM=0.278 ipSAE=0.0263 pDockQ2=0.0432
2026-08-16 01:25:56,076 Query 8/10: rfd3_input_step2_anexina_binder_step2_round_05_0_model_0_top7_score0.805 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:14 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:25:56,430 Sleeping for 5s. Reason: PENDING
2026-08-16 01:26:01,750 Sleeping for 8s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:06 remaining: 00:00]

2026-08-16 01:26:10,743 Sleeping for 6s. Reason: PENDING
2026-08-16 01:26:24,543 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=79.2 pTM=0.764 ipTM=0.333
2026-08-16 01:26:31,105 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.1 pTM=0.752 ipTM=0.27 tol=0.763
2026-08-16 01:26:37,713 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=77.9 pTM=0.757 ipTM=0.294 tol=0.393
2026-08-16 01:26:37,713 alphafold2_multimer_v3_model_1_seed_000 took 19.9s (2 recycles)
2026-08-16 01:26:44,359 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=77.4 pTM=0.742 ipTM=0.268
2026-08-16 01:26:51,011 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=77.3 pTM=0.741 ipTM=0.256 tol=0.669
2026-08-16 01:26:57,678 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78.6 pTM=0.752 ipTM=0.314 tol=0.704
2026-08-16 01:27:04,366 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=78.4 pTM=0.749 ipTM=0.298 tol=0.452
2026-08-16 01:27:04,366 alphafold2_multimer_v3_model_2_seed_000 took 26.6s (3 recycles)
2026-08-16 01:27:04,377 reranking models by 'multimer' metric
2026-08-16 01:27:04,377 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.4 pTM=0.749 ipTM=0.298 ipSAE=0.0479 pDockQ2=0.0502
2026-08-16 01:27:04,377 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=77.9 pTM=0.757 ipTM=0.294 ipSAE=0.0297 pDockQ2=0.0466
2026-08-16 01:27:04,900 Query 9/10: rfd3_input_step2_anexina_binder_step2_round_05_0_model_0_top8_score0.808 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:15 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:27:05,241 Sleeping for 7s. Reason: PENDING
2026-08-16 01:27:12,578 Sleeping for 7s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:05 remaining: 00:00]

2026-08-16 01:27:20,581 Sleeping for 5s. Reason: PENDING
2026-08-16 01:27:33,367 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.9 pTM=0.756 ipTM=0.29
2026-08-16 01:27:39,991 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80 pTM=0.776 ipTM=0.357 tol=0.608
2026-08-16 01:27:46,640 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=79.6 pTM=0.77 ipTM=0.328 tol=0.705
2026-08-16 01:27:53,311 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.9 pTM=0.776 ipTM=0.348 tol=0.48
2026-08-16 01:27:53,312 alphafold2_multimer_v3_model_1_seed_000 took 26.6s (3 recycles)
2026-08-16 01:28:00,021 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=78.9 pTM=0.763 ipTM=0.323
2026-08-16 01:28:06,730 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=79.4 pTM=0.768 ipTM=0.337 tol=0.333
2026-08-16 01:28:06,731 alphafold2_multimer_v3_model_2_seed_000 took 13.4s (1 recycles)
2026-08-16 01:28:06,741 reranking models by 'multimer' metric
2026-08-16 01:28:06,741 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.9 pTM=0.776 ipTM=0.348 ipSAE=0.077 pDockQ2=0.0743
2026-08-16 01:28:06,741 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=79.4 pTM=0.768 ipTM=0.337 ipSAE=0.127 pDockQ2=0.0661
2026-08-16 01:28:07,273 Query 10/10: rfd3_input_step2_anexina_binder_step2_round_05_0_model_0_top9_score0.809 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:28:07,605 Sleeping for 8s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]

2026-08-16 01:28:17,602 Sleeping for 9s. Reason: PENDING
2026-08-16 01:28:34,423 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=75.5 pTM=0.737 ipTM=0.228
2026-08-16 01:28:41,053 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=78.2 pTM=0.763 ipTM=0.308 tol=5.77
2026-08-16 01:28:47,730 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=76.6 pTM=0.747 ipTM=0.239 tol=1.8
2026-08-16 01:28:54,447 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=75.5 pTM=0.742 ipTM=0.221 tol=2.34
2026-08-16 01:28:54,448 alphafold2_multimer_v3_model_1_seed_000 took 26.7s (3 recycles)
2026-08-16 01:29:01,263 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=77.5 pTM=0.756 ipTM=0.315
2026-08-16 01:29:08,144 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=78.3 pTM=0.766 ipTM=0.336 tol=0.757
2026-08-16 01:29:15,103 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=77.3 pTM=0.754 ipTM=0.296 tol=0.451
2026-08-16 01:29:15,103 alphafold2_multimer_v3_model_2_seed_000 took 20.6s (2 recycles)
2026-08-16 01:29:15,114 reranking models by 'multimer' metric
2026-08-16 01:29:15,114 rank_001_alphafold2_multimer_v3_model_2_seed_000 pLDDT=77.3 pTM=0.754 ipTM=0.296 ipSAE=0.0454 pDockQ2=0.0452
2026-08-16 01:29:15,114 rank_002_alphafold2_multimer_v3_model_1_seed_000 pLDDT=75.5 pTM=0.742 ipTM=0.221 ipSAE=0.0143 pDockQ2=0.0342
2026-08-16 01:29:15,641 Done
Melhor candidato da rodada 5: rfd3_input_step2_anexina_binder_step2_round_05_0_model_0_top4_score0.798
Template escolhido para a proxima rodada: /kaggle/working/outputs/level2/refinement_rounds/round_05/af2_predictions_multimer/rfd3_input_step2_anexina_binder_step2_round_05_0_model_0/rfd3_input_step2_anexina_binder_step2_round_05_0_model_0_top10_score0.827_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

=== Rodada 6/6 ===
Usando como template: /kaggle/working/outputs/level2/refinement_rounds/round_05/af2_predictions_multimer/rfd3_input_step2_anexina_binder_step2_round_05_0_model_0/rfd3_input_step2_anexina_binder_step2_round_05_0_model_0_top10_score0.827_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

/usr/local/lib/python3.12/dist-packages/hydra/_internal/config_loader_impl.py:216: UserWarning: provider=hydra.searchpath in main, path=configs is not available.
  warnings.warn(
Environment variable CCD_MIRROR_PATH not set. Will not be able to use function requiring this variable. To set it you may:
  (1) add the line 'export VAR_NAME=path/to/variable' to your .bashrc or .zshrc file
  (2) set it in your current shell with 'export VAR_NAME=path/to/variable'
  (3) write it to a .env file in the root of the atomworks.io repository
Environment variable PDB_MIRROR_PATH not set. Will not be able to use function requiring this variable. To set it you may:
  (1) add the line 'export VAR_NAME=path/to/variable' to your .bashrc or .zshrc file
  (2) set it in your current shell with 'export VAR_NAME=path/to/variable'
  (3) write it to a .env file in the root of the atomworks.io repository
01:29:26 DEBUG transforms: Debug mode is on
01:29:28 INFO rfd3.engine: [rank: 0] Outputs will be written to /kaggle/working/outputs/level2/refinement_rounds/round_06/rfd3_designs.
01:29:28 INFO rfd3.engine: [rank: 0] Found 0 existing example IDs in the output directory (0 total).
Using bfloat16 Automatic Mixed Precision (AMP)
01:29:37 WARNING atomworks.io: We can't fix formal charges without building from templates, as we need to know the true number of hydrogens bonded to a given atom, not the inferred number. This may lead to occasional inaccuracies after adding inter-residue bonds. To avoid this and fix formal charges, set `add_missing_atoms = True`.
01:29:38 WARNING atomworks.io: The `extra_fields` argument will be ignored if there is no CIF file input.
01:29:45 INFO rfd3.engine: [rank: 0] Finished inference batch in 6.90 seconds.
01:29:45 INFO rfd3.engine: [rank: 0] Outputs for rfd3_input_step2_anexina_binder_step2_round_06_0_model_0 written to /kaggle/working/outputs/level2/refinement_rounds/round_06/rfd3_designs/rfd3_input_step2_anexina_binder_step2_round_06_0_model_0.

✓ Convertido com sucesso: rfd3_input_step2_anexina_binder_step2_round_06_0_model_0.pdb
Iniciando a filtragem rigorosa de backbones...
Filtragem concluida!
✓ Total avaliados: 1
✓ Total no filtro estrito (fracao >= 0.30 e clashes <= 0): 1
🏆 Aprovados e enviados para o MPNN (Top 10): 1
Desenhando sequencias para o backbone: rfd3_input_step2_anexina_binder_step2_round_06_0_model_0
Filtrando e formatando complexos para o AlphaFold Multimer...
✓ Pronto! 10 complexos organizados para validacao do fragmento.
Validando sequencias do design: rfd3_input_step2_anexina_binder_step2_round_06_0_model_0

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-16 01:31:30,745 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)
2026-08-16 01:31:31,442 Running on GPU
2026-08-16 01:31:31,716 Found 5 citations for tools or databases
2026-08-16 01:31:31,778 Query 1/10: rfd3_input_step2_anexina_binder_step2_round_06_0_model_0_top10_score0.742 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:15 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:31:32,491 Sleeping for 7s. Reason: PENDING
2026-08-16 01:31:39,851 Sleeping for 7s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:10 remaining: 00:00]
/usr/local/lib/python3.12/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)

2026-08-16 01:31:47,861 Sleeping for 10s. Reason: PENDING
2026-08-16 01:32:45,584 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82.5 pTM=0.8 ipTM=0.441
2026-08-16 01:33:22,749 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=82.3 pTM=0.789 ipTM=0.404 tol=2.35
2026-08-16 01:33:30,171 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=82.8 pTM=0.798 ipTM=0.429 tol=1.13
2026-08-16 01:33:37,654 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=82.5 pTM=0.788 ipTM=0.399 tol=0.994
2026-08-16 01:33:37,655 alphafold2_multimer_v3_model_1_seed_000 took 91.3s (3 recycles)
2026-08-16 01:33:44,993 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=79.2 pTM=0.771 ipTM=0.35
2026-08-16 01:33:52,139 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=80.3 pTM=0.766 ipTM=0.338 tol=1.11
2026-08-16 01:33:59,161 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=80.4 pTM=0.763 ipTM=0.329 tol=0.732
2026-08-16 01:34:06,179 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=80.9 pTM=0.772 ipTM=0.363 tol=1.04
2026-08-16 01:34:06,179 alphafold2_multimer_v3_model_2_seed_000 took 28.5s (3 recycles)
2026-08-16 01:34:06,190 reranking models by 'multimer' metric
2026-08-16 01:34:06,190 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.5 pTM=0.788 ipTM=0.399 ipSAE=0.12 pDockQ2=0.223
2026-08-16 01:34:06,190 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=80.9 pTM=0.772 ipTM=0.363 ipSAE=0.0823 pDockQ2=0.135
2026-08-16 01:34:06,735 Query 2/10: rfd3_input_step2_anexina_binder_step2_round_06_0_model_0_top1_score0.709 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:13 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:34:07,079 Sleeping for 6s. Reason: PENDING
2026-08-16 01:34:13,402 Sleeping for 6s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-16 01:34:20,412 Sleeping for 7s. Reason: PENDING
2026-08-16 01:34:35,511 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78 pTM=0.754 ipTM=0.279
2026-08-16 01:34:42,529 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=85.9 pTM=0.823 ipTM=0.555 tol=2.54
2026-08-16 01:34:49,579 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=85.4 pTM=0.817 ipTM=0.568 tol=0.349
2026-08-16 01:34:49,580 alphafold2_multimer_v3_model_1_seed_000 took 21.1s (2 recycles)
2026-08-16 01:34:56,785 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=76.9 pTM=0.741 ipTM=0.261
2026-08-16 01:35:04,095 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=80.3 pTM=0.764 ipTM=0.344 tol=0.79
2026-08-16 01:35:11,461 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=79.7 pTM=0.759 ipTM=0.342 tol=0.144
2026-08-16 01:35:11,461 alphafold2_multimer_v3_model_2_seed_000 took 21.9s (2 recycles)
2026-08-16 01:35:11,471 reranking models by 'multimer' metric
2026-08-16 01:35:11,471 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=85.4 pTM=0.817 ipTM=0.568 ipSAE=0.307 pDockQ2=0.28
2026-08-16 01:35:11,472 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=79.7 pTM=0.759 ipTM=0.342 ipSAE=0.0815 pDockQ2=0.0687
2026-08-16 01:35:11,980 Query 3/10: rfd3_input_step2_anexina_binder_step2_round_06_0_model_0_top2_score0.721 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:16 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:35:12,311 Sleeping for 9s. Reason: PENDING
2026-08-16 01:35:21,655 Sleeping for 6s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:20 remaining: 00:00]

2026-08-16 01:35:28,638 Sleeping for 5s. Reason: PENDING
2026-08-16 01:35:33,967 Sleeping for 7s. Reason: PENDING
2026-08-16 01:35:41,287 Sleeping for 7s. Reason: RUNNING
2026-08-16 01:35:56,504 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.7 pTM=0.764 ipTM=0.328
2026-08-16 01:36:03,587 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.7 pTM=0.774 ipTM=0.354 tol=1.39
2026-08-16 01:36:10,825 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=83.3 pTM=0.802 ipTM=0.451 tol=0.376
2026-08-16 01:36:10,826 alphafold2_multimer_v3_model_1_seed_000 took 21.4s (2 recycles)
2026-08-16 01:36:18,204 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=78.4 pTM=0.761 ipTM=0.359
2026-08-16 01:36:25,562 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=79.6 pTM=0.751 ipTM=0.315 tol=0.961
2026-08-16 01:36:32,773 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=77.1 pTM=0.736 ipTM=0.263 tol=0.498
2026-08-16 01:36:32,773 alphafold2_multimer_v3_model_2_seed_000 took 21.9s (2 recycles)
2026-08-16 01:36:32,783 reranking models by 'multimer' metric
2026-08-16 01:36:32,783 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.3 pTM=0.802 ipTM=0.451 ipSAE=0.193 pDockQ2=0.138
2026-08-16 01:36:32,783 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=77.1 pTM=0.736 ipTM=0.263 ipSAE=0.0257 pDockQ2=0.0453
2026-08-16 01:36:33,285 Query 4/10: rfd3_input_step2_anexina_binder_step2_round_06_0_model_0_top3_score0.718 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:19 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:36:33,641 Sleeping for 9s. Reason: PENDING
2026-08-16 01:36:42,981 Sleeping for 9s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:14 remaining: 00:00]

2026-08-16 01:36:53,014 Sleeping for 6s. Reason: PENDING
2026-08-16 01:36:59,345 Sleeping for 7s. Reason: RUNNING
2026-08-16 01:37:14,503 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.8 pTM=0.763 ipTM=0.326
2026-08-16 01:37:21,530 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=86.8 pTM=0.823 ipTM=0.734 tol=2.24
2026-08-16 01:37:28,690 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=86.1 pTM=0.822 ipTM=0.705 tol=0.44
2026-08-16 01:37:28,691 alphafold2_multimer_v3_model_1_seed_000 took 21.3s (2 recycles)
2026-08-16 01:37:36,008 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=80.2 pTM=0.757 ipTM=0.344
2026-08-16 01:37:43,392 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=82.4 pTM=0.781 ipTM=0.425 tol=2.24
2026-08-16 01:37:50,700 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=82.1 pTM=0.775 ipTM=0.396 tol=0.59
2026-08-16 01:37:57,886 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=79.8 pTM=0.755 ipTM=0.333 tol=0.393
2026-08-16 01:37:57,887 alphafold2_multimer_v3_model_2_seed_000 took 29.2s (3 recycles)
2026-08-16 01:37:57,896 reranking models by 'multimer' metric
2026-08-16 01:37:57,897 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=86.1 pTM=0.822 ipTM=0.705 ipSAE=0.519 pDockQ2=0.269
2026-08-16 01:37:57,897 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=79.8 pTM=0.755 ipTM=0.333 ipSAE=0.0812 pDockQ2=0.0708
2026-08-16 01:37:58,404 Query 5/10: rfd3_input_step2_anexina_binder_step2_round_06_0_model_0_top4_score0.726 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:37:58,738 Sleeping for 9s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]

2026-08-16 01:38:08,726 Sleeping for 8s. Reason: PENDING
2026-08-16 01:38:24,828 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=80.4 pTM=0.779 ipTM=0.385
2026-08-16 01:38:31,852 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=81.9 pTM=0.782 ipTM=0.389 tol=2.03
2026-08-16 01:38:38,933 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=82.7 pTM=0.791 ipTM=0.418 tol=0.856
2026-08-16 01:38:46,170 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=82.3 pTM=0.784 ipTM=0.406 tol=0.727
2026-08-16 01:38:46,171 alphafold2_multimer_v3_model_1_seed_000 took 28.4s (3 recycles)
2026-08-16 01:38:53,555 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=77.9 pTM=0.754 ipTM=0.318
2026-08-16 01:39:00,923 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=79.9 pTM=0.764 ipTM=0.342 tol=1.26
2026-08-16 01:39:08,153 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=80.7 pTM=0.766 ipTM=0.366 tol=1.72
2026-08-16 01:39:15,275 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=80.4 pTM=0.761 ipTM=0.351 tol=1.25
2026-08-16 01:39:15,275 alphafold2_multimer_v3_model_2_seed_000 took 29.1s (3 recycles)
2026-08-16 01:39:15,285 reranking models by 'multimer' metric
2026-08-16 01:39:15,285 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=82.3 pTM=0.784 ipTM=0.406 ipSAE=0.144 pDockQ2=0.15
2026-08-16 01:39:15,285 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=80.4 pTM=0.761 ipTM=0.351 ipSAE=0.107 pDockQ2=0.094
2026-08-16 01:39:15,791 Query 6/10: rfd3_input_step2_anexina_binder_step2_round_06_0_model_0_top5_score0.727 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:16 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:39:16,126 Sleeping for 7s. Reason: PENDING
2026-08-16 01:39:23,447 Sleeping for 8s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-16 01:39:32,448 Sleeping for 9s. Reason: PENDING
2026-08-16 01:39:49,559 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.1 pTM=0.75 ipTM=0.271
2026-08-16 01:39:56,581 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=79.7 pTM=0.762 ipTM=0.304 tol=1.03
2026-08-16 01:40:03,699 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.5 pTM=0.779 ipTM=0.363 tol=1.07
2026-08-16 01:40:10,956 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79.8 pTM=0.764 ipTM=0.315 tol=0.524
2026-08-16 01:40:10,956 alphafold2_multimer_v3_model_1_seed_000 took 28.5s (3 recycles)
2026-08-16 01:40:18,325 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=81.9 pTM=0.789 ipTM=0.434
2026-08-16 01:40:25,676 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=79.5 pTM=0.756 ipTM=0.308 tol=1.61
2026-08-16 01:40:32,893 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=79.4 pTM=0.757 ipTM=0.311 tol=0.479
2026-08-16 01:40:32,893 alphafold2_multimer_v3_model_2_seed_000 took 21.9s (2 recycles)
2026-08-16 01:40:32,903 reranking models by 'multimer' metric
2026-08-16 01:40:32,904 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79.8 pTM=0.764 ipTM=0.315 ipSAE=0.0623 pDockQ2=0.0896
2026-08-16 01:40:32,904 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=79.4 pTM=0.757 ipTM=0.311 ipSAE=0.0533 pDockQ2=0.0719
2026-08-16 01:40:33,410 Query 7/10: rfd3_input_step2_anexina_binder_step2_round_06_0_model_0_top6_score0.733 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:18 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:40:33,748 Sleeping for 5s. Reason: PENDING
2026-08-16 01:40:39,079 Sleeping for 5s. Reason: RUNNING
2026-08-16 01:40:44,435 Sleeping for 7s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-16 01:40:52,412 Sleeping for 7s. Reason: PENDING
2026-08-16 01:41:07,565 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=77.9 pTM=0.752 ipTM=0.275
2026-08-16 01:41:14,590 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=82.4 pTM=0.79 ipTM=0.408 tol=1.77
2026-08-16 01:41:21,706 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=80.9 pTM=0.774 ipTM=0.354 tol=0.413
2026-08-16 01:41:21,707 alphafold2_multimer_v3_model_1_seed_000 took 21.2s (2 recycles)
2026-08-16 01:41:28,981 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=77.9 pTM=0.743 ipTM=0.256
2026-08-16 01:41:36,356 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=79.5 pTM=0.758 ipTM=0.309 tol=1.14
2026-08-16 01:41:43,680 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=80 pTM=0.761 ipTM=0.329 tol=1.37
2026-08-16 01:41:50,875 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=78.8 pTM=0.747 ipTM=0.278 tol=0.744
2026-08-16 01:41:50,876 alphafold2_multimer_v3_model_2_seed_000 took 29.2s (3 recycles)
2026-08-16 01:41:50,885 reranking models by 'multimer' metric
2026-08-16 01:41:50,886 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.9 pTM=0.774 ipTM=0.354 ipSAE=0.0817 pDockQ2=0.0804
2026-08-16 01:41:50,886 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.8 pTM=0.747 ipTM=0.278 ipSAE=0.0456 pDockQ2=0.0519
2026-08-16 01:41:51,417 Query 8/10: rfd3_input_step2_anexina_binder_step2_round_06_0_model_0_top7_score0.737 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:14 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:41:51,730 Sleeping for 5s. Reason: PENDING
2026-08-16 01:41:57,019 Sleeping for 8s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-16 01:42:05,928 Sleeping for 7s. Reason: PENDING
2026-08-16 01:42:21,017 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=82.4 pTM=0.794 ipTM=0.416
2026-08-16 01:42:28,039 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=80.6 pTM=0.785 ipTM=0.371 tol=1.38
2026-08-16 01:42:35,170 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=81.3 pTM=0.793 ipTM=0.406 tol=1.37
2026-08-16 01:42:42,458 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=80.8 pTM=0.787 ipTM=0.38 tol=0.899
2026-08-16 01:42:42,459 alphafold2_multimer_v3_model_1_seed_000 took 28.5s (3 recycles)
2026-08-16 01:42:49,869 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=82.2 pTM=0.788 ipTM=0.426
2026-08-16 01:42:57,188 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=80.4 pTM=0.779 ipTM=0.382 tol=1.51
2026-08-16 01:43:04,371 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=78.8 pTM=0.752 ipTM=0.298 tol=0.742
2026-08-16 01:43:11,475 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=79.1 pTM=0.764 ipTM=0.329 tol=0.623
2026-08-16 01:43:11,476 alphafold2_multimer_v3_model_2_seed_000 took 29.0s (3 recycles)
2026-08-16 01:43:11,486 reranking models by 'multimer' metric
2026-08-16 01:43:11,486 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=80.8 pTM=0.787 ipTM=0.38 ipSAE=0.129 pDockQ2=0.121
2026-08-16 01:43:11,486 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=79.1 pTM=0.764 ipTM=0.329 ipSAE=0.0679 pDockQ2=0.0784
2026-08-16 01:43:12,223 Query 9/10: rfd3_input_step2_anexina_binder_step2_round_06_0_model_0_top8_score0.741 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:13 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:43:12,864 Sleeping for 5s. Reason: PENDING
2026-08-16 01:43:18,173 Sleeping for 7s. Reason: RUNNING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:09 remaining: 00:00]

2026-08-16 01:43:26,099 Sleeping for 9s. Reason: PENDING
2026-08-16 01:43:43,230 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=84.6 pTM=0.812 ipTM=0.613
2026-08-16 01:43:50,250 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.5 pTM=0.802 ipTM=0.46 tol=2.58
2026-08-16 01:43:57,349 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=84.2 pTM=0.812 ipTM=0.515 tol=1.13
2026-08-16 01:44:04,601 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=84 pTM=0.808 ipTM=0.494 tol=0.528
2026-08-16 01:44:04,602 alphafold2_multimer_v3_model_1_seed_000 took 28.4s (3 recycles)
2026-08-16 01:44:11,986 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=83.2 pTM=0.793 ipTM=0.521
2026-08-16 01:44:19,322 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=81.2 pTM=0.777 ipTM=0.388 tol=1.28
2026-08-16 01:44:26,526 alphafold2_multimer_v3_model_2_seed_000 recycle=2 pLDDT=80.9 pTM=0.778 ipTM=0.395 tol=0.613
2026-08-16 01:44:33,647 alphafold2_multimer_v3_model_2_seed_000 recycle=3 pLDDT=81.9 pTM=0.785 ipTM=0.421 tol=0.749
2026-08-16 01:44:33,648 alphafold2_multimer_v3_model_2_seed_000 took 29.0s (3 recycles)
2026-08-16 01:44:33,658 reranking models by 'multimer' metric
2026-08-16 01:44:33,658 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=84 pTM=0.808 ipTM=0.494 ipSAE=0.261 pDockQ2=0.367
2026-08-16 01:44:33,658 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=81.9 pTM=0.785 ipTM=0.421 ipSAE=0.206 pDockQ2=0.252
2026-08-16 01:44:34,165 Query 10/10: rfd3_input_step2_anexina_binder_step2_round_06_0_model_0_top9_score0.732 (length 118)

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:08 remaining: 00:00]
SUBMIT:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]

2026-08-16 01:44:34,503 Sleeping for 7s. Reason: PENDING

COMPLETE: 100%|██████████| 300/300 [elapsed: 00:07 remaining: 00:00]

2026-08-16 01:44:42,529 Sleeping for 7s. Reason: PENDING
2026-08-16 01:44:57,642 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=78.6 pTM=0.769 ipTM=0.354
2026-08-16 01:45:04,669 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=83.8 pTM=0.81 ipTM=0.531 tol=2.62
2026-08-16 01:45:11,734 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=82.5 pTM=0.798 ipTM=0.461 tol=1.43
2026-08-16 01:45:18,943 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=83.3 pTM=0.804 ipTM=0.484 tol=1.13
2026-08-16 01:45:18,943 alphafold2_multimer_v3_model_1_seed_000 took 28.3s (3 recycles)
2026-08-16 01:45:26,295 alphafold2_multimer_v3_model_2_seed_000 recycle=0 pLDDT=78.7 pTM=0.758 ipTM=0.329
2026-08-16 01:45:33,663 alphafold2_multimer_v3_model_2_seed_000 recycle=1 pLDDT=78.8 pTM=0.75 ipTM=0.3 tol=0.48
2026-08-16 01:45:33,664 alphafold2_multimer_v3_model_2_seed_000 took 14.7s (1 recycles)
2026-08-16 01:45:33,674 reranking models by 'multimer' metric
2026-08-16 01:45:33,674 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=83.3 pTM=0.804 ipTM=0.484 ipSAE=0.246 pDockQ2=0.242
2026-08-16 01:45:33,674 rank_002_alphafold2_multimer_v3_model_2_seed_000 pLDDT=78.8 pTM=0.75 ipTM=0.3 ipSAE=0.0508 pDockQ2=0.0847
2026-08-16 01:45:34,178 Done
Melhor candidato da rodada 6: rfd3_input_step2_anexina_binder_step2_round_06_0_model_0_top3_score0.718
Template escolhido para a proxima rodada: /kaggle/working/outputs/level2/refinement_rounds/round_06/af2_predictions_multimer/rfd3_input_step2_anexina_binder_step2_round_06_0_model_0/rfd3_input_step2_anexina_binder_step2_round_06_0_model_0_top10_score0.742_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

Resumo das rodadas de refinamento:

,Rodada,Rank,Candidato,ipTM (Afinidade),pLDDT do Binder,pLDDT da Proteina,pTM Global,Template
0,1,1,rfd3_input_step2_anexina_binder_step2_round_01...,0.36,92.1,45.2,0.74,/kaggle/working/outputs/level2/refinement_roun...
1,1,2,rfd3_input_step2_anexina_binder_step2_round_01...,0.35,91.9,44.1,0.74,/kaggle/working/outputs/level2/refinement_roun...
2,1,3,rfd3_input_step2_anexina_binder_step2_round_01...,0.34,92.6,43.4,0.75,/kaggle/working/outputs/level2/refinement_roun...
3,1,4,rfd3_input_step2_anexina_binder_step2_round_01...,0.33,93.4,43.3,0.76,/kaggle/working/outputs/level2/refinement_roun...
4,2,1,rfd3_input_step2_anexina_binder_step2_round_02...,0.66,94.9,60.5,0.83,/kaggle/working/outputs/level2/refinement_roun...
5,2,2,rfd3_input_step2_anexina_binder_step2_round_02...,0.64,94.3,64.7,0.81,/kaggle/working/outputs/level2/refinement_roun...
6,2,3,rfd3_input_step2_anexina_binder_step2_round_02...,0.62,94.5,65.4,0.82,/kaggle/working/outputs/level2/refinement_roun...
7,2,4,rfd3_input_step2_anexina_binder_step2_round_02...,0.60,94.0,60.0,0.82,/kaggle/working/outputs/level2/refinement_roun...
8,3,1,rfd3_input_step2_anexina_binder_step2_round_03...,0.67,95.9,68.8,0.85,/kaggle/working/outputs/level2/refinement_roun...
9,3,2,rfd3_input_step2_anexina_binder_step2_round_03...,0.66,96.3,68.0,0.85,/kaggle/working/outputs/level2/refinement_roun...
10,3,3,rfd3_input_step2_anexina_binder_step2_round_03...,0.64,96.0,62.4,0.83,/kaggle/working/outputs/level2/refinement_roun...
11,3,4,rfd3_input_step2_anexina_binder_step2_round_03...,0.55,94.1,61.1,0.81,/kaggle/working/outputs/level2/refinement_roun...
12,4,1,rfd3_input_step2_anexina_binder_step2_round_04...,0.38,94.2,46.3,0.78,/kaggle/working/outputs/level2/refinement_roun...
13,4,2,rfd3_input_step2_anexina_binder_step2_round_04...,0.36,93.6,44.3,0.78,/kaggle/working/outputs/level2/refinement_roun...
14,4,3,rfd3_input_step2_anexina_binder_step2_round_04...,0.35,93.9,45.3,0.77,/kaggle/working/outputs/level2/refinement_roun...
15,4,4,rfd3_input_step2_anexina_binder_step2_round_04...,0.35,92.5,43.2,0.77,/kaggle/working/outputs/level2/refinement_roun...
16,5,1,rfd3_input_step2_anexina_binder_step2_round_05...,0.69,95.5,59.3,0.83,/kaggle/working/outputs/level2/refinement_roun...
17,5,2,rfd3_input_step2_anexina_binder_step2_round_05...,0.47,92.7,50.7,0.79,/kaggle/working/outputs/level2/refinement_roun...
18,5,3,rfd3_input_step2_anexina_binder_step2_round_05...,0.36,91.0,43.5,0.76,/kaggle/working/outputs/level2/refinement_roun...
19,5,4,rfd3_input_step2_anexina_binder_step2_round_05...,0.35,93.2,42.5,0.78,/kaggle/working/outputs/level2/refinement_roun...
20,6,1,rfd3_input_step2_anexina_binder_step2_round_06...,0.70,96.3,57.3,0.82,/kaggle/working/outputs/level2/refinement_roun...
21,6,2,rfd3_input_step2_anexina_binder_step2_round_06...,0.57,96.1,55.6,0.82,/kaggle/working/outputs/level2/refinement_roun...
22,6,3,rfd3_input_step2_anexina_binder_step2_round_06...,0.49,95.2,52.4,0.81,/kaggle/working/outputs/level2/refinement_roun...
23,6,4,rfd3_input_step2_anexina_binder_step2_round_06...,0.48,95.1,50.4,0.80,/kaggle/working/outputs/level2/refinement_roun...

Melhor estrutura final salva em: /kaggle/working/outputs/level2/refinement_rounds/round_06/af2_predictions_multimer/rfd3_input_step2_anexina_binder_step2_round_06_0_model_0/rfd3_input_step2_anexina_binder_step2_round_06_0_model_0_top10_score0.742_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

In [20]:
!rm -rf ProteinMPNN
!rm -rf models